Repository celestiaorg/celestia-app, pull requests merged in 2022-11, with the labels that each got.

#835 ADR square size independent message commitments
  docs/architecture/adr-008-square-size-independent-message-commitments.md
  docs/architecture/assets/complexity.png
  docs/architecture/assets/interactive-commitment.png
  docs/architecture/assets/interactive-commitment2.png
  docs/architecture/assets/multiple-blocks.png
  docs/architecture/assets/padding-savings.png
  docs/architecture/assets/row-size-comparison.png
  docs/architecture/assets/size-dependent-commitment.png
  docs/architecture/assets/size-independent-commitment.png
Labels: documentation, C: Celestia app, discussion

#948 Update docs for payment module
  x/payment/client/cli/query.go
  x/payment/client/cli/tx.go
  x/payment/doc.go
  x/payment/keeper/keeper.go
  x/payment/module.go
  x/payment/payfordata.go
  x/payment/spec/docs.md
  x/payment/types/events.go
Labels: documentation

#959 docs: add details to positive celestia-app changes
  docs/architecture/adr-008-square-size-independent-message-commitments.md
Labels: documentation

#946 feat: charge gas per message shares
  x/payment/keeper/gas_test.go
  x/payment/keeper/keeper.go
Labels: C: Celestia app

#977 Revert "chore!: rename `TIA` to `CLS` (#859)"
  app/app.go
  app/test/block_size_test.go
  scripts/single-node.sh
  testutil/test_app.go
  x/payment/types/builder_options.go
  x/payment/types/payfordata_test.go
Labels: T: chore

#975 feat: remove unnecessary QGB code
  proto/payment/query.proto
  proto/qgb/genesis.proto
  proto/qgb/msgs.proto
  proto/qgb/query.proto
  x/qgb/handler.go
  x/qgb/keeper/msg_server.go
  x/qgb/module.go
  x/qgb/types/codec.go
  x/qgb/types/data_commitment_confirm.go
  x/qgb/types/errors.go
  x/qgb/types/genesis.pb.go
  x/qgb/types/msgs.pb.go
  x/qgb/types/msgs.pb.gw.go
  x/qgb/types/query.pb.go
  x/qgb/types/valset_confirm.go
Labels: C: QGB

#983 docs: update "How is the `MessageShareCommitment` generated?"
  x/payment/spec/docs.md
Labels: documentation

#987 chore!: use different default codec
  pkg/appconsts/appconsts.go
  pkg/wrapper/nmt_wrapper_test.go
Labels: C: Celestia app, consensus breaking

#978 chore!: rename PFD -> PFB
  README.md
  app/estimate_square_size.go
  app/estimate_square_size_test.go
  app/malleate_txs.go
  app/parse_txs.go
  app/prepare_proposal.go
  app/process_proposal.go
  app/test/block_size_test.go
  app/test/fuzz_abci_test.go
  app/test/prepare_proposal_test.go
  app/test/process_proposal_test.go
  app/test_util.go
  docs/architecture/adr-001-abci++-adoption.md
  docs/architecture/adr-006-non-interactive-defaults.md
  docs/architecture/adr-007-universal-share-prefix.md
  docs/architecture/adr-008-square-size-independent-message-commitments.md
  proto/blob/tx.proto
  testutil/blob/testutil.go
  testutil/testnode/node_interaction_api.go
  x/blob/client/cli/tx.go
  x/blob/client/cli/wirepayfordata.go
  x/blob/client/testutil/integration_test.go
  x/blob/handler.go
  x/blob/keeper/gas_test.go
  x/blob/keeper/keeper.go
  x/blob/payforblob.go
  x/blob/spec/docs.md
  x/blob/types/builder_options.go
  x/blob/types/builder_test.go
  x/blob/types/codec.go
  x/blob/types/events.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
  x/blob/types/tx.pb.go
  x/blob/types/tx.pb.gw.go
  x/blob/types/verify_sigs.go
  x/blob/types/wirepayforblob.go
  x/blob/types/wirepayfordata_test.go
Labels: C: Celestia app, T: chore, consensus breaking

#984 feat!: square size independent share commitments (#937)
  app/estimate_square_size.go
  app/estimate_square_size_test.go
  app/malleate_txs.go
  app/test/block_size_test.go
  app/test/prepare_proposal_test.go
  app/test/process_proposal_test.go
  app/test_util.go
  docs/architecture/adr-007-universal-share-prefix.md
  docs/architecture/adr-008-square-size-independent-message-commitments.md
  pkg/appconsts/appconsts.go
  pkg/inclusion/paths.go
  pkg/inclusion/paths_test.go
  pkg/shares/utils.go
  proto/blob/tx.proto
  testutil/blob/testutil.go
  x/blob/client/cli/wirepayfordata.go
  x/blob/payforblob.go
  x/blob/spec/docs.md
  x/blob/types/builder_test.go
  x/blob/types/errors.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
  x/blob/types/tx.pb.go
  x/blob/types/verify_sigs.go
  x/blob/types/wirepayforblob.go
  x/blob/types/wirepayfordata_test.go
Labels: C: Celestia app, consensus breaking

#998 chore: test for gas usage
  app/test/block_size_test.go
Labels: testing

#1000 chore: change the default minimum gas fee to something non-zero
  cmd/celestia-appd/cmd/root.go
Labels: C: Celestia app

#965 feat: add param for gas per message byte
  proto/blob/params.proto
  x/blob/keeper/keeper.go
  x/blob/keeper/params.go
  x/blob/keeper/params_test.go
  x/blob/types/genesis_test.go
  x/blob/types/params.go
  x/blob/types/params.pb.go
Labels: C: Celestia app

#966 fix: test packages and coverage generation
  .github/workflows/test.yml
Labels: CI

#1008 feat!: override default mempool params
  cmd/celestia-appd/cmd/root.go
Labels: breaking

#1015 chore: uncomment out tests
  pkg/shares/shares_test.go
Labels: testing

#1017 fix: add git to Dockerfile build
  Dockerfile
Labels: docker

#1023 chore!: upgrade to celestia-core `v1.8.0-tm-v0.34.20`
  app/estimate_square_size_test.go
  app/malleate_txs.go
  app/parse_txs.go
  app/prepare_proposal.go
  app/process_proposal.go
  app/test/block_size_test.go
  app/test/prepare_proposal_test.go
  app/test/process_proposal_test.go
  app/test_util.go
  go.mod
  go.sum
  pkg/prove/proof.go
  pkg/prove/proof_test.go
  pkg/shares/parse_sparse_shares.go
  pkg/shares/share_merging.go
  pkg/shares/share_merging_test.go
  pkg/shares/share_splitting.go
  pkg/shares/shares_test.go
  pkg/shares/sparse_shares_test.go
  pkg/shares/split_sparse_shares.go
  pkg/shares/utils.go
  pkg/shares/utils_test.go
  testutil/testnode/full_node_test.go
  x/blob/types/payforblob.go
  x/blob/types/wirepayforblob.go
Labels: dependencies, consensus breaking

#1021 feat: QGB support specifying Tx fee for orchestrator
  e2e/qgb/celestia-app/genesis.json
  e2e/qgb/scripts/start_node_and_create_validator.sh
  x/qgb/orchestrator/config.go
  x/qgb/orchestrator/orchestrator.go
  x/qgb/orchestrator/orchestrator_command.go
Labels: C: QGB

#1038 chore!: refactor the testnode to expose the genesis state
  testutil/testnode/full_node.go
  testutil/testnode/full_node_test.go
  testutil/testnode/node_init.go
Labels: C: Celestia app

#1028 feat: specify share version in `MsgWirePayForBlob`
  app/estimate_square_size.go
  app/estimate_square_size_test.go
  app/test/block_size_test.go
  app/test/prepare_proposal_test.go
  app/test/process_proposal_test.go
  app/test_util.go
  go.mod
  go.sum
  pkg/appconsts/appconsts.go
  pkg/shares/compact_shares_test.go
  pkg/shares/share_merging_test.go
  pkg/shares/share_splitting.go
  pkg/shares/sparse_shares_test.go
  pkg/shares/split_compact_shares.go
  pkg/shares/split_compact_shares_test.go
  pkg/shares/split_sparse_shares.go
  pkg/shares/utils.go
  proto/blob/tx.proto
  testutil/blob/testutil.go
  testutil/testnode/node_interaction_api.go
  x/blob/client/cli/wirepayfordata.go
  x/blob/payforblob.go
  x/blob/types/builder_test.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
  x/blob/types/tx.pb.go
  x/blob/types/wirepayforblob.go
  x/blob/types/wirepayfordata_test.go
Labels: C: Celestia app, consensus breaking

#1051 chore!(testnode): return errors in cleanup functions and wait for cleanup
  testutil/testnode/full_node.go
  testutil/testnode/full_node_test.go
  testutil/testnode/rpc_client.go
Labels: C: Celestia app, testing

#939 specs: two reserved bytes
  specs/src/specs/consensus.md
  specs/src/specs/data_structures.md
  specs/src/specs/figures/compact_continuation_share.dot
  specs/src/specs/figures/compact_continuation_share.svg
  specs/src/specs/figures/compact_start_share.dot
  specs/src/specs/figures/compact_start_share.svg
  specs/src/specs/figures/sparse_continuation_share.dot
  specs/src/specs/figures/sparse_continuation_share.svg
  specs/src/specs/figures/sparse_start_share.dot
  specs/src/specs/figures/sparse_start_share.svg
Labels: specs

#1052 docs: add qgb module readme
  x/qgb/README.md
Labels: documentation, C: QGB

#1046 chore: remove unnecessary QGB BridgeID
  go.mod
  go.sum
  x/qgb/types/abi_consts.go
  x/qgb/types/valset.go
Labels: C: QGB
