Repository celestiaorg/celestia-app, pull requests merged in 2022-09, with the labels that each got.

#672 chore: delete githooks
  contrib/githooks/README.md
  contrib/githooks/pre-commit
Labels: T: chore

#549 feat: Cache and traverse nmt sub tree roots
  pkg/inclusion/nmt_caching.go
  pkg/inclusion/nmt_caching_test.go
  testutil/coretestutil/core.go
Labels: enhancement, C: Celestia app

#621 feat: add path generation for nmt subroots
  pkg/inclusion/paths.go
  pkg/inclusion/paths_test.go
Labels: C: Celestia app

#657 QGB ADR-005 Reducing QGB module state usage
  docs/architecture/ADR-005-QGB_reduce_state_usage.md
Labels: documentation, enhancement, C: QGB

#680 feat: implement non-interactive defaults logic
  pkg/shares/non_interactive_defaults.go
  pkg/shares/non_interactive_defaults_test.go
Labels: C: Celestia app

#690 chore: move malleated transaction decoder to the encoding package
  app/app.go
  app/encoding/malleated_tx_decoder.go
  app/process_proposal.go
  app/test/prepare_proposal_test.go
Labels: C: Celestia app

#681 feat: finish msg inclusion api
  pkg/inclusion/get_commit.go
  pkg/inclusion/nmt_caching.go
  pkg/inclusion/nmt_caching_test.go
  pkg/inclusion/paths.go
  pkg/inclusion/paths_test.go
  pkg/shares/non_interactive_defaults_test.go
Labels: C: Celestia app

#697 chore: remove sims
  .github/workflows/release-sims.yml
  .github/workflows/sims.yml
  Makefile
  contrib/devtools/Makefile
  contrib/devtools/sims.mk
Labels: T: chore

#702 chore(pkg)!: move the prove package from core -> app
  pkg/prove/proof.go
  pkg/prove/proof_test.go
Labels: C: Celestia app

#706 chore(pkg)!: move da package from core -> app
  app/prepare_proposal.go
  app/process_proposal.go
  app/test/process_proposal_test.go
  app/test/split_shares_test.go
  go.mod
  go.sum
  pkg/da/data_availability_header.go
  pkg/da/data_availability_header_test.go
  pkg/inclusion/get_commit.go
  pkg/inclusion/nmt_caching.go
  pkg/inclusion/nmt_caching_test.go
  proto/da/data_availability_header.pb.go
  proto/da/data_availability_header.proto
Labels: C: Celestia app

#707 chore(pkg)!: move wrapper package from core -> app
  pkg/inclusion/nmt_caching.go
  pkg/inclusion/nmt_caching_test.go
  pkg/prove/proof.go
  pkg/wrapper/nmt_wrapper.go
  pkg/wrapper/nmt_wrapper_test.go
  x/payment/types/payfordata.go
Labels: C: Celestia app

#705 Use `squareSize` instead of `k` or `origSquareSize`
  pkg/inclusion/get_commit.go
  pkg/inclusion/paths.go
  pkg/prove/proof.go
  pkg/shares/non_interactive_defaults.go
  pkg/shares/share_merging.go
  x/payment/types/payfordata.go
  x/payment/types/payfordata_test.go
  x/payment/types/square_sizes.go
  x/payment/types/wirepayfordata.go
Labels: T: chore

#704 Rename `contiguous` => `compact` and `message` => `sparse`
  app/split_shares.go
  docs/architecture/ADR-001-ABCI++.md
  pkg/prove/proof_test.go
  pkg/shares/compact_shares_test.go
  pkg/shares/non_interactive_defaults.go
  pkg/shares/parse_compact_shares.go
  pkg/shares/parse_sparse_shares.go
  pkg/shares/share_merging.go
  pkg/shares/share_splitting.go
  pkg/shares/shares_test.go
  pkg/shares/sparse_shares_test.go
  pkg/shares/split_compact_shares.go
  pkg/shares/split_sparse_shares.go
Labels: T: chore

#708 feat: Implement and install new ABCI Query for transaction inclusion proofs
  app/app.go
  app/split_shares.go
  app/test/block_size_test.go
  go.mod
  go.sum
  pkg/da/data_availability_header.go
  pkg/prove/proof.go
  pkg/prove/proof_test.go
  pkg/prove/querier.go
  pkg/shares/compact_shares_test.go
  pkg/shares/shares_test.go
  pkg/shares/split_compact_shares.go
  pkg/shares/split_sparse_shares.go
Labels: C: Celestia app

#715 test: add test to build random blocks and check if they're valid
  app/test/fuzz_abci_test.go
  testutil/payment/testutil.go
Labels: testing

#716 docs: improve doc comments
  pkg/prove/proof.go
  pkg/shares/compact_shares_test.go
  pkg/shares/parse_compact_shares.go
  pkg/shares/parse_sparse_shares.go
  pkg/shares/shares.go
  pkg/shares/sparse_shares_test.go
  pkg/shares/split_compact_shares.go
  x/payment/types/payfordata_test.go
Labels: documentation

#720 Remove valset/data commitment confirm logic from state machine
  go.mod
  go.sum
  proto/qgb/query.proto
  x/qgb/client/cli/datacommitment.go
  x/qgb/client/cli/txcommand.go
  x/qgb/client/cli/valsetconfirm.go
  x/qgb/client/main/main.go
  x/qgb/handler.go
  x/qgb/handler_test.go
  x/qgb/keeper/keeper.go
  x/qgb/keeper/keeper_data_commitment_confirm.go
  x/qgb/keeper/keeper_test.go
  x/qgb/keeper/keeper_valset_confirm.go
  x/qgb/keeper/msg_server.go
  x/qgb/keeper/query_data_commitment_confirm.go
  x/qgb/keeper/query_data_commitment_confirm_test.go
  x/qgb/keeper/query_valset_confirm.go
  x/qgb/keeper/query_valset_confirm_test.go
  x/qgb/module.go
  x/qgb/types/data_commitment_confirm.go
  x/qgb/types/data_commitment_confirm_test.go
  x/qgb/types/errors.go
  x/qgb/types/ethereum_signer.go
  x/qgb/types/ethereum_signer_test.go
  x/qgb/types/events.go
  x/qgb/types/keys.go
  x/qgb/types/query.pb.go
  x/qgb/types/query.pb.gw.go
  x/qgb/types/valset_confirm.go
Labels: C: QGB

#740 Bump cosmos-sdk to v1.3.0-sdk-v0.46.0
  go.mod
  go.sum
Labels: enhancement, consensus breaking

#749 QGB Update valset and data commitment confirm ADRs to link to ADR-005
  docs/architecture/ADR-002-QGB-ValSet.md
  docs/architecture/ADR-003-QGB-DataCommitment.md
Labels: documentation, C: QGB

#746 QGB Feedback on PR #742
  docs/architecture/ADR-002-QGB-ValSet.md
  docs/architecture/ADR-003-QGB-DataCommitment.md
  go.mod
  go.sum
  proto/qgb/query.proto
  testutil/common.go
  x/qgb/abci_test.go
  x/qgb/keeper/hooks.go
  x/qgb/keeper/keeper_attestation.go
  x/qgb/keeper/keeper_data_commitment.go
  x/qgb/keeper/keeper_valset.go
  x/qgb/keeper/query_valset.go
  x/qgb/types/genesis.go
  x/qgb/types/query.pb.go
  x/qgb/types/valset.go
Labels: C: QGB

#748 Qgb universal nonces ADR update
  docs/architecture/ADR-004-QGB_relayer_security.md
Labels: documentation, C: QGB

#753 QGB nits + docs for the merge 2
  docs/architecture/ADR-002-QGB-ValSet.md
  proto/qgb/query.proto
  x/qgb/abci.go
  x/qgb/keeper/keeper_attestation.go
  x/qgb/types/keys.go
Labels: enhancement, C: QGB

#747 feat(ProcessProposal)!: Check for message inclusion using subtree roots
  app/process_proposal.go
  app/test/block_size_test.go
  pkg/inclusion/nmt_caching.go
  pkg/inclusion/nmt_caching_test.go
  pkg/prove/proof.go
  pkg/shares/utils.go
  pkg/shares/utils_test.go
  x/payment/types/payfordata.go
  x/payment/types/payfordata_test.go
Labels: C: Celestia app, consensus breaking

#757 fix: regenerate proto files
  x/payment/types/tx.pb.gw.go
  x/qgb/types/msgs.pb.gw.go
  x/qgb/types/query.pb.gw.go
Labels: C: QGB

#762 fix: Update Dockerfiles and fix CI
  Dockerfile
  docker/Dockerfile_ephemeral
Labels: bug, CI

#764 fix: update export code to work with v0.46.0
  app/export.go
Labels: bug, C: Celestia app

#767 chore: Go mod tidy on QGB branch
  go.mod
Labels: C: QGB

#742 Merge QGB feature branch into main
  .gitignore
  Makefile
  app/app.go
  docs/architecture/ADR-002-QGB-ValSet.md
  docs/architecture/ADR-003-QGB-DataCommitment.md
  docs/architecture/ADR-004-QGB_relayer_security.md
  docs/architecture/ADR-005-QGB_reduce_state_usage.md
  go.mod
  go.sum
  proto/qgb/genesis.proto
  proto/qgb/msgs.proto
  proto/qgb/query.proto
  proto/qgb/types.proto
  scripts/protocgen.sh
  scripts/single-node.sh
  testutil/common.go
  testutil/test_app.go
  x/payment/types/builder.go
  x/qgb/abci.go
  x/qgb/abci_test.go
  x/qgb/client/cli/datacommitment.go
  x/qgb/client/cli/valsetconfirm.go
  x/qgb/genesis.go
  x/qgb/handler.go
  x/qgb/keeper/hooks.go
  x/qgb/keeper/keeper.go
  x/qgb/keeper/keeper_attestation.go
  x/qgb/keeper/keeper_data_commitment.go
  x/qgb/keeper/keeper_valset.go
  x/qgb/keeper/keeper_valset_test.go
  x/qgb/keeper/msg_server.go
  x/qgb/keeper/query_attestation.go
  x/qgb/keeper/query_general.go
  x/qgb/keeper/query_valset.go
  x/qgb/module.go
  x/qgb/types/abi_consts.go
  x/qgb/types/attestation.go
  x/qgb/types/codec.go
  x/qgb/types/data_commitment.go
  x/qgb/types/data_commitment_confirm.go
  x/qgb/types/datacommitmentconfirm.go
  x/qgb/types/errors.go
  x/qgb/types/events.go
  x/qgb/types/genesis.go
  x/qgb/types/genesis.pb.go
  x/qgb/types/genesis_test.go
  x/qgb/types/keys.go
  x/qgb/types/msgs.pb.go
  x/qgb/types/msgs.pb.gw.go
  x/qgb/types/query.pb.go
  x/qgb/types/query.pb.gw.go
  x/qgb/types/types.go
  x/qgb/types/types.pb.go
  x/qgb/types/types_test.go
  x/qgb/types/validator.go
  x/qgb/types/valset.go
  x/qgb/types/valset_confirm.go
  x/qgb/types/valsetconfirm.go
Labels: enhancement, C: Celestia app, C: QGB, apphash breaking

#778 fix: compact share `Count`
  app/estimate_square_size.go
  pkg/shares/split_compact_shares.go
  pkg/shares/split_compact_shares_test.go
Labels: bug, T: chore

#774 chore!: rename `k` to `square_size`
  proto/payment/tx.proto
  x/payment/types/payfordata_test.go
  x/payment/types/tx.pb.go
  x/payment/types/verify_sigs.go
  x/payment/types/wirepayfordata.go
  x/payment/types/wirepayfordata_test.go
Labels: C: Celestia app

#776 chore: move `MarshalDelimited*` functions
  pkg/shares/shares.go
  pkg/shares/split_compact_shares.go
  pkg/shares/split_sparse_shares.go
Labels: T: chore

#775 chore!: rename `message_name_space_id` to `message_namespace_id`
  app/estimate_square_size.go
  app/parse_txs.go
  proto/payment/tx.proto
  x/payment/spec/docs.md
  x/payment/types/payfordata_test.go
  x/payment/types/tx.pb.go
  x/payment/types/wirepayfordata.go
  x/payment/types/wirepayfordata_test.go
Labels: C: Celestia app

#788 fix: update default `timeout_commit` when running `sed` on genesis in `single-node.sh` script
  scripts/single-node.sh
Labels: bug

#790 fix: move the eth private key comment in single-node.sh to correct place
  scripts/single-node.sh
Labels: bug

#794 Fix markdown lint workflow to actually run on subdirectories properly
  .github/workflows/markdown-lint.yml
Labels: CI

#793 Initial specs migration.
  .github/workflows/gh-pages.yml
  specs/.gitignore
  specs/README.md
  specs/book.toml
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/rationale/index.md
  specs/src/rationale/message_block_layout.md
  specs/src/specs/block_proposer.md
  specs/src/specs/consensus.md
  specs/src/specs/data_structures.md
  specs/src/specs/figures/block_data_structures.dot
  specs/src/specs/figures/block_data_structures.svg
  specs/src/specs/figures/data_root.svg
  specs/src/specs/figures/rs2d.svg
  specs/src/specs/figures/rs2d_extend.svg
  specs/src/specs/figures/rs2d_extending.svg
  specs/src/specs/figures/rs2d_originaldata_message.svg
  specs/src/specs/figures/rs2d_originaldata_reserved.svg
  specs/src/specs/figures/rs2d_quadrants.svg
  specs/src/specs/figures/rs2d_row.svg
  specs/src/specs/figures/share.dot
  specs/src/specs/figures/share.svg
  specs/src/specs/index.md
  specs/src/specs/networking.md
  specs/src/specs/proto/consensus.proto
  specs/src/specs/proto/types.proto
  specs/src/specs/proto/wire.proto
  specs/theme/highlight.js
Labels: specs

#798 Fix markdown lint errors.
  specs/src/specs/data_structures.md
Labels: specs

#797 Add deploy step to mdbook workflow.
  .github/workflows/gh-pages.yml
Labels: CI, specs

#799 Run table formatter.
  specs/src/specs/data_structures.md
  specs/src/specs/networking.md
Labels: specs

#801 chore: prefer appconsts for # of reserved bytes
  pkg/shares/split_compact_shares.go
Labels: enhancement

#804 feat: introduce `FirstCompactShareContentSize`
  pkg/appconsts/appconsts.go
Labels: C: Celestia app

#724 docs: README for shares package
  pkg/shares/README.md
  pkg/shares/doc.go
Labels: documentation

#810 feat: return `bytesOfPadding`
  pkg/shares/parse_sparse_shares.go
  pkg/shares/shares_test.go
  pkg/shares/split_compact_shares.go
  pkg/shares/split_sparse_shares.go
Labels: C: Celestia app

#811 chore: move `zeroPadIfNecessary` to utils
  pkg/shares/parse_sparse_shares.go
  pkg/shares/shares_test.go
  pkg/shares/utils.go
  pkg/shares/utils_test.go
Labels: T: chore

#805 Rename `InfoReservedByte` to `InfoByte`
  pkg/shares/compact_shares_test.go
  pkg/shares/info_byte.go
  pkg/shares/info_byte_test.go
  pkg/shares/parse_compact_shares.go
  pkg/shares/parse_sparse_shares.go
  pkg/shares/sparse_shares_test.go
  pkg/shares/split_compact_shares.go
  pkg/shares/split_sparse_shares.go
Labels: C: Celestia app

#813 test: transaction splitting
  pkg/shares/share_splitting_test.go
Labels: testing

#814 chore: rename txLen to unitLen
  pkg/shares/parse_compact_shares.go
Labels: C: Celestia app, low priority

#812 chore: specs-staging CODEOWNERS
  .github/CODEOWNERS
Labels: T: chore

#815 chore: kebab-case ADR filenames
  docs/architecture/adr-002-qgb-valset.md
  docs/architecture/adr-003-qgb-data-commitments.md
  docs/architecture/adr-004-qgb-relayer-security.md
  docs/architecture/adr-005-qgb-reduce-state-usage.md
Labels: T: chore

#781 feat: write data length to first compact share
  pkg/prove/proof.go
  pkg/prove/proof_test.go
  pkg/shares/compact_shares_test.go
  pkg/shares/parse_compact_shares.go
  pkg/shares/share_splitting_test.go
  pkg/shares/split_compact_shares.go
Labels: C: Celestia app, consensus breaking

#822 chore!: remove `NamespacedShares`
  app/prepare_proposal.go
  app/process_proposal.go
  pkg/prove/proof.go
  pkg/prove/proof_test.go
  pkg/shares/compact_shares_test.go
  pkg/shares/share_splitting.go
  pkg/shares/share_splitting_test.go
  pkg/shares/shares.go
  pkg/shares/shares_test.go
  pkg/shares/sparse_shares_test.go
  pkg/shares/split_compact_shares.go
  pkg/shares/split_sparse_shares.go
  x/payment/types/payfordata.go
Labels: C: Celestia app
