Repository celestiaorg/celestia-app, pull requests merged in 2022-10, with the labels that each got.

#673 ADR 006: Non-interactive Defaults, Wrapped Txs, and Subtree Root Message Inclusion Checks
  docs/architecture/adr-006-non-interactive-defaults.md
  docs/architecture/assets/after.png
  docs/architecture/assets/before.png
  docs/architecture/assets/example-full-block.png
  docs/architecture/assets/extra-message-that-doesnt-fit.png
  docs/architecture/assets/fit-extra-msg-byremoving-tx.png
  docs/architecture/assets/multi-row-str.png
  docs/architecture/assets/multirow.png
  docs/architecture/assets/subtree-root.png
Labels: documentation, discussion

#824 feat: Implement an in-process test core node with celestia-app and custom state
  cmd/celestia-appd/cmd/root.go
  pkg/inclusion/nmt_caching_test.go
  testutil/coretestutil/core.go
  testutil/testnode/full_node.go
  testutil/testnode/full_node_test.go
  testutil/testnode/node_init.go
  testutil/testnode/node_interaction_api.go
  testutil/testnode/rpc_client.go
  testutil/utils.go
Labels: C: Celestia app, testing

#828 feat: new `ParseShare` API
  pkg/shares/share_merging.go
  pkg/shares/share_merging_test.go
  pkg/shares/shares.go
Labels: C: Celestia app, share encoding

#837 feat: throw error when parsing unsupported share version
  pkg/appconsts/appconsts.go
  pkg/shares/compact_shares_test.go
  pkg/shares/parse_compact_shares.go
  pkg/shares/parse_sparse_shares.go
  pkg/shares/share_merging.go
  pkg/shares/sparse_shares_test.go
Labels: C: Celestia app, share encoding

#841 chore: move `ParseDelimiter`
  pkg/shares/compact_shares_test.go
  pkg/shares/parse_sparse_shares.go
  pkg/shares/utils.go
  pkg/shares/utils_test.go
Labels: T: chore

#844 Remove doc comment on SparseShare vs CompactShare
  pkg/appconsts/appconsts.go
Labels: documentation, T: chore

#838 Remove duplicated random valid namespace
  app/estimate_square_size_test.go
  app/test/block_size_test.go
  app/test_util.go
  pkg/namespace/random_ns_generator.go
  pkg/prove/proof_test.go
  testutil/payment/testutil.go
  testutil/testnode/full_node_test.go
  testutil/utils.go
Labels: hacktoberfest-accepted

#849 Update qgb orchestrator relayer to main
  .github/CODEOWNERS
  .github/workflows/markdown-lint.yml
  .github/workflows/test.yml
  app/estimate_square_size.go
  app/export.go
  app/prepare_proposal.go
  app/process_proposal.go
  cmd/celestia-appd/cmd/root.go
  docs/architecture/adr-002-qgb-valset.md
  docs/architecture/adr-003-qgb-data-commitments.md
  docs/architecture/adr-004-qgb-relayer-security.md
  docs/architecture/adr-005-qgb-reduce-state-usage.md
  docs/architecture/adr-006-non-interactive-defaults.md
  docs/architecture/assets/after.png
  docs/architecture/assets/before.png
  docs/architecture/assets/example-full-block.png
  docs/architecture/assets/extra-message-that-doesnt-fit.png
  docs/architecture/assets/fit-extra-msg-byremoving-tx.png
  docs/architecture/assets/multi-row-str.png
  docs/architecture/assets/multirow.png
  docs/architecture/assets/subtree-root.png
  pkg/appconsts/appconsts.go
  pkg/inclusion/nmt_caching_test.go
  pkg/inclusion/paths.go
  pkg/prove/proof.go
  pkg/prove/proof_test.go
  pkg/shares/README.md
  pkg/shares/compact_shares_test.go
  pkg/shares/doc.go
  pkg/shares/info_byte.go
  pkg/shares/info_byte_test.go
  pkg/shares/parse_compact_shares.go
  pkg/shares/parse_sparse_shares.go
  pkg/shares/share_splitting.go
  pkg/shares/share_splitting_test.go
  pkg/shares/shares.go
  pkg/shares/shares_test.go
  pkg/shares/sparse_shares_test.go
  pkg/shares/split_compact_shares.go
  pkg/shares/split_compact_shares_test.go
  pkg/shares/split_sparse_shares.go
  pkg/shares/utils.go
  pkg/shares/utils_test.go
  scripts/single-node.sh
  testutil/coretestutil/core.go
  testutil/testnode/full_node.go
  testutil/testnode/full_node_test.go
  testutil/testnode/node_init.go
  testutil/testnode/node_interaction_api.go
  testutil/testnode/rpc_client.go
  testutil/utils.go
  x/payment/keeper/keeper.go
  x/payment/types/payfordata.go
  x/payment/types/payfordata_test.go
  x/payment/types/square_sizes.go
  x/qgb/orchestrator/confirms.go
  x/qgb/orchestrator/ethereum_signature.go
  x/qgb/orchestrator/querier.go
  x/qgb/orchestrator/test/test_utils.go
Labels: C: QGB

#846 chore: move namespace pkg under testutil directory
  app/estimate_square_size_test.go
  app/test/block_size_test.go
  app/test_util.go
  pkg/prove/proof_test.go
  testutil/namespace/random_ns_generator.go
  testutil/payment/testutil.go
  testutil/testnode/full_node_test.go
Labels: T: chore

#851 fix: remove debug printf statement
  pkg/prove/proof.go
Labels: bug, T: chore

#852 chore: remove Makefile `PACKAGES`
  Makefile
Labels: T: chore

#855 chore: extract manySmallTxsWithoutRandomness
  pkg/prove/proof_test.go
  pkg/prove/proof_testdata.go
Labels: T: chore

#854 chore: remove redundant check
  x/payment/types/wirepayfordata.go
Labels: T: chore

#853 fix: FitsInSquare for case with 0 messages
  pkg/shares/non_interactive_defaults.go
  pkg/shares/non_interactive_defaults_test.go
Labels: bug

#864 chore: rename data length to sequence length
  docs/architecture/adr-007-universal-share-prefix.md
  pkg/appconsts/appconsts.go
  pkg/prove/proof_test.go
  pkg/shares/parse_compact_shares.go
  pkg/shares/shares.go
  pkg/shares/split_compact_shares.go
Labels: T: chore

#866 feat!: implement `FillSquare` method for the testnode
  testutil/testnode/full_node.go
  testutil/testnode/full_node_test.go
  testutil/testnode/node_interaction_api.go
Labels: testing

#863 Add a package-specific documentation section
  README.md
Labels: documentation

#872 fix: ParseShares failed to append last sequence
  pkg/shares/share_merging.go
  pkg/shares/share_merging_test.go
Labels: C: Celestia app

#859 chore!: rename `TIA` to `CLS`
  README.md
  app/app.go
  app/test/block_size_test.go
  scripts/single-node.sh
  testutil/test_app.go
  x/payment/types/builder_options.go
  x/payment/types/payfordata_test.go
Labels: C: Celestia app, breaking

#857 feat: Add store, indexer, extractor and loader to QGB
  x/qgb/orchestrator/confirm_store.go
  x/qgb/orchestrator/indexer.go
  x/qgb/orchestrator/loader.go
Labels: enhancement, C: QGB

#874 docs: update code block in ADR-006
  .markdownlint.yaml
  docs/architecture/adr-006-non-interactive-defaults.md
  x/payment/spec/docs.md
Labels: documentation

#865 feat: throw error if incorrect sequenceLength
  pkg/shares/compact_shares_test.go
  pkg/shares/info_byte.go
  pkg/shares/info_byte_test.go
  pkg/shares/parse_compact_shares.go
  pkg/shares/parse_sparse_shares.go
  pkg/shares/share_merging.go
  pkg/shares/share_merging_test.go
  pkg/shares/shares.go
  pkg/shares/sparse_shares_test.go
  pkg/shares/split_sparse_shares.go
Labels: C: Celestia app

#850 feat!: increase share size to 512 bytes
  app/estimate_square_size_test.go
  app/test/block_size_test.go
  pkg/appconsts/appconsts.go
  pkg/da/data_availability_header_test.go
  pkg/prove/proof_test.go
  pkg/shares/reserved_bytes.go
  pkg/shares/reserved_bytes_test.go
  pkg/shares/share_splitting_test.go
  pkg/shares/split_compact_shares.go
  testutil/testnode/full_node.go
  testutil/testnode/full_node_test.go
  x/payment/types/payfordata_test.go
  x/payment/types/square_sizes_test.go
  x/payment/types/wirepayfordata_test.go
Labels: C: Celestia app

#881 create a new docker image on release branch
  .github/workflows/docker-build.yml
Labels: github_actions, CI

#882 Remove branch release from docker build CI
  .github/workflows/docker-build.yml
Labels: github_actions, CI

#806 docs: describe message length varint
  specs/src/specs/data_structures.md
Labels: documentation, specs

#875 shares: extract powers of two
  app/estimate_square_size.go
  go.mod
  go.sum
  pkg/shares/non_interactive_defaults.go
  pkg/shares/powers_of_two.go
  pkg/shares/powers_of_two_test.go
  x/payment/types/payfordata.go
  x/payment/types/payfordata_test.go
  x/payment/types/wirepayfordata.go
Labels: T: chore

#898 fix: link to gnu-sed in single-node script
  scripts/single-node.sh
Labels: bug

#899 docs: remove devnet code block
  README.md
Labels: documentation

#901 docs: delete all contents of `~/.celestia-app`
  README.md
Labels: documentation

#903 fix: markdown lint links
  README.md
  docs/architecture/adr-002-qgb-valset.md
  docs/architecture/adr-003-qgb-data-commitments.md
  docs/architecture/adr-005-qgb-reduce-state-usage.md
Labels: bug

#905 test: three additional test cases for FitsInSquare
  pkg/shares/non_interactive_defaults_test.go
Labels: testing

#909 chore: rename `height` to `treeSizes` in Merkle mountain range
  x/payment/types/payfordata.go
  x/payment/types/payfordata_test.go
Labels: T: chore

#922 chore: Rename eth to evm
  go.mod
  go.sum
  proto/qgb/msgs.proto
  proto/qgb/types.proto
  testutil/common.go
  testutil/testnode/node_init.go
  x/qgb/abci.go
  x/qgb/keeper/keeper.go
  x/qgb/keeper/keeper_valset.go
  x/qgb/keeper/keeper_valset_test.go
  x/qgb/types/abi_consts.go
  x/qgb/types/data_commitment_confirm.go
  x/qgb/types/errors.go
  x/qgb/types/genesis.go
  x/qgb/types/msgs.pb.go
  x/qgb/types/types.pb.go
  x/qgb/types/types_test.go
  x/qgb/types/validator.go
  x/qgb/types/valset.go
  x/qgb/types/valset_confirm.go
Labels: C: QGB

#926 chore: update to rsmt2d v0.7.0
  go.mod
  go.sum
  pkg/da/data_availability_header.go
  pkg/inclusion/nmt_caching.go
  pkg/inclusion/nmt_caching_test.go
  pkg/prove/proof.go
  pkg/wrapper/nmt_wrapper.go
  pkg/wrapper/nmt_wrapper_test.go
Labels: C: Celestia app, consensus breaking

#856 specs: universal share prefix
  specs/src/specs/consensus.md
  specs/src/specs/data_structures.md
  specs/src/specs/figures/compact_continuation_share.dot
  specs/src/specs/figures/compact_continuation_share.svg
  specs/src/specs/figures/compact_start_share.dot
  specs/src/specs/figures/compact_start_share.svg
  specs/src/specs/figures/share.dot
  specs/src/specs/figures/share.svg
  specs/src/specs/figures/sparse_continuation_share.dot
  specs/src/specs/figures/sparse_continuation_share.svg
  specs/src/specs/figures/sparse_start_share.dot
  specs/src/specs/figures/sparse_start_share.svg
Labels: specs

#921 chore: move `TestProcessWirePayForData`
  x/payment/types/payfordata_test.go
  x/payment/types/wirepayfordata_test.go
Labels: T: chore
