Repository celestiaorg/celestia-app, pull requests merged in 2022-08, with the labels that each got.

#583 ci: enable markdownlint
  .github/workflows/markdown-lint.yml
  .markdownlint.yaml
  contrib/githooks/README.md
  docs/architecture/ADR-001-ABCI++.md
  x/payment/spec/docs.md
Labels: CI

#586 chore: add v0.7.x, v0.8.x, and v0.9.x to mergify
  .github/mergify.yml
Labels: C: Celestia app, CI, S:backport-to-v0.7.x

#593 adds `.idea` to gitignore
  .gitignore
Labels: enhancement, S:backport-to-v0.7.x

#472 update to sdk v0.46.0 and downgrade tendermint to v0.34.20
  app/app.go
  app/test/block_size_test.go
  go.mod
  go.sum
  testutil/network/network.go
  testutil/test_app.go
  x/payment/types/payfordata_test.go
  x/payment/types/wirepayfordata_test.go
Labels: dependencies, C: Celestia app, apphash breaking

#602 Update QGB implementation to support cosmos-sdk v0.46.x
  .github/workflows/test.yml
  app/app.go
  cmd/celestia-appd/cmd/root.go
  contrib/single-node.sh
  docs/architecture/ADR-002-QGB-ValSet.md
  docs/architecture/ADR-003-QGB-DataCommitment.md
  docs/architecture/ADR-004-QGB_relayer_security.md
  e2e/qgb/README.md
  e2e/qgb/Service.go
  e2e/qgb/celestia-app/config.toml
  e2e/qgb/celestia-app/core0/account-address-core0.txt
  e2e/qgb/celestia-app/core0/config/gentx/gentx-59b5a0fcecba7f44d5a0a52a0506ff8da45e23a2.json
  e2e/qgb/celestia-app/core0/config/gentx/gentx-79042c6ca62f2890f5604a22ec8505f14510cb71.json
  e2e/qgb/celestia-app/core0/config/node_key.json
  e2e/qgb/celestia-app/core0/config/priv_validator_key.json
  e2e/qgb/celestia-app/core0/keyring-test/core0.info
  e2e/qgb/celestia-app/core0/keyring-test/f080579c09ecaaee2c4e175599c1d82e2636ef31.address
  e2e/qgb/celestia-app/core0/keyring-test/f90a245c294d9de463b5502c0dc7aedb942eaf1a.address
  e2e/qgb/celestia-app/core1/account-address-core1.txt
  e2e/qgb/celestia-app/core1/keyring-test/2bf1b5857a5922bf615fe19414bba6d2d4b2d9af.address
  e2e/qgb/celestia-app/core1/keyring-test/86bd3d199b87c84949f9e962f60c575e20b21fbc.address
  e2e/qgb/celestia-app/core1/keyring-test/core1.info
  e2e/qgb/celestia-app/core2/account-address-core2.txt
  e2e/qgb/celestia-app/core2/keyring-test/9e0c3c9d2bfa6f7bbb716a23c5cac221a0cb4102.address
  e2e/qgb/celestia-app/core2/keyring-test/core2.info
  e2e/qgb/celestia-app/core2/keyring-test/fd09583928be1223e66957d58f27311ebf3ed47d.address
  e2e/qgb/celestia-app/core3/account-address-core3.txt
  e2e/qgb/celestia-app/core3/keyring-test/0373a90792119530ad8d94a821746cd390f5dbe1.address
  e2e/qgb/celestia-app/core3/keyring-test/7c8956db8dbe031b29d19f0a8a4e8f1cc1b4b132.address
  e2e/qgb/celestia-app/core3/keyring-test/core3.info
  e2e/qgb/celestia-app/genesis.json
  e2e/qgb/docker-compose.yml
  e2e/qgb/qgb_network.go
  e2e/qgb/scripts/deploy_qgb_contract.sh
  e2e/qgb/scripts/start_node_and_create_validator.sh
  e2e/qgb/scripts/start_orchestrator_after_validator_created.sh
  go.mod
  go.sum
  testutil/common.go
  testutil/test_app.go
  x/qgb/abci_test.go
  x/qgb/handler_test.go
  x/qgb/keeper/hooks.go
  x/qgb/keeper/keeper.go
  x/qgb/keeper/keeper_valset.go
  x/qgb/keeper/msg_server.go
  x/qgb/orchestrator/codec.go
  x/qgb/orchestrator/deploy_command.go
  x/qgb/orchestrator/evm_client.go
  x/qgb/orchestrator/orchestrator.go
  x/qgb/orchestrator/orchestrator_command.go
  x/qgb/orchestrator/querier.go
  x/qgb/orchestrator/relayer.go
  x/qgb/orchestrator/relayer_command.go
  x/qgb/orchestrator/test/common_test.go
  x/qgb/orchestrator/test/test_utils.go
  x/qgb/types/abi_consts.go
  x/qgb/types/validator.go
Labels: C: QGB

#548 Remove cosmos/keyring
  go.mod
  go.sum
Labels: dependencies, T: chore

#615 ci: enable exportloopref
  .golangci.yml
Labels: CI

#618 fix: use wrapped nmt when generating commitments
  go.mod
  x/payment/types/payfordata.go
  x/payment/types/payfordata_test.go
Labels: C: Celestia app

#605 QGB Use Ecrecover to validate Ethereum signatures
  x/qgb/types/ethereum_signer.go
  x/qgb/types/ethereum_signer_test.go
Labels: bug, C: QGB

#625 chore: move scripts from contrib to scripts/
  .gitignore
  Makefile
  docker/Dockerfile.test
  scripts/localnet-blocks-test.sh
  scripts/single-node.sh
  scripts/test_cover.sh
Labels: T: chore

#622 QGB depend on latest version of core and use begin/end block instead of query for commitments
  go.mod
  go.sum
  x/qgb/orchestrator/orchestrator.go
  x/qgb/orchestrator/querier.go
  x/qgb/orchestrator/test/mock_querier.go
  x/qgb/orchestrator/test/test_utils.go
Labels: bug, C: QGB

#627 chore: move share encoding logic from core -> app
  app/process_proposal.go
  app/split_shares.go
  app/test/process_proposal_test.go
  app/test/split_shares_test.go
  pkg/shares/share_merging.go
  pkg/shares/share_splitting.go
  pkg/shares/shares.go
  pkg/shares/shares_test.go
  x/payment/types/payfordata.go
Labels: C: Celestia app

#629 relaying 2/3 signatures correctly
  x/qgb/orchestrator/relayer.go
Labels: bug, C: QGB

#634 fix: remove test-build
  Makefile
Labels: bug, T: chore

#614 Extract helper to logInvalidPropBlock
  app/process_proposal.go
Labels: T:enhancement

#645 QGB state machine remove confirm valset check
  x/qgb/handler_test.go
  x/qgb/keeper/msg_server.go
Labels: enhancement, C: QGB

#649 Clarify naming of NextHighestPowerOf2
  app/prepare_proposal.go
  x/payment/types/payfordata.go
  x/payment/types/payfordata_test.go
Labels: T: chore

#646 QGB state machine remove invalid validator set check
  x/qgb/keeper/msg_server.go
Labels: bug, C: QGB

#661 docs: add diagram
  README.md
Labels: documentation

#662 Remove PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: T: chore

#665 chore: remove redundant checks
  x/payment/types/payfordata.go
Labels: T: chore

#654 Ensure that `MsgWirePayForData` and `MsgPayForData` contain at least one MessageShareCommitment
  x/payment/types/errors.go
  x/payment/types/payfordata.go
  x/payment/types/payfordata_test.go
  x/payment/types/wirepayfordata.go
  x/payment/types/wirepayfordata_test.go
Labels: C: Celestia app

#637 chore: refactor share splitting and merging
  app/child_tx_decoder.go
  app/process_proposal.go
  app/split_shares.go
  app/test/process_proposal_test.go
  app/test/split_shares_test.go
  go.mod
  go.sum
  pkg/appconsts/appconsts.go
  pkg/shares/contiguous_shares_test.go
  pkg/shares/message_shares_test.go
  pkg/shares/parse_contiguous_shares.go
  pkg/shares/parse_message_shares.go
  pkg/shares/share_merging.go
  pkg/shares/share_splitting.go
  pkg/shares/shares.go
  pkg/shares/shares_test.go
  pkg/shares/split_contiguous_shares.go
  pkg/shares/split_message_shares.go
  pkg/shares/utils.go
  x/payment/types/builder_test.go
  x/payment/types/payfordata.go
Labels: C: Celestia app

#675 Delete precommit
  contrib/githooks/precommit
Labels: T: chore

#671 Implement InfoReservedByte
  pkg/appconsts/appconsts.go
  pkg/shares/info_reserved_byte.go
  pkg/shares/info_reserved_byte_test.go
Labels: C: Celestia app

#613 QGB Relayer add commitments check when relaying confirms
  x/qgb/orchestrator/errors.go
  x/qgb/orchestrator/querier.go
Labels: C: QGB

#666 Validate all relevant square sizes are committed to in `MsgWirePayForData`
  app/process_proposal.go
  app/split_shares.go
  app/test/prepare_proposal_test.go
  app/test/process_proposal_test.go
  app/test/split_shares_test.go
  pkg/shares/parse_message_shares.go
  x/payment/types/errors.go
  x/payment/types/payfordata_test.go
  x/payment/types/wirepayfordata.go
  x/payment/types/wirepayfordata_test.go
Labels: C: Celestia app, apphash breaking, consensus breaking
