Repository celestiaorg/celestia-app, pull requests merged in 2022-12, with the labels that each got.

#1090 chore: add docs to create commitment explaining the double namespace
  x/blob/types/payforblob.go
Labels: documentation

#1099 chore: cherry pick default changes
  cmd/celestia-appd/cmd/root.go
Labels: C: Celestia app

#1109 fix!: Share splitting bug v0.11.0
  app/test/fuzz_abci_test.go
  pkg/shares/share_splitting.go
Labels: bug, consensus breaking

#1089 feat!: use `BlobTx` instead of `MsgWirePayForBlob`
  app/app.go
  app/check_tx.go
  app/encoding/malleated_tx_decoder.go
  app/estimate_square_size.go
  app/estimate_square_size_test.go
  app/malleate_txs.go
  app/parse_txs.go
  app/prepare_proposal.go
  app/process_proposal.go
  app/test/block_size_test.go
  app/test/check_tx_test.go
  app/test/fuzz_abci_test.go
  app/test/prepare_proposal_test.go
  app/test/process_proposal_test.go
  app/test_util.go
  app/testutil_test.go
  app/write_square.go
  app/write_square_test.go
  go.mod
  go.sum
  pkg/shares/share_splitting.go
  proto/blob/genesis.proto
  proto/blob/params.proto
  proto/blob/query.proto
  proto/blob/tx.proto
  testutil/blobfactory/payforblob_factory.go
  testutil/blobfactory/test_util.go
  testutil/test_app.go
  testutil/testfactory/utils.go
  testutil/testnode/full_node.go
  testutil/testnode/full_node_test.go
  testutil/testnode/node_init.go
  testutil/testnode/node_interaction_api.go
  testutil/utils.go
  x/blob/README.md
  x/blob/client/cli/wirepayfordata.go
  x/blob/payforblob.go
  x/blob/types/blob_tx.go
  x/blob/types/blob_tx_test.go
  x/blob/types/builder.go
  x/blob/types/builder_test.go
  x/blob/types/codec.go
  x/blob/types/errors.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
  x/blob/types/test/blob_tx_test.go
  x/blob/types/tx.pb.go
  x/blob/types/verify_sigs.go
  x/blob/types/wirepayforblob.go
  x/blob/types/wirepayfordata_test.go
Labels: ABCI, consensus breaking, api breaking, x/blob

#1040 ADR 011 - Optimistic Blob Size Independent Inclusion Proofs and PFB Fraud Proofs
  docs/architecture/adr-011-optimistic-blob-size-independent-inclusion-proofs-and-pfb-fraud-proofs.md
  docs/architecture/assets/blob-merkle-proof.png
  docs/architecture/assets/optimized-pfb-proofs.png
  docs/architecture/assets/pfb-proof-size-result.png
  docs/architecture/assets/pfd-merkle-proof.png
Labels: ADR

#1111 fix!: Share splitting bug
  app/test/fuzz_abci_test.go
  pkg/shares/share_splitting.go
  pkg/shares/shares_test.go
Labels: bug, consensus breaking

#1143 test: sequence start indicator tampering
  app/test/process_proposal_test.go
Labels: testing
