Repository celestiaorg/celestia-app, pull requests merged in 2023-07, with the labels that each got.

#2002 docs: namespace specs
  pkg/namespace/README.md
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/specs/consensus.md
  specs/src/specs/data_structures.md
  specs/src/specs/figures/namespace.dot
  specs/src/specs/figures/namespace.svg
  specs/src/specs/index.md
  specs/src/specs/namespace.md
  specs/src/specs/shares.md
  x/blob/README.md
Labels: specs

#2005 chore: enable stylecheck
  .golangci.yml
  app/test/integration_test.go
  app/test/process_proposal_test.go
  app/validate_txs.go
  pkg/shares/share_sequence_test.go
  pkg/shares/split_compact_shares_test.go
  pkg/square/builder_test.go
  pkg/square/square_test.go
  pkg/wrapper/nmt_wrapper_test.go
  test/txsim/run.go
  test/txsim/send.go
  test/txsim/sequence.go
  test/util/blobfactory/payforblob_factory.go
  test/util/blobfactory/test_util.go
  test/util/testnode/config.go
  test/util/testnode/node_interaction_api.go
  x/blob/client/testutil/integration_test.go
  x/blob/types/blob_tx_test.go
  x/blob/types/builder.go
  x/blob/types/payforblob.go
  x/blob/types/test/blob_tx_test.go
  x/mint/keeper/genesis.go
  x/qgb/client/query.go
  x/qgb/types/genesis.go
Labels: chore

#2012 fix!: use max square size worst case padding when constructing the square in all cases
  app/extend_block.go
  app/test/integration_test.go
  pkg/proof/proof.go
  pkg/square/builder.go
  pkg/square/builder_test.go
  pkg/square/square.go
  pkg/square/square_fuzz_test.go
  pkg/square/square_test.go
Labels: bug, consensus breaking, api breaking

#2022 fix!: use correct chain-id when filtering and checking txs
  app/prepare_proposal.go
  app/process_proposal.go
  app/test/fuzz_abci_test.go
  app/test/prepare_proposal_test.go
  app/test/process_proposal_test.go
  go.mod
  go.sum
  pkg/shares/parse_sparse_shares_test.go
  test/util/testfactory/blob.go
Labels: bug

#2028 fix: prepare/process proposal consistency test
  app/test/fuzz_abci_test.go
  test/util/direct_tx_gen.go
Labels: bug, testing

#2036 docs: describe conventional commits
  README.md
Labels: documentation

#1966 docs: add block validity rules specs
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/specs/block_validity_rules.md
  specs/src/specs/data_square_layout.md
  specs/src/specs/fraud_proofs.md
Labels: specs

#2056 test: fix flaky TestPrepareProposalConsistency
  app/test/fuzz_abci_test.go
Labels: testing

#2035 fix: stop overwriting chain-id in testnode
  test/util/testnode/full_node.go
Labels: external

#2057 chore: docker common pipeline v0.2.1
  .github/workflows/docker-build-publish.yml
Labels: bug, CI, docker

#2065 chore: markdown-link-check ignore bitcointalk.org
  specs/src/specs/data_structures.md
Labels: external

#2043 refactor: use `SecondsPerYear`
  x/mint/types/constants.go
Labels: external

#1974 docs: add the QGB overview document
  x/qgb/overview.md
Labels: documentation, x/qgb

#2062 chore!: bump to rsmt2d v0.10.0
  app/prepare_proposal.go
  app/process_proposal.go
  app/test/integration_test.go
  app/test/process_proposal_test.go
  go.mod
  go.sum
  pkg/da/data_availability_header.go
  pkg/da/data_availability_header_test.go
  pkg/inclusion/nmt_caching_test.go
  pkg/proof/proof.go
  pkg/proof/proof_test.go
  pkg/square/square_fuzz_test.go
  pkg/square/square_test.go
Labels: api breaking

#2082 docs: link to valset creation in overview
  x/qgb/overview.md
Labels: documentation, x/qgb

#2086 chore: update common pipeline to v0.2.2
  .github/workflows/docker-build-publish.yml
Labels: external

#2094 fix: links to modules in specs
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/specs/state_machine_modules.md
Labels: external

#2095 feat: SquareSize helper for dah
  pkg/da/data_availability_header.go
  pkg/da/data_availability_header_test.go
Labels: enhancement

#2051 test: coverage report to exclude test/util and to not run race detection
  Makefile
  scripts/test_cover.sh
Labels: testing

#2103 chore: always enable API in local dev scripts
  scripts/build-run-single-node.sh
  scripts/single-node.sh
Labels: chore

#2113 refactor: calculate namespace before loop
  x/blob/types/payforblob.go
Labels: refactor

#2099 feat: add blocktime tool
  tools/blocktime/main.go
  tools/blocktime/readme.md
Labels: enhancement

#2014 fix(Makefile)!: add ledger build flag to build with ledger support by default
  Dockerfile
  Makefile
Labels: bug

#2121 fix: explicit int64 for NanosecondsPerYear
  x/mint/test/mint_test.go
  x/mint/types/constants.go
  x/mint/types/minter_test.go
Labels: bug

#2102 fix: single node script (#929)
  scripts/single-node.sh
Labels: x/qgb

#2124 doc: revises the namespace specifications and includes some clarifications
  specs/src/specs/data_structures.md
  specs/src/specs/fraud_proofs.md
  specs/src/specs/namespace.md
  tools/blocktime/readme.md
Labels: namespace audit

#2137 doc: clarifies the exact range of reserved namespaces
  specs/src/specs/namespace.md
Labels: namespace audit

#2140 chore: fixes mutability of the Repeat output
  pkg/namespace/namespace.go
  pkg/namespace/namespace_test.go
Labels: namespace audit

#2133 feat: add detection logic for gas price errors
  app/errors/errors.go
  app/errors/errors_test.go
Labels: enhancement

#2141 test: adds missing unittest for leftPad
  pkg/namespace/namespace.go
  pkg/namespace/namespace_test.go
Labels: namespace audit

#2151 doc: fix incorrect usage of `MaxBytes`
  docs/architecture/adr-021-restricted-block-size.md
Labels: documentation

#2052 feat: make a txsim binary build from Makefile and dockerfile
  .github/workflows/docker-build-publish.yml
  Makefile
  docker/Dockerfile_txsim
  docker/README.md
  docker/txsim.sh
Labels: external

#2154 chore: delete Dockerfile_ephemeral
  docker/Dockerfile_ephemeral
Labels: chore

#2163 fix: stop running the malicious integration test during short mode
  test/util/malicious/app_test.go
Labels: CI

#2164 fix: enable node grpc service in tests
  test/util/testnode/rpc_client.go
Labels: bug

#2162 fix: pass all the app config arguments to the app constructor
  cmd/celestia-appd/cmd/root.go
  test/util/testnode/full_node.go
  x/upgrade/test/integration_test.go
Labels: bug

#2171 chore: update pfb namespace size description
  x/blob/client/cli/payforblob.go
Labels: chore

#2132 docs: resource pricing specs
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/specs/figures/gas_consumption/100kib_pfb_trace.png
  specs/src/specs/figures/gas_consumption/msg_create_validator_trace.png
  specs/src/specs/figures/gas_consumption/msg_send_trace.png
  specs/src/specs/figures/gas_consumption/pfb_with_two_single_share_blobs_trace.png
  specs/src/specs/figures/gas_consumption/single_share_pfb_trace.png
  specs/src/specs/resource_pricing.md
Labels: specs

#2165 refactor!: remove builder return param from init
  pkg/shares/padding.go
  pkg/shares/share_builder.go
  pkg/shares/share_builder_test.go
  pkg/shares/split_compact_shares.go
  pkg/shares/split_sparse_shares.go
Labels: refactor

#2145 refactor!: un-export `namespace.ValidateBlobNamespace`
  pkg/namespace/consts.go
  pkg/namespace/namespace.go
  pkg/namespace/random_blob.go
  x/blob/types/blob_tx.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
Labels: refactor

#2183 chore(deps): bump core version to v1.26.0-tm-v0.34.28
  go.mod
  go.sum
Labels: dependencies

#2190 fix: Use commit sha when there is no RC or tag available
  Makefile
Labels: external
