Repository celestiaorg/celestia-app, pull requests merged in 2023-11, with the labels that each got.

#2798 chore: remove unnecessary abs operation from power diff
  x/blobstream/types/validator.go
Labels: x/blobstream

#2799 refactor(x/blobstream): remove unnecessary code
  x/blobstream/abci.go
Labels: external

#2825 feat(cmd): snapshots command
  cmd/celestia-appd/cmd/root.go
Labels: backport:v1.x

#2826 chore: include calculated and proposed data root in log message
  app/process_proposal.go
Labels: backport:v1.x

#2838 fix: register gRPC Gateway routes
  x/blob/module.go
  x/blobstream/module.go
Labels: external, backport:v1.x

#2853 test: generateShares(2 * 2)
  pkg/da/data_availability_header_test.go
Labels: external
