Repository celestiaorg/celestia-app, pull requests merged in 2023-09, with the labels that each got.

#2385 docs: add block validity rules specs (backport #1966)
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/specs/block_validity_rules.md
  specs/src/specs/data_square_layout.md
  specs/src/specs/fraud_proofs.md
Labels: documentation, specs

#2401 fix(txsim): resolves discrepancies between suggested and implemented flags
  test/cmd/txsim/cli.go
  test/txsim/run.go
  test/txsim/sequence.go
Labels: cli

#2402 chore: remove `GetMaccPerms`
  app/app.go
Labels: external, cleanup

#2416 docs: add default params to the spec
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/specs/params.md
Labels: specs, param, backport:v1.x

#2403 feat(cli): add experimental-compact-goleveldb
  cmd/celestia-appd/cmd/root.go
Labels: enhancement, backport:v1.x

#2411 feat: improve PayForBlobs CLI
  x/blob/client/cli/payforblob.go
Labels: enhancement

#2430 docs: fix typo in environment variable name
  README.md
Labels: documentation

#2431 chore: default home directory for `single-node.sh`
  scripts/single-node.sh
Labels: chore

#2447 docs: backport the overview document
  x/qgb/overview.md
Labels: documentation, x/qgb

#2449 Makefile: simpily ledger build tags
  Makefile
  README.md
  specs/src/SUMMARY.md
Labels: external

#2448 Makefile: fix formatting error on help printout
  Makefile
Labels: external

#2437 build: Goreleaser
  .github/workflows/ci-release.yml
  .goreleaser.yaml
  Makefile
  README.md
Labels: CI, external

#2446 fix: check for equal expected size in square size test
  app/test/square_size_test.go
Labels: bug, testing, backport:v1.x

#2450 typo(ci): upload word typo
  .github/workflows/test.yml
Labels: documentation

#2468 chore: bump docker ci to v0.2.3
  .github/workflows/docker-build-publish.yml
Labels: CI, external

#2406 docs(x/mint): explain `TargetInflationRate`
  x/mint/types/constants.go
Labels: x/mint, backport:v1.x

#2460 chore(deps): bump the QGB contracts version
  go.mod
  go.sum
  x/qgb/client/verify.go
  x/qgb/types/abi_consts.go
Labels: dependencies, backport:v1.x

#2467 fix(scripts): single node celestia app home fix
  scripts/single-node.sh
Labels: bug, backport:v1.x

#2408 refactor(x/mint): error if current before previous
  x/mint/abci.go
  x/mint/types/minter.go
  x/mint/types/minter_test.go
Labels: x/mint

#2417 chore: update more default parameters
  app/app.go
  app/default_overrides.go
  app/default_overrides_test.go
  pkg/appconsts/consensus_consts.go
  specs/src/specs/params.md
Labels: param, backport:v1.x

#2407 refactor(x/mint): initialize inflation decimals once
  x/mint/types/constants.go
  x/mint/types/minter.go
  x/mint/types/minter_test.go
Labels: x/mint, backport:v1.x

#1562 docs: ADR 018 Network Upgrades
  docs/architecture/adr-018-network-upgrades.md
Labels: ADR

#2492 docs: consistent format for percentages in params.md
  specs/src/specs/params.md
Labels: documentation, specs, backport:v1.x

#2524 feat: add query qgb evm address by valoper address command
  x/qgb/client/query.go
  x/qgb/types/errors.go
Labels: x/qgb, cli, backport:v1.x

#2477 docs: add Informal Systems audit PDF
  README.md
  audit/informal-systems.pdf
Labels: documentation, audit, backport:v1.x

#2515 fix: add time to the sdk.Context used in PrepareProposal
  Makefile
  app/prepare_proposal.go
  app/test/fuzz_abci_test.go
  app/test/prepare_proposal_context_test.go
  app/test/prepare_proposal_test.go
  app/test/process_proposal_test.go
  go.mod
  go.sum
Labels: bug, backport:v1.x

#2518 chore: log filtered transactions and fix gas limits in tests
  app/prepare_proposal.go
  app/test/fuzz_abci_test.go
  app/validate_txs.go
  test/util/malicious/out_of_order_prepare.go
Labels: bug, backport:v1.x, introspection

#2537 chore: remove unnecessary go mod tidy
  Makefile
Labels: chore, backport:v1.x, cleanup

#2541 chore(deps): Bump go version to 1.21.1
  .github/workflows/ci-release.yml
  .github/workflows/lint.yml
  .github/workflows/nightly.yml
  .github/workflows/test.yml
  README.md
  go.mod
Labels: dependencies, backport:v1.x

#2544 chore(deps): Bump QGB contracts version to v2
  go.mod
  go.sum
  x/qgb/client/verify.go
  x/qgb/types/abi_consts.go
  x/qgb/types/valset.go
Labels: dependencies, x/qgb, backport:v1.x

#2546 refactor: fork the markdown linter from .github and use our own config
  .github/markdown-link-check-config.json
  .github/workflows/lint.yml
  .github/workflows/markdown-linter.yml
Labels: CI, refactor

#2547 chore(deps): bump golang-ci version to support go 1.21
  .github/workflows/lint.yml
Labels: dependencies, backport:v1.x

#2532 chore: increase duration of `VotingPeriod` and `MaxDepositPeriod`
  app/default_overrides.go
  app/default_overrides_test.go
  specs/src/specs/params.md
Labels: defaults, x/gov, backport:v1.x

#2540 chore: use builtin min function
  x/blob/ante/max_total_blob_size_ante.go
Labels: chore, backport:v1.x

#2556 ci: run markdown-linter on ci-release
  .github/workflows/ci-release.yml
  .github/workflows/lint.yml
  .github/workflows/markdown-linter.yml
Labels: CI, backport:v1.x

#2554 docs: add one more mint param to params.md
  specs/src/specs/params.md
  x/mint/README.md
  x/mint/types/constants.go
Labels: documentation, specs, backport:v1.x

#2560 feat: add metrics to prepare and process proposal
  app/prepare_proposal.go
  app/process_proposal.go
  app/validate_txs.go
Labels: backport:v1.x

#2559 feat: add decorator to wrap panic messages with the transaction that caused them
  app/ante/ante.go
  app/ante/panic.go
  app/ante/panic_test.go
Labels: backport:v1.x

#2581 chore: bump celestia-core to v1.28.0-tm-v0.34.29
  go.mod
  go.sum
Labels: dependencies, backport:v1.x

#2574 feat!: disable ibc upgrade proposal handler
  app/app.go
  app/ibc_proposal_handler.go
  x/upgrade/test/integration_test.go
Labels: backport:v1.x

#2585 deps: bump ics23 from v0.9.0 to v0.9.1
  go.mod
  go.sum
Labels: backport:v1.x

#2589 chore: bump our fork of the sdk to v1.18.1-sdk-v0.46.14
  go.mod
  go.sum
Labels: dependencies, backport:v1.x

#2593 fix: dead link
  docs/architecture/adr-019-strict-inflation-schedule.md
  specs/src/specs/ante_handler.md
  specs/src/specs/data_structures.md
  specs/src/specs/public_key_cryptography.md
  specs/src/specs/resource_pricing.md
  x/blob/types/payforblob.go
  x/qgb/overview.md
  x/upgrade/README.md
Labels: CI, backport:v1.x, fix
