Repository celestiaorg/celestia-app, pull requests merged in 2023-10, with the labels that each got.

#2598 chore(deps): bump qgb contracts version to v2.1.2
  go.mod
  go.sum
Labels: x/qgb, backport:v1.x

#2599 fix: register qgb msg server in codec
  x/qgb/types/codec.go
Labels: x/qgb, backport:v1.x

#2604 chore: use a permalink for rollkit ADR
  docs/architecture/adr-008-square-size-independent-message-commitments.md
Labels: CI, backport:v1.x

#2602 chore: bump celestia-core to v1.29.0-tm-v0.34.29
  go.mod
  go.sum
Labels: dependencies

#2621 chore: backport dep bumps from main to v1.x
  go.mod
  go.sum
Labels: chore

#2584 chore: move audit under docs directory
  README.md
  docs/audit/informal-systems.pdf
Labels: backport:v1.x

#2627 chore: reduce VotingPeriod to 1 week
  app/default_overrides.go
  app/default_overrides_test.go
  specs/src/specs/params.md
Labels: chore, backport:v1.x

#2568 feat: sign pre-built binary with GPG key
  .github/workflows/ci-release.yml
  .goreleaser.yaml
  README.md
  scripts/signing/celestia-app-maintainers.asc
  scripts/signing/verify-signature.sh
Labels: enhancement, backport:v1.x

#2637 docs: update the specs links
  pkg/wrapper/README.md
Labels: documentation, backport:v1.x

#2455 refactor!: genesis creation into its own package
  app/test/block_production_test.go
  app/test/integration_test.go
  app/test/max_total_blob_size_test.go
  app/test/prepare_proposal_context_test.go
  app/test/priority_test.go
  app/test/qgb_rpc_test.go
  app/test/square_size_test.go
  app/test/std_sdk_test.go
  pkg/user/signer_test.go
  test/cmd/txsim/cli_test.go
  test/e2e/setup.go
  test/e2e/simple_test.go
  test/e2e/testnet.go
  test/txsim/run_test.go
  test/util/genesis/accounts.go
  test/util/genesis/document.go
  test/util/genesis/files.go
  test/util/genesis/genesis.go
  test/util/genesis/modifier.go
  test/util/genesis/util.go
  test/util/malicious/app_test.go
  test/util/test_app.go
  test/util/testnode/config.go
  test/util/testnode/full_node.go
  test/util/testnode/full_node_test.go
  test/util/testnode/node_init.go
  x/qgb/integration_test.go
  x/upgrade/test/integration_test.go
Labels: testing, api breaking, refactor

#2606 CI: Create codeql.yml
  .github/workflows/codeql.yml
Labels: CI

#2626 fix: specs for `MaxDepositPeriod`
  specs/src/specs/params.md
Labels: specs, backport:v1.x

#2646 fix: LatestAttestationNonce constant name typo
  x/qgb/keeper/keeper_attestation.go
  x/qgb/types/keys.go
Labels: typo, backport:v1.x

#2631 chore: increase `MinDeposit` from 1K to 10K TIA
  app/default_overrides.go
  app/default_overrides_test.go
  specs/src/specs/params.md
Labels: external, backport:v1.x

#2645 fix: build manually the app binary for codeql
  .github/workflows/codeql.yml
Labels: CI

#2630 chore: decrease `SlashFractionDoubleSign` to 2%
  app/default_overrides.go
  specs/src/specs/params.md
Labels: external, backport:v1.x

#2652 ci: check if goreleaser config is valid
  .github/workflows/ci-release.yml
Labels: CI

#2668 fix: signing with ledger throws an empty error
  go.mod
  go.sum
Labels: bug, backport:v1.x

#2677 ci: PRs titles must have a conventional commit prefix
  .github/workflows/lint-pull-request.yml
Labels: CI

#2651 docs: remove reference to specs-staging
  docs/architecture/adr-014-versioned-namespaces.md
Labels: documentation, ADR

#2681 chore: update deafult mempool size to match ttl and block size
  app/default_overrides.go
Labels: backport:v1.x

#2712 chore: fix blobstream link
  x/blobstream/overview.md
Labels: chore

#2709 chore(deps): replace old qgb contracts repo with blobstream repo
  go.mod
  go.sum
  x/blobstream/client/verify.go
  x/blobstream/types/abi_consts.go
  x/blobstream/types/valset.go
Labels: dependencies, backport:v1.x, x/blobstream

#2717 fix: override proposer rewards to 0%
  app/app.go
  app/default_overrides.go
  app/default_overrides_test.go
Labels: defaults, backport:v1.x

#2725 chore: fix multiplatform builds
  Dockerfile
  docker/Dockerfile_txsim
Labels: external

#2724 feat: query earliest attestation nonce
  app/test/qgb_rpc_test.go
  proto/celestia/qgb/v1/query.proto
  x/blobstream/keeper/query_general.go
  x/blobstream/types/query.pb.go
  x/blobstream/types/query.pb.gw.go
Labels: backport:v1.x, x/blobstream

#2719 feat(blobstream): utilizes sdk.Dec type for power difference calculation
  x/blobstream/abci.go
  x/blobstream/types/types_test.go
  x/blobstream/types/validator.go
Labels: backport:v1.x

#2740 fix: restore Ledger support for MacOS 14
  go.mod
  go.sum
Labels: backport:v1.x

#2723 fix(malicious): use constructor NMT options
  test/util/malicious/tree.go
Labels: testing, backport:v1.x, fix

#2623 feat: command to convert `peers.txt` into `addrbook.json`
  cmd/celestia-appd/cmd/addrbook.go
  cmd/celestia-appd/cmd/root.go
Labels: enhancement

#2736 chore: update the default description for tia
  app/default_overrides.go
Labels: backport:v1.x

#2728 fix: pre-built binary support for Ubuntu 20.04
  .github/workflows/ci-release.yml
Labels: backport:v1.x

#2714 docs: update adr18 on new upgrade mechanism
  docs/architecture/adr-018-network-upgrades.md
Labels: documentation, ADR

#2754 docs: Binary Builders audit PDF
  README.md
  docs/audit/binary-builders.pdf
Labels: documentation

#2763 docs: fix broken links to docs.celestia.org
  tools/blocktime/readme.md
  x/blob/README.md
Labels: documentation

#2760 docs: fix spelling of compatibility
  docs/architecture/adr-015-namespace-id-size.md
  specs/src/specs/cat_pool.md
Labels: external

#2764 chore: discard abci responses by default
  app/default_overrides.go
Labels: backport:v1.x

#2761 chore: disable API, GRPC, and GRPC web by default
  app/default_overrides.go
  app/default_overrides_test.go
  scripts/single-node.sh
Labels: backport:v1.x

#2772 ci: add goreleaser-check as a require step for the goreleaser build
  .github/workflows/ci-release.yml
Labels: external

#2770 refactor!: move all blob share commitment code to the inclusion package
  pkg/da/data_availability_header.go
  pkg/inclusion/blob_share_commitment_rules.go
  pkg/inclusion/blob_share_commitment_rules_test.go
  pkg/inclusion/commitment.go
  pkg/inclusion/commitment_test.go
  pkg/inclusion/paths.go
  pkg/square/builder.go
  pkg/square/square.go
  test/util/malicious/out_of_order_builder.go
  x/blob/types/blob_tx.go
  x/blob/types/blob_tx_test.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
Labels: api breaking, refactor

#2773 ci: add release_branches to version_bump to fix tag names
  .github/workflows/ci-release.yml
Labels: external

#2776 docs: fix typos and link error
  specs/src/specs/block_validity_rules.md
  specs/src/specs/cat_pool.md
  specs/src/specs/data_square_layout.md
  specs/src/specs/params.md
  specs/src/specs/resource_pricing.md
  x/blob/README.md
Labels: external

#2782 test: Ledger support
  test/ledger/ledger_test.go
Labels: testing

#2791 feat: `download-genesis` command
  cmd/celestia-appd/cmd/download-genesis.go
  cmd/celestia-appd/cmd/root.go
Labels: backport:v1.x
