Repository celestiaorg/celestia-app, pull requests merged in 2023-03, with the labels that each got.

#1382 docs: ADR 14 Versioned Namespaces
  docs/architecture/adr-014-versioned-namespaces.md
  docs/architecture/assets/first-sparse-share.svg
Labels: ADR

#1431 chores: QGB keepers specific errors
  go.mod
  go.sum
  x/qgb/keeper/keeper_data_commitment.go
  x/qgb/keeper/keeper_data_commitment_test.go
  x/qgb/types/errors.go
Labels: x/qgb

#1436 docs: replace evidence with PFBs in square diagram
  specs/src/rationale/message_block_layout.md
  specs/src/specs/consensus.md
  specs/src/specs/data_structures.md
  specs/src/specs/figures/block_data_structures.dot
  specs/src/specs/figures/block_data_structures.svg
  specs/src/specs/figures/rs2d_originaldata_message.svg
  specs/src/specs/figures/rs2d_originaldata_reserved.svg
Labels: specs

#1441 specs: auto generate table of contents
  specs/README.md
  specs/book.toml
  specs/src/rationale/message_block_layout.md
  specs/src/specs/block_proposer.md
  specs/src/specs/consensus.md
  specs/src/specs/data_structures.md
  specs/src/specs/networking.md
Labels: specs

#1405 docs: ADR 15 Namespace ID Size
  docs/architecture/adr-015-namespace-id-size.md
Labels: ADR

#1445 refactor(testutil/testnode): Allow passing chainID to testnode constuctor
  testutil/testnode/full_node.go
Labels: api breaking

#1448 chore: use cosmossdk.io/errors
  app/verify_txs.go
  x/blob/handler.go
  x/blob/types/errors.go
  x/qgb/abci.go
  x/qgb/handler.go
  x/qgb/keeper/keeper_data_commitment.go
  x/qgb/keeper/keeper_valset.go
  x/qgb/types/errors.go
  x/qgb/types/genesis.go
  x/qgb/types/validator.go
  x/qgb/types/valset.go
  x/tokenfilter/ibc_middleware.go
Labels: chore

#1449 feat: add the ability to log directly to a file
  cmd/celestia-appd/cmd/root.go
Labels: enhancement

#1442 chore: adds NMT Wrapper specifications
  docs/spec/nmt-wrapper.md
  pkg/appconsts/appconsts.go
  pkg/wrapper/nmt_wrapper.go
Labels: documentation

#1456 chore: issue label and project automation
  .github/workflows/issue-label-automation.yml
  .github/workflows/project-automation.yml
Labels: chore

#1447 chore: run hadolint and yamllint during `make lint`
  .yamllint.yml
  Makefile
  README.md
Labels: chore

#1467 docs: note about Q3
  specs/src/specs/data_structures.md
Labels: specs

#1481 ci: automate-labels for dependabot PRs
  .github/workflows/issue-label-automation.yml
Labels: external

#1468 chore: Remove usage of deprecated rokroskar/workflow-run-cleanup-action
  .github/workflows/test.yml
Labels: external

#1482 chore: add Sanaz as NMT wrapper code owner
  .github/CODEOWNERS
Labels: chore

#1476 feat(pkg/da): Extract min share creation into separate function for convenience
  pkg/da/data_availability_header.go
Labels: external

#1479 chore: remove packr2
  Makefile
Labels: chore

#796 Spec migration
  .github/CODEOWNERS
  .github/workflows/gh-pages.yml
  specs/.gitignore
  specs/README.md
  specs/book.toml
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/rationale/index.md
  specs/src/rationale/message_block_layout.md
  specs/src/specs/block_proposer.md
  specs/src/specs/consensus.md
  specs/src/specs/data_structures.md
  specs/src/specs/figures/block_data_structures.dot
  specs/src/specs/figures/block_data_structures.svg
  specs/src/specs/figures/compact_continuation_share.dot
  specs/src/specs/figures/compact_continuation_share.svg
  specs/src/specs/figures/compact_start_share.dot
  specs/src/specs/figures/compact_start_share.svg
  specs/src/specs/figures/data_root.svg
  specs/src/specs/figures/rs2d.svg
  specs/src/specs/figures/rs2d_extend.svg
  specs/src/specs/figures/rs2d_extending.svg
  specs/src/specs/figures/rs2d_originaldata_message.svg
  specs/src/specs/figures/rs2d_originaldata_reserved.svg
  specs/src/specs/figures/rs2d_quadrants.svg
  specs/src/specs/figures/rs2d_row.svg
  specs/src/specs/figures/sparse_continuation_share.dot
  specs/src/specs/figures/sparse_continuation_share.svg
  specs/src/specs/figures/sparse_start_share.dot
  specs/src/specs/figures/sparse_start_share.svg
  specs/src/specs/index.md
  specs/src/specs/networking.md
  specs/src/specs/proto/consensus.proto
  specs/src/specs/proto/types.proto
  specs/src/specs/proto/wire.proto
  specs/theme/highlight.js
Labels: specs

#1497 ci: PR preview specs
  .github/workflows/gh-pages.yml
Labels: CI

#1500 ci: deploy main on workflow dispatch
  .github/workflows/gh-pages.yml
Labels: CI

#1502 fix: signal handling for container
  docker/entrypoint.sh
Labels: external

#1510 docs: change LessThen to MoreThen
  docs/architecture/adr-009-non-interactive-default-rules-for-reduced-padding.md
Labels: external

#1508 docs: improve CreateCommitment docs
  x/blob/README.md
Labels: documentation

#1520 docs: rename ADR 13 filename
  docs/architecture/adr-013-non-interactive-default-rules-for-zero-padding.md
Labels: documentation

#1537 chore: upgrade to Go 1.19
  .github/workflows/lint.yml
  .github/workflows/test.yml
  Dockerfile
  Makefile
  README.md
  docker/Dockerfile.test
  docker/Dockerfile_ephemeral
  go.mod
Labels: chore

#1005 docs: ADR 10 Remove `MsgWirePayForBlob`
  docs/architecture/adr-010-remove-wire-msg-pay-for-blob.md
Labels: documentation, ADR

#1550 docs: versioned namespaces specs
  docs/spec/nmt-wrapper.md
  specs/src/specs/consensus.md
  specs/src/specs/data_structures.md
  specs/src/specs/figures/compact_continuation_share.dot
  specs/src/specs/figures/compact_continuation_share.svg
  specs/src/specs/figures/compact_start_share.dot
  specs/src/specs/figures/compact_start_share.svg
  specs/src/specs/figures/sparse_continuation_share.svg
  specs/src/specs/figures/sparse_start_share.dot
  specs/src/specs/figures/sparse_start_share.svg
Labels: specs

#1561 docs: account for namespace version and 32 byte namespace id
  pkg/shares/doc.go
Labels: documentation

#1545 chore: remove unnecessary third party proto files
  buf.lock
  buf.yaml
  proto/buf.gen.gogo.yaml
  proto/celestia/blob/v1/event.proto
  proto/celestia/blob/v1/tx.proto
  third_party/proto/confio/proofs.proto
  third_party/proto/cosmos_proto/cosmos.proto
  third_party/proto/gogoproto/gogo.proto
  third_party/proto/google/api/annotations.proto
  third_party/proto/google/api/http.proto
  third_party/proto/google/api/httpbody.proto
  third_party/proto/google/protobuf/any.proto
  third_party/proto/google/protobuf/descriptor.proto
  third_party/proto/tendermint/abci/types.proto
  third_party/proto/tendermint/crypto/keys.proto
  third_party/proto/tendermint/crypto/proof.proto
  third_party/proto/tendermint/libs/bits/types.proto
  third_party/proto/tendermint/types/evidence.proto
  third_party/proto/tendermint/types/params.proto
  third_party/proto/tendermint/types/types.proto
  third_party/proto/tendermint/types/validator.proto
  third_party/proto/tendermint/version/types.proto
  x/blob/types/event.pb.go
  x/blob/types/genesis.pb.go
  x/blob/types/params.pb.go
  x/blob/types/query.pb.go
  x/blob/types/tx.pb.go
  x/qgb/types/genesis.pb.go
  x/qgb/types/query.pb.go
  x/qgb/types/types.pb.go
Labels: chore

#1563 docs: specs vs package-specific docs
  README.md
  x/blob/README.md
Labels: documentation

#1551 docs: remove `SignedTransaction*` section
  specs/src/specs/data_structures.md
Labels: specs

#1577 chore: upgrade to nmt v0.15.0
  go.mod
  go.sum
  pkg/wrapper/nmt_wrapper.go
  pkg/wrapper/nmt_wrapper_test.go
  x/blob/types/payforblob.go
Labels: chore

#1579 chore: bump NMT to v0.15.0
  go.mod
  go.sum
  pkg/wrapper/nmt_wrapper.go
  pkg/wrapper/nmt_wrapper_test.go
  testutil/testnode/full_node.go
  testutil/testnode/full_node_test.go
  x/blob/types/payforblob.go
Labels: chore

#1580 chore: bump NMT to v0.15.0
  go.mod
  go.sum
  pkg/wrapper/nmt_wrapper.go
  pkg/wrapper/nmt_wrapper_test.go
  x/blob/types/payforblob.go
Labels: chore

#1581 chore: bump NMT to v0.15.0
  go.mod
  go.sum
  pkg/wrapper/nmt_wrapper.go
  pkg/wrapper/nmt_wrapper_test.go
  x/blob/types/payforblob.go
Labels: chore
