Repository celestiaorg/celestia-app, pull requests merged in 2023-06, with the labels that each got.

#1871 fix: update AnnualProvisions once per year
  test/util/test_app.go
  x/mint/abci.go
  x/mint/abci_test.go
  x/mint/types/minter.go
  x/mint/types/minter_test.go
Labels: bug

#1878 chore(deps): bump core version to v1.21.2-tm-v0.34.27
  go.mod
  go.sum
Labels: chore

#1888 chore: remove unnecessary method param
  x/blob/client/cli/query.go
  x/blob/module.go
Labels: chore

#1892 feat: add QGB query attestation CLI command
  x/qgb/client/query.go
  x/qgb/client/query_test.go
  x/qgb/client/suite_test.go
  x/qgb/keeper/query_attestation.go
  x/qgb/module.go
  x/qgb/types/errors.go
Labels: x/qgb

#1846 docs: update the valset normalization docs
  x/qgb/keeper/keeper_valset.go
  x/qgb/types/validator.go
Labels: documentation, x/qgb

#1915 chore: remove unnecessary comment
  test/util/testnode/genesis_options.go
Labels: chore

#1912 chore!: bump sdk and core
  app/prepare_proposal.go
  app/process_proposal.go
  app/square_size.go
  go.mod
  go.sum
Labels: dependencies

#1902 fix: use the right key for `EarliestAvailableAttestationNonce` check method
  x/qgb/keeper/keeper_attestation.go
Labels: x/qgb

#1909 docs: fix the GenesisTime go doc
  test/util/testnode/node_interaction_api.go
Labels: documentation

#1904 refactor: use testnode instead of cosmos-sdk version
  app/test/integration_test.go
Labels: testing

#1924 docs: add a link to the tokenfilter in the spec ToC
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/specs/state_machine_modules.md
Labels: documentation, specs

#1930 fix: add replace for broken goleveldb
  go.mod
  go.sum
  test/util/testnode/full_node.go
Labels: bug

#1929 chore: rename to namespace padding
  pkg/shares/parse_sparse_shares_test.go
  pkg/shares/share_splitting.go
  pkg/shares/split_sparse_shares.go
  pkg/square/builder.go
Labels: chore

#1923 chore!: remove unused fitsInRow return value
  pkg/inclusion/paths.go
  pkg/shares/non_interactive_defaults.go
  pkg/shares/non_interactive_defaults_test.go
  pkg/square/builder.go
Labels: chore, api breaking

#1873 docs: improve x/mint specs
  x/mint/README.md
Labels: documentation, specs

#1895 feat!: remove `useShareIndexes`
  pkg/shares/parse_sparse_shares_test.go
  pkg/shares/parse_test.go
  pkg/shares/share_splitting.go
  pkg/shares/split_sparse_shares_test.go
  x/blob/types/payforblob.go
Labels: enhancement, api breaking

#1880 docs: update shares specs
  .gitignore
  pkg/shares/README.md
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/specs/consensus.md
  specs/src/specs/data_structures.md
  specs/src/specs/figures/share_continuation.dot
  specs/src/specs/figures/share_continuation.svg
  specs/src/specs/figures/share_start.dot
  specs/src/specs/figures/share_start.svg
  specs/src/specs/figures/transaction_share_continuation.dot
  specs/src/specs/figures/transaction_share_continuation.svg
  specs/src/specs/figures/transaction_share_start.dot
  specs/src/specs/figures/transaction_share_start.svg
  specs/src/specs/index.md
  specs/src/specs/shares.md
Labels: documentation, specs

#1949 chore: `make proto-gen`
  x/blob/types/params.pb.go
  x/qgb/types/query.pb.go
Labels: chore

#1950 ci: run make proto-gen on all PRs
  .github/workflows/protobuf.yml
Labels: CI

#1928 chore: remove `RemoveBlob`
  pkg/shares/split_sparse_shares.go
Labels: chore

#1951 docs: fix namespace comment
  proto/celestia/blob/v1/tx.proto
  x/blob/types/tx.pb.go
Labels: documentation

#1906 docs: update the blob module specs part 1
  x/blob/README.md
Labels: specs, x/blob

#1963 test: add latest/earliest available attestation nonce keys tests
  test/util/common.go
  x/qgb/genesis.go
  x/qgb/keeper/keeper_attestation_test.go
  x/qgb/keeper/keeper_data_commitment_test.go
  x/qgb/keeper/keeper_valset_test.go
Labels: x/qgb, testing

#1959 docs: reword adr-013 and describe `SubtreeRootThreshold`
  docs/architecture/adr-013-non-interactive-default-rules-for-zero-padding.md
  pkg/appconsts/versioned_consts.go
  pkg/shares/blob_share_commitment_rules.go
Labels: documentation, ADR

#1911 specs: add QGB specs
  x/qgb/README.md
Labels: x/qgb, specs

#1976 chore: QGB module cosmetics
  proto/celestia/qgb/v1/genesis.proto
  test/util/common.go
  x/qgb/README.md
  x/qgb/keeper/hooks.go
  x/qgb/types/genesis.pb.go
Labels: x/qgb, chore

#1983 fix!: add namespace version check in pfbs
  x/blob/types/errors.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
Labels: bug

#1984 fix!: implement full antehandler checks
  app/prepare_proposal.go
  app/process_proposal.go
  app/test/integration_test.go
  app/test/prepare_proposal_test.go
  app/test/process_proposal_test.go
  app/validate_txs.go
  test/util/testnode/node_interaction_api.go
Labels: bug

#1986 docs: improve x/mint README
  x/mint/README.md
Labels: documentation

#1985 feat!: run min gas pfb decorator in process proposal
  x/blob/ante/ante.go
Labels: consensus breaking

#1851 feat!: remove genesis time from genesis state
  proto/celestia/mint/v1/mint.proto
  test/util/test_app.go
  x/mint/README.md
  x/mint/abci.go
  x/mint/abci_test.go
  x/mint/client/testutil/suite_test.go
  x/mint/keeper/genesis.go
  x/mint/keeper/grpc_query.go
  x/mint/keeper/grpc_query_test.go
  x/mint/keeper/keeper.go
  x/mint/keeper/querier.go
  x/mint/keeper/querier_test.go
  x/mint/simulation/decoder.go
  x/mint/simulation/decoder_test.go
  x/mint/types/keys.go
  x/mint/types/mint.pb.go
  x/mint/types/minter.go
  x/mint/types/minter_test.go
Labels: consensus breaking, x/mint

#1988 feat!: remove genesis time from genesis state (#1851)
  proto/celestia/mint/v1/mint.proto
  test/util/test_app.go
  x/blob/types/params.pb.go
  x/mint/README.md
  x/mint/abci.go
  x/mint/abci_test.go
  x/mint/client/testutil/suite_test.go
  x/mint/keeper/genesis.go
  x/mint/keeper/grpc_query.go
  x/mint/keeper/grpc_query_test.go
  x/mint/keeper/keeper.go
  x/mint/keeper/querier.go
  x/mint/keeper/querier_test.go
  x/mint/simulation/decoder.go
  x/mint/simulation/decoder_test.go
  x/mint/types/keys.go
  x/mint/types/mint.pb.go
  x/mint/types/minter.go
  x/mint/types/minter_test.go
  x/qgb/types/query.pb.go
Labels: consensus breaking

#1996 chore: remove sample-block.json
  pkg/shares/testdata/sample-block.json
Labels: chore

#1975 test: implements deterministic random transaction generation function
  app/test/check_tx_test.go
  app/test/integration_test.go
  app/test/prepare_proposal_test.go
  app/test/process_proposal_test.go
  pkg/namespace/random_blob.go
  pkg/proof/proof_test.go
  pkg/square/builder_test.go
  pkg/square/square_benchmark_test.go
  pkg/square/square_fuzz_test.go
  pkg/square/square_test.go
  test/util/blobfactory/payforblob_factory.go
  test/util/blobfactory/payforblob_factory_test.go
  test/util/blobfactory/test_util.go
  test/util/blobfactory/test_util_test.go
  test/util/direct_tx_gen.go
  x/blob/types/test/blob_tx_test.go
Labels: testing

#1991 chore!: refactor testnode to expose appcreator
  app/test/integration_test.go
  app/test/qgb_rpc_test.go
  app/test/square_size_test.go
  app/test/std_sdk_test.go
  test/cmd/txsim/cli_test.go
  test/txsim/run_test.go
  test/util/testnode/config.go
  test/util/testnode/full_node.go
  test/util/testnode/full_node_test.go
  test/util/testnode/node_interaction_api.go
  x/mint/test/mint_test.go
  x/qgb/client/verify.go
  x/upgrade/test/integration_test.go
Labels: testing

#2001 docs: share version
  specs/src/specs/shares.md
Labels: specs

#2008 feat: add multiple excluded directories to the test coverage script
  scripts/test_cover.sh
Labels: testing, CI

#2006 docs: scripts README
  scripts/README.md
Labels: documentation
