Repository celestiaorg/celestia-app, pull requests merged in 2023-01, with the labels that each got.

#1159 fix!: pass the baseapp msg service router
  app/app.go
Labels: apphash breaking, consensus breaking

#1152 feat: implement non-interactive default rules for reduced padding
  app/write_square.go
  app/write_square_test.go
  pkg/inclusion/paths.go
  pkg/inclusion/paths_test.go
  pkg/shares/non_interactive_defaults.go
  pkg/shares/non_interactive_defaults_test.go
  pkg/shares/share_merging_test.go
  pkg/shares/share_splitting.go
Labels: consensus breaking

#1167 fix: reject txs from the mempool that have a PFB but not a blob
  app/check_tx.go
  app/test/block_size_test.go
  app/test/check_tx_test.go
  testutil/blobfactory/payforblob_factory.go
  testutil/blobfactory/test_util.go
  x/blob/client/cli/wirepayfordata.go
  x/blob/client/testutil/integration_test.go
  x/blob/types/errors.go
Labels: bug

#1160 chore!: Test std modules
  app/test/std_sdk_test.go
  testutil/testnode/sign.go
  x/blob/types/builder.go
Labels: testing, api breaking

#1168 fix!: enforce that blocks with PFBs without a share index get rejected
  app/process_proposal.go
  app/test/process_proposal_test.go
Labels: bug, ABCI, consensus breaking

#1177 chore: improve appconsts godoc
  pkg/appconsts/appconsts.go
Labels: T: chore

#1192 chore: make `test-short`
  Makefile
  app/test/block_size_test.go
  app/test/fuzz_abci_test.go
  testutil/testnode/full_node_test.go
  x/blob/client/testutil/integration_test.go
Labels: enhancement

#1048 Add more QGB abci test cases
  x/qgb/abci_test.go
Labels: x/qgb, testing

#1188 feat: emit namespaceId in PayForBlob event
  proto/blob/event.proto
  x/blob/keeper/keeper.go
  x/blob/types/event.pb.go
  x/blob/types/events.go
Labels: enhancement, x/blob

#1196 feat!: use MultiShareCommitments instead of a single ShareCommitment
  app/process_proposal.go
  pkg/inclusion/get_commit.go
  x/blob/types/blob_tx.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
Labels: consensus breaking, x/blob

#1197 chore!: refactor NewMsgPayForBlob to accept blobs
  app/test/block_size_test.go
  pkg/appconsts/appconsts.go
  testutil/blobfactory/payforblob_factory.go
  testutil/testnode/node_interaction_api.go
  x/blob/client/cli/wirepayfordata.go
  x/blob/payforblob.go
  x/blob/types/blob_tx.go
  x/blob/types/blob_tx_test.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
  x/blob/types/test/blob_tx_test.go
Labels: api breaking, x/blob

#1124 specs: fixed sequence length
  specs/src/specs/consensus.md
  specs/src/specs/data_structures.md
  specs/src/specs/figures/compact_continuation_share.dot
  specs/src/specs/figures/compact_continuation_share.svg
  specs/src/specs/figures/compact_start_share.dot
  specs/src/specs/figures/compact_start_share.svg
  specs/src/specs/figures/sparse_start_share.dot
  specs/src/specs/figures/sparse_start_share.svg
Labels: specs

#1156 specs: non-interactive default rules for reduced padding
  specs/src/rationale/message_block_layout.md
Labels: specs

#1227 chore: refactor `stripCompactShares`
  pkg/prove/proof_test.go
Labels: T: chore

#1217 fix: fix data commitment ranges overlap
  x/qgb/abci_test.go
  x/qgb/keeper/keeper_data_commitment.go
Labels: bug, x/qgb

#1232 chore: bump core to v1.13.0-tm-v0.34.23
  app/estimate_square_size.go
  app/estimate_square_size_test.go
  app/parse_txs.go
  app/process_proposal.go
  go.mod
  go.sum
  pkg/shares/share_splitting.go
  pkg/shares/shares_test.go
  x/blob/types/blob_tx_test.go
Labels: dependencies, consensus breaking

#1235 fix: add size check in RandBlobTxsWithAccounts
  testutil/blobfactory/payforblob_factory.go
Labels: bug

#1210 feat!: Add a default transaction limit
  app/prepare_proposal.go
  app/test/prepare_proposal_test.go
  pkg/appconsts/appconsts.go
  testutil/testfactory/common.go
Labels: bug

#1154 feat!: multiple blobs per PFB
  app/check_tx.go
  app/estimate_square_size.go
  app/estimate_square_size_test.go
  app/parse_txs.go
  app/prepare_proposal.go
  app/process_proposal.go
  app/test/block_size_test.go
  app/test/check_tx_test.go
  app/test/fuzz_abci_test.go
  app/testutil_test.go
  app/write_square.go
  app/write_square_test.go
  pkg/shares/share_splitting.go
  proto/blob/event.proto
  proto/blob/tx.proto
  testutil/blobfactory/payforblob_factory.go
  testutil/namespace/random_ns_generator.go
  testutil/testnode/node_interaction_api.go
  x/blob/client/cli/wirepayfordata.go
  x/blob/keeper/gas_test.go
  x/blob/keeper/keeper.go
  x/blob/payforblob.go
  x/blob/types/blob_tx.go
  x/blob/types/blob_tx_test.go
  x/blob/types/errors.go
  x/blob/types/event.pb.go
  x/blob/types/events.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
  x/blob/types/test/blob_tx_test.go
  x/blob/types/tx.pb.go
Labels: app, apphash breaking, ABCI, consensus breaking, x/blob

#1219 feat! implement token filter IBC middleware
  app/app.go
  x/tokenfilter/ibc_middleware.go
  x/tokenfilter/ibc_middleware_test.go
  x/tokenfilter/keeper.go
Labels: apphash breaking

#1251 fix: add check to `blobCount` in RandBlobTxsWithAccounts
  testutil/blobfactory/payforblob_factory.go
Labels: enhancement

#1248 docs: spec namespaced padding share
  specs/src/specs/data_structures.md
Labels: specs

#1255 fix: stop saving snapshot files to wrong directory during tests
  testutil/testnode/full_node.go
Labels: bug

#1244 docs: spec tail padding share
  specs/src/specs/data_structures.md
Labels: specs

#1228 feat!: write PFB txs to their own namespace
  app/estimate_square_size.go
  app/estimate_square_size_test.go
  app/parse_txs.go
  app/process_proposal.go
  app/test/integration_test.go
  app/testutil_test.go
  pkg/appconsts/appconsts.go
  pkg/prove/proof.go
  pkg/prove/proof_test.go
  pkg/shares/compact_shares_test.go
  pkg/shares/share_merging_test.go
  pkg/shares/share_splitting.go
  pkg/shares/share_splitting_test.go
Labels: consensus breaking, share encoding, api breaking, block validity rule

#1262 chore!: remove `gasLim` param in favor of `TxBuilderOption`
  app/test/integration_test.go
  x/blob/payforblob.go
Labels: T: chore, api breaking

#1264 chore: remove references to "malleated"
  app/app.go
  app/encoding/index_wrapper_decoder.go
  app/test/integration_test.go
  app/test/prepare_proposal_test.go
  x/blob/README.md
  x/blob/client/testutil/integration_test.go
  x/blob/types/builder_test.go
Labels: T: chore

#1266 docs: fix path to x/blob docs
  x/blob/doc.go
Labels: documentation

#1272 docs: update x/blob/README.md
  x/blob/README.md
Labels: documentation

#1261 chore: set the default keyring backend to `test`
  cmd/celestia-appd/cmd/root.go
  go.mod
  go.sum
Labels: T: chore

#1270 chore!: remove ShareCommitAndSignature
  proto/blob/tx.proto
  x/blob/types/tx.pb.go
Labels: T: chore

#1275 revert!: multi share commitment
  app/estimate_square_size_test.go
  app/process_proposal.go
  pkg/inclusion/get_commit.go
  proto/blob/tx.proto
  x/blob/types/blob_tx.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
  x/blob/types/test/blob_tx_test.go
  x/blob/types/tx.pb.go
Labels: api breaking

#1289 chore: rename message to blob in QGB verify command
  x/qgb/client/verify.go
Labels: x/qgb

#1303 feat: Prevent any errors when creating the data folder
  docker/entrypoint.sh
Labels: app, docker, refactor

#1304 chore!: rename MsgPayForBlob to MsgPayForBlobs
  README.md
  app/check_tx.go
  app/prepare_proposal.go
  app/process_proposal.go
  app/write_square.go
  pkg/appconsts/appconsts.go
  pkg/proof/proof.go
  proto/blob/event.proto
  proto/blob/tx.proto
  testutil/blobfactory/payforblob_factory.go
  testutil/testnode/node_interaction_api.go
  x/blob/README.md
  x/blob/client/cli/wirepayforblob.go
  x/blob/handler.go
  x/blob/keeper/gas_test.go
  x/blob/keeper/keeper.go
  x/blob/payforblob.go
  x/blob/types/blob_tx.go
  x/blob/types/blob_tx_test.go
  x/blob/types/builder_test.go
  x/blob/types/codec.go
  x/blob/types/errors.go
  x/blob/types/event.pb.go
  x/blob/types/events.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
  x/blob/types/test/blob_tx_test.go
  x/blob/types/tx.pb.go
  x/blob/types/tx.pb.gw.go
Labels: consensus breaking, api breaking

#1309 chore: update to golangci-lint 1.50.1
  .github/workflows/lint.yml
Labels: T: chore

#1311 feat: add testRandBlob CLI for testground tests
  x/blob/client/cli/payforblob.go
  x/blob/client/cli/testrandblob.go
  x/blob/client/cli/tx.go
  x/blob/client/testutil/integration_test.go
Labels: enhancement, x/blob

#1229 test: add contract interaction verify attestation test
  x/qgb/orchestrator/test/contract_interaction_test.go
Labels: x/qgb, testing

#1287 docs: add QGB verify command docs
  x/qgb/README.md
Labels: documentation, x/qgb
