Repository celestiaorg/celestia-app, pull requests merged in 2023-12, with the labels that each got.

#2872 feat: prebuilt binaries with Ledger support
  .github/workflows/ci-release.yml
  .gitignore
  .goreleaser.yaml
  Makefile
  README.md
  scripts/signing/celestia-app-maintainers.asc
  scripts/signing/verify-signature.sh
Labels: backport:v1.x

#2856 feat: Use file input in payForBlobs CLI to allow to submit multiple blobs
  x/blob/client/cli/payforblob.go
  x/blob/client/cli/util.go
  x/blob/client/testutil/integration_test.go
Labels: external

#2915 test: versioned constant getters
  pkg/appconsts/versioned_consts_test.go
Labels: testing

#2917 ci(goreleaser): set fetch-depth to 0
  .github/workflows/ci-release.yml
Labels: CI

#2920 chore(pkg): typo fix
  pkg/appconsts/global_consts.go
  pkg/wrapper/nmt_wrapper_test.go
Labels: external

#2921 chore: Add vendor to gitignore
  .gitignore
Labels: external

#2926 chore: fix all typos on the repository
  app/ante/ante.go
  app/process_proposal.go
  app/test/fuzz_abci_test.go
  docs/architecture/adr-006-non-interactive-defaults.md
  docs/architecture/adr-012-sequence-length-encoding.md
  docs/architecture/adr-014-versioned-namespaces.md
  docs/architecture/adr-015-namespace-id-size.md
  docs/architecture/adr-018-network-upgrades.md
  docs/architecture/adr-019-strict-inflation-schedule.md
  docs/architecture/adr-020-deterministic-square-construction.md
  pkg/inclusion/nmt_caching.go
  pkg/shares/namespace.go
  pkg/square/builder.go
  pkg/square/square_test.go
  pkg/user/signer.go
  proto/celestia/core/v1/da/data_availability_header.pb.go
  proto/celestia/core/v1/da/data_availability_header.proto
  proto/tendermint/crypto/proof.proto
  scripts/build-run-single-node.sh
  specs/src/specs/block_validity_rules.md
  specs/src/specs/data_structures.md
  specs/src/specs/params.md
  test/testground/README.md
  test/testground/manifest.toml
  test/testground/network/configurators.go
  test/testground/network/consensus_node.go
  test/txsim/send.go
  test/util/malicious/hasher.go
  test/util/malicious/test_app.go
  x/blob/README.md
  x/blob/types/payforblob.go
  x/blobstream/README.md
  x/mint/types/constants.go
Labels: external

#2929 chore(pkg/user): fix typo
  pkg/user/signer.go
Labels: external

#2937 docs: corrections and clarifications
  docs/architecture/adr-020-deterministic-square-construction.md
  pkg/wrapper/README.md
  test/testground/README.md
  x/blobstream/README.md
Labels: external

#2951 fix(testground): updates the app version in testground test
  go.work.sum
  test/testground/go.mod
  test/testground/go.sum
Labels: fix

#2963 feat: SetGasLimitAndFee should round up
  pkg/user/tx_options.go
Labels: backport:v1.x
