Repository celestiaorg/celestia-app, pull requests merged in 2023-04, with the labels that each got.

#1567 chore!: remove min/max square size params
  proto/celestia/blob/v1/params.proto
  x/blob/README.md
  x/blob/keeper/params.go
  x/blob/keeper/params_test.go
  x/blob/types/genesis_test.go
  x/blob/types/params.go
  x/blob/types/params.pb.go
Labels: api breaking

#1595 chore: pin version of `celestiaorg/.github` workflows and actions
  .github/workflows/ci_release.yml
  .github/workflows/docker-build-publish.yml
  .github/workflows/housekeeping.yml
  .github/workflows/lint.yml
Labels: external

#1603 feat: Introduce `--share-version` CLI flag
  app/test/integration_test.go
  testutil/blobfactory/payforblob_factory.go
  testutil/testnode/node_interaction_api.go
  x/blob/client/cli/payforblob.go
  x/blob/client/cli/testrandblob.go
  x/blob/client/testutil/integration_test.go
  x/blob/types/blob_tx.go
  x/blob/types/blob_tx_test.go
  x/blob/types/test/blob_tx_test.go
Labels: external

#1611 chore!: rename `RowsRoots` => `RowRoots`
  pkg/da/data_availability_header.go
  pkg/da/data_availability_header_test.go
  pkg/inclusion/get_commit.go
  pkg/inclusion/nmt_caching.go
  pkg/inclusion/nmt_caching_test.go
Labels: external

#1623 chore: export GenerateRandomBlobOfShareCount
  pkg/shares/sparse_shares_test.go
  testutil/testfactory/blob.go
Labels: chore

#1614 test: ProcessProposal with invalid namespace in index wrapped PFB tx
  app/test/process_proposal_test.go
  testutil/blobfactory/payforblob_factory.go
Labels: testing

#1590 feat!: max namespace version for parity namespace
  pkg/da/data_availability_header_test.go
  pkg/namespace/consts.go
  pkg/namespace/random_namespace.go
  pkg/proof/proof.go
  pkg/shares/compact_shares_test.go
  pkg/shares/parse_sparse_shares_test.go
  pkg/shares/share_builder.go
  pkg/shares/shares.go
  specs/src/specs/consensus.md
  x/blob/README.md
  x/blob/types/errors.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
Labels: api breaking

#1553 docs: public key crypto specs
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/specs/data_structures.md
  specs/src/specs/public_key_cryptography.md
Labels: specs

#1617 docs: rename message to blob in specs
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/rationale/data_square_layout.md
  specs/src/rationale/index.md
  specs/src/rationale/message_block_layout.md
  specs/src/specs/block_proposer.md
  specs/src/specs/consensus.md
  specs/src/specs/data_structures.md
  specs/src/specs/figures/rs2d_originaldata_blob.svg
  specs/src/specs/networking.md
Labels: specs

#1612 chore: explicitly set IgnoreMaxNamespace: true
  pkg/wrapper/nmt_wrapper.go
  pkg/wrapper/nmt_wrapper_test.go
  x/blob/types/payforblob.go
Labels: chore

#1619 chore: remove evidence namespace
  docs/architecture/adr-007-universal-share-prefix.md
  pkg/namespace/consts.go
  specs/src/specs/consensus.md
  x/blob/types/errors.go
  x/blob/types/payforblob_test.go
Labels: chore

#1627 feat!: max namespace version for parity namespace
  pkg/da/data_availability_header_test.go
  pkg/namespace/consts.go
  pkg/namespace/random_namespace.go
  pkg/proof/proof.go
  pkg/shares/compact_shares_test.go
  pkg/shares/parse_sparse_shares_test.go
  pkg/shares/share_builder.go
  pkg/shares/shares.go
  specs/src/specs/consensus.md
  x/blob/README.md
  x/blob/types/errors.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
Labels: api breaking

#1632 chore: address adr-gen feedback
  Makefile
Labels: chore

#1634 refactor(pkg/shares): Add length of share to err message for SequenceLen
  pkg/shares/shares.go
Labels: external

#1585 feat: Introduce `--namespace-version` CLI flag
  x/blob/client/cli/payforblob.go
  x/blob/client/testutil/integration_test.go
Labels: external

#1604 feat!: pack squares densely by implementing ADR013
  app/write_square.go
  app/write_square_test.go
  pkg/appconsts/appconsts.go
  pkg/inclusion/paths.go
  pkg/inclusion/paths_test.go
  pkg/shares/non_interactive_defaults.go
  pkg/shares/non_interactive_defaults_test.go
  pkg/shares/share_splitting.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
  x/qgb/types/query.pb.go
Labels: consensus breaking

#1633 docs: ADR020 Deterministic Square Construction
  docs/architecture/adr-020-deterministic-square-construction.md
Labels: ADR

#1646 Refactor rawDataStartIndex method in share package
  pkg/shares/shares.go
Labels: share encoding, refactor, external

#1644 chore: upgrade to cosmos-sdk v1.10.0-sdk-v0.46.11
  go.mod
  go.sum
Labels: chore

#1629 feat!: remove token voting upgrades
  app/app.go
  app/test/integration_test.go
  app/test/std_sdk_test.go
  test/util/testnode/query.go
  x/upgrade/README.md
  x/upgrade/module.go
  x/upgrade/test/integration_test.go
  x/upgrade/test/removal_test.go
Labels: apphash breaking, x/upgrade

#1653 chore: register blob msg server in module
  x/blob/module.go
Labels: x/blob

#1661 chore!: remove unnecessary constants
  x/blob/client/cli/tx.go
  x/blob/types/payforblob.go
Labels: external

#1640 feat!: Implement the version module
  app/app.go
  app/end_block.go
  cmd/celestia-appd/cmd/root.go
  pkg/wrapper/nmt_wrapper_test.go
  testutil/testnode/full_node.go
  testutil/testnode/full_node_test.go
  x/blob/README.md
  x/version/README.md
  x/version/abci.go
  x/version/chains.go
  x/version/consts.go
  x/version/end_block_test.go
  x/version/keeper.go
  x/version/test/integration_test.go
  x/version/version_height_mapping.go
  x/version/version_height_mapping_test.go
Labels: itn, x/version

#1638 fix: check latest attestation nonce before getting it
  test/util/common.go
  x/qgb/keeper/keeper_attestation.go
  x/qgb/keeper/keeper_data_commitment.go
  x/qgb/keeper/keeper_data_commitment_test.go
  x/qgb/keeper/keeper_valset.go
  x/qgb/keeper/keeper_valset_test.go
  x/qgb/keeper/query_attestation.go
  x/qgb/types/errors.go
Labels: x/qgb

#1666 fix: override TxDecoder
  app/app.go
  app/encoding/encoding.go
  app/encoding/index_wrapper_decoder.go
  cmd/celestia-appd/cmd/root.go
  go.mod
  go.sum
  test/util/testnode/read.go
Labels: bug, app
