Repository celestiaorg/celestia-app, pull requests merged in 2023-08, with the labels that each got.

#2196 chore: remove Dockerfile.test
  docker/Dockerfile.test
Labels: chore

#2187 test: blob sizes that are too large
  app/test/check_tx_test.go
  app/test/integration_test.go
Labels: testing

#2200 docs: clarify that `MaxSquareSize` is a versioned constant
  docs/architecture/adr-021-restricted-block-size.md
Labels: documentation, ADR, external

#2072 chore: audit `x/upgrade` module
  x/upgrade/README.md
  x/upgrade/module.go
  x/upgrade/test/integration_test.go
  x/upgrade/test/removal_test.go
Labels: x/upgrade

#2204 chore: skip data race tests with `-skip` flag
  .github/workflows/test.yml
  Makefile
  x/mint/test/mint_test.go
Labels: chore

#2209 chore(docs): lists should be surrounded by blank lines in md
  specs/src/specs/namespace.md
Labels: documentation, chore

#2208 fix: end exclusive parse namespace end share range
  pkg/proof/proof_test.go
  pkg/proof/querier.go
Labels: bug

#2215 docs: describe need for GetModuleAccount
  x/mint/keeper/genesis.go
Labels: documentation

#1958 test: skip > 10 sec tests in short mode
  test/txsim/run_test.go
  x/mint/client/testutil/suite_test.go
Labels: testing, chore

#2213 test: skip TestMaliciousTestNode in race mode
  Makefile
Labels: testing

#2207 chore: copy across cat pool spec from celestia-core
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/specs/cat_pool.md
  specs/src/specs/index.md
Labels: specs

#2224 chore: remove test cmd from cli
  x/blob/client/cli/payforblob.go
  x/blob/client/cli/testrandblob.go
  x/blob/client/cli/tx.go
Labels: backport:v1.x

#2219 chore: bump the max tx bytes in the mempool config
  app/default_overrides.go
  test/util/testnode/config.go
Labels: backport:v1.x

#2234 fix: packageNaming fix for txsim
  .github/workflows/docker-build-publish.yml
Labels: external

#2230 fix: incorrect byte units in comments
  app/test/integration_test.go
Labels: external

#2220 test: tests tx inclusion in the first block
  app/test/block_production_test.go
  test/util/testnode/config.go
Labels: testing

#2236 Update mergify.yml to fix label
  .github/mergify.yml
Labels: external

#2239 fix: round up when calculating fee in txsim
  test/txsim/account.go
Labels: bug, backport:v1.x

#2242 chore: fixes linter issues by adjusting heading levels in cat_pool.md
  specs/src/specs/cat_pool.md
Labels: chore

#2243 chore(deps): bump core version to v1.26.1-tm-v0.34.28
  go.mod
  go.sum
Labels: dependencies

#2004 test: genesis state tests for vesting accounts
  Makefile
  pkg/genesis/vesting_accounts.go
  pkg/genesis/vesting_accounts_test.go
  test/util/testfactory/utils.go
  test/util/testnode/node_interaction_api.go
  test/util/testnode/sign.go
Labels: testing

#2258 chore!: remove x/mint amino codec
  x/mint/keeper/querier.go
  x/mint/keeper/querier_test.go
  x/mint/module.go
  x/mint/types/codec.go
Labels: x/mint, backport:v1.x

#2257 feat!: reserve the last 256 namespaces for protocol use
  pkg/namespace/consts.go
  pkg/namespace/namespace.go
  pkg/namespace/namespace_test.go
  pkg/shares/padding.go
  pkg/shares/padding_test.go
  pkg/shares/parse_test.go
  pkg/shares/share_sequence_test.go
  pkg/shares/shares.go
  specs/src/specs/namespace.md
  specs/src/specs/shares.md
Labels: consensus breaking, specs, api breaking, backport:v1.x

#2217 feat!: remove Minter from x/mint genesis state
  app/default_overrides.go
  proto/celestia/mint/v1/genesis.proto
  x/mint/keeper/genesis.go
  x/mint/types/genesis.go
  x/mint/types/genesis.pb.go
Labels: api breaking, x/mint, backport:v1.x

#2265 ci: maybe fix issue label automation for mergify
  .github/workflows/issue-label-automation.yml
Labels: bug, CI, backport:v1.x

#2252 fix: TestLegacyGovUpgradeFailure flakiness
  x/upgrade/test/integration_test.go
Labels: testing, chore, flake

#2272 chore(deps): bump core to v1.26.2-tm-v0.34.28
  go.mod
  go.sum
Labels: dependencies, CI

#2279 ci: maybe fix issue label automation
  .github/workflows/issue-label-automation.yml
Labels: CI, backport:v1.x

#2282 ci: fix issue label automation
  .github/workflows/issue-label-automation.yml
Labels: CI, backport:v1.x

#2277 test: skip TestMaxTotalBlobSizeSuite during test-race
  Makefile
Labels: testing

#2285 chore: removes the log info related to the number of txs in mempool when preparing the first block
  app/prepare_proposal.go
Labels: chore

#2288 docs: clarify annual provisions table
  docs/architecture/adr-019-strict-inflation-schedule.md
Labels: documentation, x/mint

#2275 feat: create user package and signer class
  pkg/user/signer.go
  pkg/user/signer_test.go
  pkg/user/tx_options.go
Labels: backport:v1.x

#2292 feat: add the ability to specifiy the txsim master account
  app/test/square_size_test.go
  test/cmd/txsim/cli.go
  test/e2e/simple_test.go
  test/txsim/account.go
  test/txsim/run.go
  test/txsim/run_test.go
Labels: txsim

#2169 feat!: handle registering evm addresses in QGB module
  proto/buf.gen.gogo.yaml
  proto/celestia/mint/v1/mint.proto
  proto/celestia/qgb/v1/tx.proto
  test/util/common.go
  test/util/testfactory/common.go
  x/qgb/abci_test.go
  x/qgb/client/tx.go
  x/qgb/integration_test.go
  x/qgb/keeper/hooks.go
  x/qgb/keeper/keeper.go
  x/qgb/keeper/keeper_valset.go
  x/qgb/keeper/keeper_valset_test.go
  x/qgb/keeper/msg_server.go
  x/qgb/keeper/msg_server_test.go
  x/qgb/module.go
  x/qgb/types/codec.go
  x/qgb/types/errors.go
  x/qgb/types/keys.go
  x/qgb/types/msgs.go
  x/qgb/types/msgs_test.go
  x/qgb/types/query.pb.go
  x/qgb/types/tx.pb.go
  x/qgb/types/tx.pb.gw.go
  x/qgb/types/types.go
  x/qgb/types/validator.go
Labels: x/qgb, consensus breaking

#2290 docs: add security section to x/mint README
  x/mint/README.md
Labels: documentation, x/mint

#2304 chore: bump rsmt2d to v0.11.0
  Makefile
  go.mod
  go.sum
Labels: backport:v1.x

#2301 feat: add qgb endpoint to query evm address
  proto/celestia/qgb/v1/query.proto
  x/qgb/keeper/keeper_valset_test.go
  x/qgb/keeper/query_general.go
  x/qgb/types/query.pb.go
  x/qgb/types/query.pb.gw.go
Labels: x/qgb, backport:v1.x

#2291 feat!: add feegranter option to txsim
  app/test/square_size_test.go
  test/cmd/txsim/cli.go
  test/e2e/simple_test.go
  test/txsim/account.go
  test/txsim/blob.go
  test/txsim/run.go
  test/txsim/run_test.go
  test/txsim/send.go
  test/txsim/sequence.go
  test/txsim/stake.go
Labels: txsim, backport:v1.x

#2307 feat!: make submitPFB broadcast mode configurable
  app/test/integration_test.go
  test/util/malicious/app_test.go
  x/blob/payforblob.go
Labels: api breaking

#2312 chore(deps): bump core to v1.26.2-tm-v0.34.28 (#2272)
  go.mod
  go.sum
Labels: dependencies, chore

#2311 chore: register the EVM address correctly in single-node scripts
  scripts/build-run-single-node.sh
  scripts/single-node.sh
Labels: x/qgb, chore

#2317 fix(test): skip the `TestSignerTestSuite` in test race
  Makefile
Labels: testing

#2319 fix(cmd): correctly use the log-to-file flag
  cmd/celestia-appd/cmd/root.go
Labels: bug, backport:v1.x

#2325 docs: update dead submit PFB link
  x/blob/README.md
Labels: documentation, backport:v1.x

#2314 chore: remove old signer and refactor tests
  app/ante/gov_test.go
  app/errors/insufficient_gas_price_test.go
  app/errors/nonce_mismatch_test.go
  app/test/check_tx_test.go
  app/test/fuzz_abci_test.go
  app/test/integration_test.go
  app/test/max_total_blob_size_test.go
  app/test/prepare_proposal_test.go
  app/test/process_proposal_test.go
  app/test/square_size_test.go
  app/test/std_sdk_test.go
  pkg/genesis/vesting_accounts_test.go
  pkg/proof/proof_test.go
  pkg/square/builder_test.go
  pkg/square/square_benchmark_test.go
  pkg/square/square_fuzz_test.go
  pkg/square/square_test.go
  pkg/user/signer.go
  pkg/user/signer_test.go
  pkg/user/tx_options.go
  pkg/wrapper/nmt_wrapper_test.go
  test/cmd/txsim/cli_test.go
  test/util/blobfactory/payforblob_factory.go
  test/util/blobfactory/payforblob_factory_test.go
  test/util/blobfactory/test_util.go
  test/util/blobfactory/test_util_test.go
  test/util/direct_tx_gen.go
  test/util/malicious/app.go
  test/util/malicious/app_test.go
  test/util/test_app.go
  test/util/testfactory/common.go
  test/util/testfactory/common_test.go
  test/util/testfactory/utils.go
  test/util/testnode/full_node.go
  test/util/testnode/full_node_test.go
  test/util/testnode/genesis_options.go
  test/util/testnode/node_interaction_api.go
  test/util/testnode/sign.go
  test/util/testnode/signer.go
  test/util/testnode/utils.go
  x/blob/client/testutil/integration_test.go
  x/blob/payforblob.go
  x/blob/types/blob_tx_test.go
  x/blob/types/builder.go
  x/blob/types/builder_options.go
  x/blob/types/builder_test.go
  x/blob/types/codec.go
  x/blob/types/estimate_gas_test.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
  x/blob/types/test/blob_tx_test.go
  x/blob/types/test_util.go
  x/mint/test/mint_test.go
  x/qgb/integration_test.go
  x/upgrade/test/integration_test.go
Labels: testing, refactor

#2335 fix: support MacOS in scripts
  scripts/build-run-single-node.sh
  scripts/single-node.sh
Labels: backport:v1.x

#2333 chore: upgrade to Go 1.21
  .github/workflows/lint.yml
  .github/workflows/test.yml
  Makefile
  README.md
  go.mod
  go.sum
Labels: chore, backport:v1.x

#2338 chore(deps): bump gogo proto and ethereum version
  go.mod
  go.sum
Labels: dependencies, backport:v1.x

#2339 fix: patch default fee checker priority calculation
  app/ante/ante.go
  app/ante/fee_checker.go
  app/ante/fee_checker_test.go
Labels: bug, backport:v1.x

#2356 docs: Updated namespace_id to namespaces in EventPayForBob doc. Fixes…
  x/blob/README.md
Labels: external

#2347 fix: PayForBlobs help text for namespace ID
  x/blob/client/cli/payforblob.go
Labels: bug, backport:v1.x

#2344 revert: genesis state tests for vesting accounts
  Makefile
  pkg/genesis/vesting_accounts.go
  pkg/genesis/vesting_accounts_test.go
  test/util/testfactory/common.go
  test/util/testnode/node_interaction_api.go
Labels: revert

#2357 docs: fix namespace size in comment
  proto/celestia/blob/v1/event.proto
  x/blob/types/event.pb.go
Labels: external, backport:v1.x

#2345 chore: remove `-compat` usage
  Makefile
Labels: chore, backport:v1.x

#2343 chore: remove `-mod=readonly` from Makefile
  Makefile
Labels: external, backport:v1.x

#2368 docs: fix namespace rules in x/blob/README.md
  x/blob/README.md
Labels: documentation, backport:v1.x

#2365 ci: run ci-release workflow on release branches
  .github/workflows/ci-release.yml
Labels: CI, backport:v1.x

#2367 ci: add new workflow for make test-short
  .github/workflows/test.yml
  Makefile
Labels: external, backport:v1.x

#2352 docs: specify the ante handler
  app/ante/ante.go
  app/ante/fee_checker.go
  app/ante/gov.go
  app/check_tx.go
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/specs/ante_handler.md
  specs/src/specs/block_validity_rules.md
Labels: documentation, specs, backport:v1.x

#2389 chore(blob): clarifies that hex values should not be 0x prefixed in the PayForBlobs subcommand
  x/blob/client/cli/payforblob.go
Labels: documentation, backport:v1.x

#2395 chore(deps): bump to nmt v0.19.0
  go.mod
  go.sum
Labels: backport:v1.x

#2397 chore!: bump the cosmos-sdk to include new vesting module changes
  app/test/std_sdk_test.go
  go.mod
  go.sum
Labels: dependencies, consensus breaking, backport:v1.x

#2394 chore: add test for tx priority
  Makefile
  app/test/priority_test.go
  pkg/user/tx_options.go
Labels: testing, mempool, backport:v1.x
