Repository celestiaorg/celestia-app, pull requests merged in 2023-02, with the labels that each got.

#1039 doc: document NMT wrapper in prepare_proposal
  app/prepare_proposal.go
  pkg/da/data_availability_header.go
Labels: documentation

#1330 feat: remove orchestrator address
  app/test/std_sdk_test.go
  go.mod
  go.sum
  scripts/single-node.sh
  testutil/common.go
  testutil/testnode/node_init.go
  x/qgb/abci_test.go
  x/qgb/keeper/keeper.go
Labels: x/qgb

#1334 chore: remove replace statement
  go.mod
Labels: dependencies

#1335 chore: use correct tag
  go.mod
  go.sum
Labels: dependencies

#1325 feat: add `LastValsetRequestBeforeNonce` rpc call
  proto/celestia/qgb/v1/query.proto
  x/qgb/keeper/keeper_valset.go
  x/qgb/types/query.pb.go
  x/qgb/types/query.pb.gw.go
Labels: x/qgb

#1341 feat!: differentiate namespaced padded shares
  pkg/shares/namespaced_padding.go
  pkg/shares/namespaced_padding_test.go
  pkg/shares/parse_sparse_shares.go
Labels: T:enhancement, share encoding

#1353 chore!: consistent share prefix for tail padding
  pkg/appconsts/appconsts.go
  pkg/da/data_availability_header.go
  pkg/da/data_availability_header_test.go
  pkg/shares/namespaced_padding.go
  pkg/shares/namespaced_padding_test.go
  pkg/shares/padding.go
  pkg/shares/padding_test.go
  pkg/shares/parse_sparse_shares.go
  pkg/shares/share_splitting.go
  pkg/shares/shares.go
  pkg/shares/shares_test.go
  pkg/shares/split_sparse_shares.go
  pkg/shares/tail_padding.go
  pkg/shares/tail_padding_test.go
Labels: share encoding

#1356 feat: expose the EVM private key used to create the testnode validator
  testutil/testnode/node_init.go
Labels: x/qgb, testing

#1357 chore!: rename `TxSharePosition` to `TxShareRange`
  pkg/proof/proof.go
  pkg/proof/proof_test.go
  x/qgb/client/verify.go
Labels: api breaking

#1359 docs: revise specs for padding shares
  specs/src/specs/consensus.md
  specs/src/specs/data_structures.md
Labels: specs

#1362 feat: `make help`
  Makefile
Labels: enhancement

#1327 feat!: Docker CI - Security added & Tagging updates - 2
  .github/workflows/docker-build-publish.yml
Labels: app, CI, blocked, docker

#1364 fix: Fix prefix `v` in RCs
  .github/workflows/docker-build-publish.yml
Labels: docker

#1368 feat: make the testnode port allocation dynamic
  testutil/testnode/full_node.go
  testutil/testnode/full_node_test.go
Labels: testing

#1372 feat: register testnode cleanup in teardown
  app/test/std_sdk_test.go
  testutil/testnode/full_node.go
Labels: testing

#1374 test: add QGB queries test
  app/test/qgb_rpc_test.go
Labels: x/qgb, testing

#1379 fix: add permissions to docker security build
  .github/workflows/docker-build-publish-common.yml
Labels: bug, CI

#1385 chore: explicitly set namespace size
  pkg/appconsts/appconsts.go
  pkg/wrapper/nmt_wrapper.go
  pkg/wrapper/nmt_wrapper_test.go
Labels: chore

#1383 refactor: Keep only the common Ci
  .github/workflows/docker-build-publish-common.yml
  .github/workflows/docker-build-publish.yml
Labels: CI, docker, refactor

#1389 feat: data commitment for height support for yet to be committed heights
  x/qgb/keeper/keeper_data_commitment.go
  x/qgb/keeper/keeper_data_commitment_test.go
Labels: x/qgb

#1401 refactor: Cleanup old Pipelines
  .github/workflows/amd64-docker-build.yml
  .github/workflows/main-docker-build.yml
Labels: dependencies, CI, refactor

#1411 chore: delete testnode home dir during cleanup
  testutil/testnode/full_node.go
Labels: testing

#1412 chore: fix qgb rpc flaky test
  app/test/qgb_rpc_test.go
Labels: testing

#1414 chore: update dead link
  docs/architecture/adr-012-sequence-length-encoding.md
Labels: CI

#1416 chore: remove duplicate error handling in `initFileStructure`
  testutil/testnode/node_init.go
Labels: chore

#1407 docs: hoist ADR status
  docs/architecture/adr-001-abci++-adoption.md
  docs/architecture/adr-002-qgb-valset.md
  docs/architecture/adr-003-qgb-data-commitments.md
  docs/architecture/adr-004-qgb-relayer-security.md
  docs/architecture/adr-005-qgb-reduce-state-usage.md
  docs/architecture/adr-006-non-interactive-defaults.md
  docs/architecture/adr-007-universal-share-prefix.md
  docs/architecture/adr-008-square-size-independent-message-commitments.md
  docs/architecture/adr-009-non-interactive-default-rules-for-reduced-padding.md
  docs/architecture/adr-011-optimistic-blob-size-independent-inclusion-proofs-and-pfb-fraud-proofs.md
  docs/architecture/adr-012-sequence-length-encoding.md
  docs/architecture/adr-template.md
Labels: documentation

#1406 docs: fix code coverage link
  README.md
Labels: documentation

#1417 fix: use a custom remove function to find the file causing the flakiness
  testutil/testnode/full_node.go
Labels: testing

#1420 chore: specifies minimum square size in non-interactive default rules
  specs/src/rationale/message_block_layout.md
Labels: documentation

#1423 chore: improve nmt wrapper tests
  pkg/wrapper/nmt_wrapper_test.go
Labels: testing

#1426 fix: better way to delete tendermint config folder
  testutil/testnode/full_node.go
  testutil/testnode/rpc_client.go
Labels: testing, CI

#1432 chore: bump core to v1.15.0
  go.mod
  go.sum
Labels: dependencies

#1433 chore: bump core to v1.15.0
  go.mod
  go.sum
Labels: dependencies
