Repository celestiaorg/celestia-app, pull requests merged in 2024-01, with the labels that each got.

#2974 docs: add column for governance modifiable params in resource_pricing
  specs/src/specs/resource_pricing.md
Labels: external

#2975 chore: remove unnecessary conversions
  .golangci.yml
  app/default_overrides.go
  app/default_overrides_test.go
  pkg/proof/proof.go
  pkg/shares/info_byte.go
  pkg/shares/shares.go
  pkg/square/square_test.go
  test/txsim/account.go
  x/mint/test/mint_test.go
  x/mint/types/constants.go
  x/upgrade/types/msgs.go
Labels: external

#2971 refactor: remove ValidateBasic in cli
  x/blobstream/client/tx.go
  x/upgrade/cli/tx.go
Labels: external

#2978 feat: add support for arabica-11 in download-genesis command
  cmd/celestia-appd/cmd/download_genesis.go
Labels: external

#2979 chore: bump core v1.31.0-tm-v0.34.29
  Makefile
  go.mod
  go.sum
  go.work.sum
  test/testground/go.mod
  test/testground/go.sum
Labels: backport:v1.x

#2970 refactor: Imporve signer confirm tx
  pkg/user/signer.go
  pkg/user/signer_test.go
Labels: external

#3022 chore: rename the codeowners contributor name
  .github/CODEOWNERS
Labels: chore

#3000 refactor: enable go-critic
  .golangci.yml
  app/test/prepare_proposal_test.go
  pkg/da/data_availability_header.go
  pkg/inclusion/commitment.go
  pkg/inclusion/nmt_caching_test.go
  pkg/inclusion/paths.go
  pkg/inclusion/paths_test.go
  pkg/shares/powers_of_two.go
  pkg/shares/share_builder.go
  pkg/shares/shares_test.go
  pkg/square/square.go
  pkg/square/square_test.go
  x/blob/client/testutil/integration_test.go
  x/blob/types/payforblob_test.go
  x/blobstream/types/validator.go
  x/upgrade/keeper.go
Labels: external

#3047 chore: The variable name has a typo
  test/util/genesis/document.go
Labels: external

#3007 test: increase test coverage for governance params
  go.work.sum
  x/paramfilter/test/gov_params_test.go
Labels: testing
