Repository celestiaorg/celestia-app, pull requests merged in 2024-07, with the labels that each got.

#3642 fix!: use POST for pfb submission
  proto/celestia/blob/v1/tx.proto
  x/blob/types/tx.pb.go
  x/blob/types/tx.pb.gw.go
Labels: WS: Maintenance 🔧

#3643 ci: run make test-interchain in CI
  .github/workflows/ci-release.yml
  .github/workflows/test-interchain.yml
  Makefile
  test/interchain/chainspec/celestia.go
  test/interchain/chainspec/cosmosHub.go
Labels: WS: V2 ✌️

#3659 chore(deps): upgrade to celestia-core v1.38.0
  test/interchain/go.mod
  test/interchain/go.sum
  test/testground/go.mod
  test/testground/go.sum
Labels: backport:v2.x

#3653 chore: fixes the link to namespace implementation
  specs/src/specs/namespace.md
Labels: chore

#3666 chore!: delete testground
  Makefile
  go.work.example
  pkg/appconsts/testground/app_consts.go
  pkg/appconsts/versioned_consts.go
  pkg/appconsts/versioned_consts_test.go
  test/testground/Dockerfile
  test/testground/README.md
  test/testground/compositions/standard/plan.toml
  test/testground/compositions/unbounded/cat.toml
  test/testground/compositions/unbounded/control.toml
  test/testground/compositions/unbounded/no_mempool.toml
  test/testground/compositions/utils.go
  test/testground/go.mod
  test/testground/go.sum
  test/testground/main.go
  test/testground/manifest.toml
  test/testground/network/command.go
  test/testground/network/command_test.go
  test/testground/network/configurators.go
  test/testground/network/consensus_node.go
  test/testground/network/entry_point.go
  test/testground/network/experiments.go
  test/testground/network/follower.go
  test/testground/network/leader.go
  test/testground/network/params.go
  test/testground/network/role.go
  test/testground/network/sync.go
  test/util/testnode/config.go
Labels: testground, WS: Maintenance 🔧

#3612 test: adding big block tests to the main branch
  test/e2e/benchmark/benchmark.go
  test/e2e/benchmark/main.go
  test/e2e/benchmark/manifest.go
  test/e2e/benchmark/throughput.go
  test/e2e/testnet/defaults.go
  test/e2e/testnet/node.go
  test/e2e/testnet/setup.go
  test/e2e/testnet/testnet.go
  test/txsim/run.go
Labels: WS: Big Blonks 🔭

#3675 docs: Rectify typographical inaccuracies
  docs/architecture/adr-001-abci++-adoption.md
  docs/architecture/adr-002-qgb-valset.md
  docs/architecture/adr-006-non-interactive-defaults.md
  docs/architecture/adr-018-network-upgrades.md
Labels: external

#3670 chore: improves code readability of e2e benchmark tests
  test/e2e/benchmark/benchmark.go
  test/e2e/benchmark/throughput.go
Labels: chore

#3661 docs: update specs for v2
  app/ante/ante.go
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/specs/ante_handler.md
  specs/src/specs/ante_handler_v1.md
  specs/src/specs/ante_handler_v2.md
  specs/src/specs/consensus.md
  specs/src/specs/data_structures.md
  specs/src/specs/index.md
  specs/src/specs/multisig.md
  specs/src/specs/networking.md
  specs/src/specs/parameters.md
  specs/src/specs/parameters_v1.md
  specs/src/specs/parameters_v2.md
  specs/src/specs/shares.md
  specs/src/specs/state_machine_modules.md
  specs/src/specs/state_machine_modules_v1.md
  specs/src/specs/state_machine_modules_v2.md
  x/paramfilter/test/gov_params_test.go
Labels: WS: V2 ✌️

#3680 test(testnode): configure custom min gas price
  app/test/testnode_test.go
  pkg/user/tx_client_test.go
  test/util/testnode/config.go
Labels: backport:v2.x

#3685 refactor(scripts): improve user prompts for single-node.sh
  scripts/single-node.sh
Labels: external

#3690 test: add Name to Account
  test/util/genesis/document.go
  test/util/genesis/genesis.go
  test/util/test_app.go
Labels: backport:v2.x

#3696 chore: skip testnode test in race mode
  Makefile
Labels: backport:v1.x, backport:v2.x

#3701 fix(goreleaser): do not mark rcs as latest release
  .goreleaser.yaml
Labels: backport:v1.x, backport:v2.x

#3705 chore: fix some comments
  README.md
  app/app.go
  app/module/manager.go
  local_devnet/celestia-app/app.toml
Labels: external

#3704 fix(docs/adr): spelling
  docs/architecture/adr-002-qgb-valset.md
  docs/architecture/adr-006-non-interactive-defaults.md
  docs/architecture/adr-018-network-upgrades.md
Labels: external

#3709 chore: add (start share == end share) check in parse namespace
  pkg/proof/proof_test.go
  pkg/proof/querier.go
Labels: chore, backport:v1.x, backport:v2.x

#3706 fix(test/e2e): name cannot be empty error
  test/e2e/testnet/testnet.go
  test/util/genesis/genesis.go
Labels: backport:v2.x

#3672 test: improves e2e tests performance by reading the block metadata instead of the entire block data
  test/e2e/benchmark/benchmark.go
  test/e2e/simple.go
  test/util/testnode/read.go
  test/util/testnode/read_test.go
Labels: enhancement, testing, WS: Big Blonks 🔭

#3725 chore(deps): upgrade to cosmos-sdk v1.24.0-sdk-v0.46.16
  go.mod
  go.sum
  test/interchain/go.mod
  test/interchain/go.sum
Labels: backport:v1.x, backport:v2.x

#3739 refactor: expose CreateShareToRowRootProofs for downstream use
  pkg/proof/proof.go
Labels: chore, backport:v1.x, backport:v2.x
