Repository celestiaorg/celestia-app, pull requests merged in 2024-04, with the labels that each got.

#3234 fix: fixes TestE2ESimple failure by ensuring positive initial stake for validator
  test/e2e/node.go
Labels: testing, fix

#3247 feat(ci): use release tracking workflow to notify devops
  .github/workflows/create_release_tracking_epic.yml
Labels: external

#3266 refactor: use celestia-core for CODEOWNERS
  .github/CODEOWNERS
Labels: backport:v1.x

#3244 test: adds the ability to run txsim as knuu instance for testground sanity test
  test/e2e/defaults.go
  test/e2e/node.go
  test/e2e/setup.go
  test/e2e/simple_test.go
  test/e2e/testnet.go
  test/e2e/throughput_test.go
  test/e2e/txsimNode.go
  test/e2e/upgrade_test.go
  test/util/genesis/accounts.go
  test/util/genesis/genesis.go
  test/util/testnode/config.go
Labels: testing, WS: Big Blonks 🔭

#3245 docs: adds documentation to proofs package
  pkg/proof/README.md
  pkg/proof/img/col_root_1.png
  pkg/proof/img/data_root.png
  pkg/proof/img/extended_square.png
  pkg/proof/img/row_root_1.png
  pkg/proof/img/row_root_2.png
  pkg/proof/img/row_root_3.png
  pkg/proof/img/row_root_to_data_root_proof.png
  pkg/proof/img/share_commitment.png
  pkg/proof/img/share_to_row_root_proof.png
  pkg/proof/img/share_to_share_commitment_inclusion.png
  pkg/proof/img/subtree_root_to_row_root.png
  pkg/proof/img/subtree_roots.png
Labels: documentation

#3286 fix: uses the specified volume amount for the genesis nodes
  test/e2e/node.go
Labels: fix

#3312 chore: improves description of --blob-amounts flag in txsim CLI
  test/cmd/txsim/cli.go
Labels: chore, WS: Big Blonks 🔭

#3326 chore: updates the upgrade module link to the signal module
  specs/src/specs/state_machine_modules.md
Labels: chore, backport:v1.x

#3319 feat(cli): addr-conversion
  cmd/celestia-appd/cmd/addr_converter.go
  cmd/celestia-appd/cmd/addr_converter_test.go
  cmd/celestia-appd/cmd/root.go
Labels: external

#3325 chore(txsim): removes deprecated `-r` flag from txsim docker README
  docker/README.md
Labels: chore, backport:v1.x

#3334 feat: updates docker file by exposing the tracing port 26661
  Dockerfile
Labels: backport:v1.x, WS: Big Blonks 🔭

#3355 docs: mentions known missing cluster configuration in test/e2e docs
  test/e2e/readme.md
Labels: documentation

#3359 chore: use errors.New to replace fmt.Errorf with no parameters
  test/txsim/account.go
  test/util/genesis/accounts.go
Labels: external

#3350 docs: add minikube instructions for test/e2e
  test/e2e/readme.md
Labels: documentation, testing

#3376 chore: POSIX compatible single-node
  scripts/single-node.sh
Labels: enhancement

#3385 feat: introduce gas multiplier to increase gas limit
  pkg/user/signer.go
  pkg/user/signer_test.go
Labels: external

#3310 feat!: disable x/blobstream in v2
  app/modules.go
  app/test/qgb_rpc_test.go
  specs/src/specs/state_machine_modules.md
  x/blobstream/README.md
  x/blobstream/client/suite_test.go
  x/blobstream/integration_test.go
  x/blobstream/keeper/hooks.go
  x/blobstream/keeper/hooks_test.go
  x/blobstream/module.go
Labels: WS: V2✌️

#3386 chore: add support for a local devnet
  local_devnet/README.md
  local_devnet/celestia-app/app.toml
  local_devnet/celestia-app/config.toml
  local_devnet/celestia-app/core0/config/gentx/gentx-e3c592c0c2ad4b05cef3791456b0d6dd4da72ed2.json
  local_devnet/celestia-app/core0/config/node_key.json
  local_devnet/celestia-app/core0/config/priv_validator_key.json
  local_devnet/celestia-app/core0/keyring-test/core0.info
  local_devnet/celestia-app/core0/keyring-test/e64b1f1302e7f9934f7f7a7bfae52d11a2d15d05.address
  local_devnet/celestia-app/core1/config/node_key.json
  local_devnet/celestia-app/core1/config/priv_validator_key.json
  local_devnet/celestia-app/core1/keyring-test/56d3d9fcadf711f5bfc4fefd8e92d9171db23229.address
  local_devnet/celestia-app/core1/keyring-test/core1.info
  local_devnet/celestia-app/core2/config/node_key.json
  local_devnet/celestia-app/core2/config/priv_validator_key.json
  local_devnet/celestia-app/core2/keyring-test/core2.info
  local_devnet/celestia-app/core2/keyring-test/ff2937f6477de47e5495f9dd863b6dc2d94458fc.address
  local_devnet/celestia-app/core3/config/node_key.json
  local_devnet/celestia-app/core3/config/priv_validator_key.json
  local_devnet/celestia-app/core3/keyring-test/core3.info
  local_devnet/celestia-app/core3/keyring-test/eeb259c4fdea3c6fd42463d7a82a21d2cd68713b.address
  local_devnet/celestia-app/genesis.json
  local_devnet/docker-compose.yml
  local_devnet/scripts/start_core0.sh
  local_devnet/scripts/start_node_and_create_validator.sh
  local_devnet/telemetry/grafana/datasources/config.yml
  local_devnet/telemetry/otel-collector/config.yml
  local_devnet/telemetry/prometheus/prometheus.yml
Labels: enhancement

#3328 chore(deps): bump .github version for release tracking epic
  .github/workflows/create_release_tracking_epic.yml
Labels: external

#3413 fix(ci): update from published to released trigger for deployment epic
  .github/workflows/create_release_tracking_epic.yml
Labels: external, backport:v1.x
