Repository celestiaorg/celestia-app, pull requests merged in 2024-02, with the labels that each got.

#3093 chore: update sdk and tm
  go.mod
  go.sum
  go.work.sum
  test/testground/go.mod
  test/testground/go.sum
Labels: backport:v1.x

#3104 chore: adds a note about namespace collisions in the namespace spec
  specs/src/specs/namespace.md
Labels: documentation

#3123 chore: typo fixes
  specs/src/specs/ante_handler.md
  specs/src/specs/block_validity_rules.md
Labels: external
