Repository celestiaorg/celestia-app, pull requests merged in 2024-06, with the labels that each got.

#3510 feat: add auto gas and fee estimations
  pkg/user/signer.go
  pkg/user/tx_client.go
  pkg/user/tx_client_test.go
Labels: external

#3514 test: enables local tracing in e2e benchmark tests
  test/e2e/benchmark/benchmark.go
  test/e2e/benchmark/manifest.go
  test/e2e/benchmark/throughput.go
  test/e2e/testnet/node.go
  test/e2e/testnet/setup.go
  test/e2e/testnet/testnet.go
  test/e2e/testnet/txsimNode.go
  test/e2e/testnet/util.go
Labels: testing, WS: Big Blonks 🔭

#3538 feat: allow user to set and update default gas price
  pkg/user/tx_client.go
  pkg/user/tx_client_test.go
  test/txsim/account.go
  test/util/testnode/rpc_client.go
Labels: WS: BestTxs

#3558 feat!: modify constraint for signal versions
  x/signal/keeper.go
  x/signal/keeper_test.go
  x/signal/types/errors.go
Labels: WS: V2 ✌️

#3554 test: circuit breaker for authz messages
  app/test/circuit_breaker_test.go
Labels: WS: Maintenance 🔧, WS: V2 ✌️

#3567 chore(x/signal)!: rename upgrade to signal in proto paths
  proto/celestia/signal/v1/query.proto
  proto/celestia/signal/v1/tx.proto
  x/signal/types/query.pb.go
  x/signal/types/query.pb.gw.go
  x/signal/types/tx.pb.go
  x/signal/types/tx.pb.gw.go
Labels: warn:api breaking

#3583 fix: rename remaining instances of GlobalMinGasPrice to NetworkMinGasPrice
  x/minfee/grpc_query.go
  x/minfee/grpc_query_test.go
Labels: WS: Maintenance 🔧

#3555 fix!: msg gatekeeper for authz messages
  app/ante/msg_gatekeeper.go
  app/ante/msg_gatekeeper_test.go
Labels: bug, consensus breaking, WS: Maintenance 🔧

#3591 fix: removes redundant attempts to start tx clients in the BenchmarkTest's Run method
  test/e2e/benchmark/benchmark.go
Labels: WS: Big Blonks 🔭

#3515 test: backports knuu optimizations from 3493
  test/e2e/testnet/node.go
  test/e2e/testnet/test_helpers.go
  test/e2e/testnet/testnet.go
Labels: knuu, WS: Big Blonks 🔭

#3602 chore!: deletes JSONRPCError from e2e test_helpers
  test/e2e/testnet/test_helpers.go
Labels: chore

#3618 chore(e2e benchmark test): allows selection of only one test
  test/e2e/benchmark/main.go
Labels: chore

#3640 chore: fixes link to the namespace implementation
  specs/src/specs/namespace.md
Labels: chore
