Repository celestiaorg/celestia-app, pull requests merged in 2024-11, with the labels that each got.

#4014 feat: add command to enable mptcp
  Makefile
Labels: WS: Maintenance 🔧, backport:v2.x

#4022 feat: add script to configure v3
  Makefile
  app/default_overrides.go
  docs/release-notes/release-notes.md
Labels: WS: V3 3️⃣, required

#4025 fix: replace bash syntax with sh in configure-v3
  Makefile
Labels: external

#4026 fix: replace any `ttl-num-blocks` value
  Makefile
Labels: external

#4030 docs: fix typos in prebuilt-binaries.md and release-guide.md
  docs/maintainers/prebuilt-binaries.md
  docs/maintainers/release-guide.md
Labels: external

#4047 feat: script to disable bbr
  Makefile
  go.mod
  go.sum
Labels: WS: Maintenance 🔧, backport:v2.x, backport:v3.x

#4044 fix: instruct GoReleaser to use current tag
  Makefile
Labels: backport:v3.x

#4045 fix: `query signal tally` after successful try upgrade
  x/signal/integration_test.go
  x/signal/keeper.go
  x/signal/keeper_test.go
Labels: backport:v3.x

#4059 chore(deps): upgrade to celestia-core v1.44.0
  go.mod
  go.sum
Labels: backport:v3.x

#4063 chore: check if a block is empty by taking its reference
  app/extend_block.go
  app/test/integration_test.go
Labels: chore, backport:v3.x
