Repository celestiaorg/celestia-app, pull requests merged in 2024-08, with the labels that each got.

#3747 test: makes network latency effective at earlier heights in benchmark tests
  test/e2e/benchmark/benchmark.go
  test/e2e/testnet/testnet.go
Labels: testing

#3752 chore: fix typos
  app/app.go
  app/test/prepare_proposal_test.go
  x/blob/README.md
Labels: external

#3754 feat: gRPC server for TxStatus endpoint
  app/app.go
  app/grpc/tx/server.go
  app/grpc/tx/tx.pb.go
  app/grpc/tx/tx.pb.gw.go
  app/test/std_sdk_test.go
  app/test/testnode_test.go
  buf.yaml
  proto/celestia/core/v1/tx/tx.proto
  test/util/testnode/testnode_test.go
Labels: backport:v1.x, backport:v2.x

#3749 chore: bump sdk to v1.24.1 and core to v1.39.0
  Dockerfile
  Makefile
  README.md
  docker/Dockerfile_txsim
  go.mod
  go.sum
  go.work.example
  test/interchain/go.mod
Labels: backport:v1.x, backport:v2.x

#3718 test: fixes e2e test failures due to increased timeout propose and timeout commit
  test/e2e/benchmark/benchmark.go
  test/e2e/testnet/setup.go
Labels: testing

#3765 feat!: support authored blobs
  app/default_overrides.go
  app/errors/insufficient_gas_price_test.go
  app/errors/nonce_mismatch_test.go
  app/test/check_tx_test.go
  app/test/consistent_apphash_test.go
  app/test/fuzz_abci_test.go
  app/test/integration_test.go
  app/test/process_proposal_test.go
  app/test/square_size_test.go
  app/test/std_sdk_test.go
  pkg/appconsts/global_consts.go
  pkg/appconsts/initial_consts.go
  pkg/da/data_availability_header_test.go
  pkg/inclusion/nmt_caching_test.go
  pkg/user/signer.go
  pkg/wrapper/nmt_wrapper.go
  pkg/wrapper/nmt_wrapper_test.go
  test/cmd/txsim/cli_test.go
  test/txsim/blob.go
  test/util/blobfactory/payforblob_factory.go
  test/util/malicious/out_of_order_builder.go
  test/util/malicious/tree.go
  test/util/test_app.go
  test/util/testfactory/blob.go
  test/util/testfactory/common.go
  test/util/testnode/config.go
  test/util/testnode/node_interaction_api.go
  x/blob/ante/ante_test.go
  x/blob/client/cli/payforblob.go
  x/blob/keeper/gas_test.go
  x/blob/keeper/keeper_test.go
  x/blob/types/blob_tx.go
  x/blob/types/blob_tx_test.go
  x/blob/types/errors.go
  x/blob/types/payforblob.go
  x/blob/types/payforblob_test.go
Labels: WS: V3 3️⃣, authored blobs

#3777 fix(scripts): single-node.sh chain ID
  scripts/single-node.sh
Labels: backport:v2.x

#3788 feat: add error log to txstatus
  app/grpc/tx/server.go
  app/grpc/tx/tx.pb.go
  app/test/big_blob_test.go
  app/test/prepare_proposal_context_test.go
  app/test/square_size_test.go
  app/test/std_sdk_test.go
  go.mod
  go.sum
  pkg/user/tx_client.go
  pkg/user/tx_client_test.go
  proto/celestia/core/v1/tx/tx.proto
  test/interchain/go.mod
  test/interchain/go.sum
  x/blobstream/integration_test.go
  x/signal/legacy_test.go
Labels: backport:v2.x

#3795 ci: fix goreleaser check deprecation warning
  .goreleaser.yaml
Labels: backport:v1.x, backport:v2.x

#3786 refactor: remove unnecessary `config.Seal()`
  app/config.go
  app/sdk_config.go
  app/sdk_config_test.go
  cmd/celestia-appd/cmd/root.go
Labels: backport:v2.x

#3774 feat: require bbr by default
  Makefile
  README.md
  cmd/celestia-appd/cmd/root.go
  cmd/celestia-appd/cmd/start.go
  scripts/single-node.sh
Labels: WS: Big Blonks 🔭

#3806 ci: use goreleaser-cross for goreleaser-check command
  .github/workflows/goreleaser.yml
  .goreleaser.yaml
  Makefile
Labels: backport:v2.x

#3833 ci(goreleaser): fix release candidate suffix
  .goreleaser.yaml
  docs/maintainers/prebuilt-binaries.md
Labels: backport:v2.x
