Repository celestiaorg/celestia-app, pull requests merged in 2024-09, with the labels that each got.

#3849 chore(go.mod): bump grafana/pyroscope-go deps
  go.mod
  go.sum
Labels: backport:v1.x, external, backport:v2.x

#3860 chore(go.mod): bump grafana/pyroscope-go deps
  go.mod
  go.sum
Labels: external

#3817 test!: adds the ability to set or unset bbr in e2e tests
  docs/maintainers/release-guide.md
  test/e2e/benchmark/benchmark.go
  test/e2e/benchmark/manifest.go
  test/e2e/benchmark/throughput.go
  test/e2e/major_upgrade_v2.go
  test/e2e/minor_version_compatibility.go
  test/e2e/simple.go
  test/e2e/testnet/node.go
  test/e2e/testnet/testnet.go
  tools/blocketa/README.md
Labels: bug, testing

#3868 chore(scripts): mainnet v2 upgrade height
  scripts/mainnet.sh
Labels: backport:v2.x

#3873 refactor(e2e): migrate the tests to the new knuu
  go.mod
  go.sum
  test/e2e/benchmark/benchmark.go
  test/e2e/benchmark/throughput.go
  test/e2e/main.go
  test/e2e/major_upgrade_v2.go
  test/e2e/minor_version_compatibility.go
  test/e2e/simple.go
  test/e2e/testnet/defaults.go
  test/e2e/testnet/node.go
  test/e2e/testnet/setup.go
  test/e2e/testnet/testnet.go
  test/e2e/testnet/txsimNode.go
Labels: external

#3887 docs: fix broken link
  pkg/wrapper/README.md
Labels: external

#3888 docs: fix upgrade doc link
  docs/release-notes/release-notes.md
Labels: external

#3892 fix: force no bbr when starting local devnet
  local_devnet/scripts/start_core0.sh
  local_devnet/scripts/start_node_and_create_validator.sh
Labels: testing

#3905 feat: build on network tags and manual dispatch
  .github/workflows/docker-build-publish.yml
Labels: external

#3900 chore: add a knuu getter
  test/e2e/testnet/testnet.go
Labels: testing

#3915 chore(deps): bump docker workflow version
  .github/workflows/docker-build-publish.yml
Labels: external

#3922 chore(ci): forward port setting in the mergify.yml
  .github/mergify.yml
Labels: external

#3924 fix(lint): golang-client lint errors
  .golangci.yml
  app/test/priority_test.go
  pkg/da/data_availability_header_test.go
  x/blob/client/testutil/integration_test.go
  x/blobstream/keeper/keeper_data_commitment.go
  x/blobstream/keeper/keeper_valset_test.go
  x/mint/client/testutil/suite_test.go
  x/mint/simulation/decoder_test.go
Labels: external, backport:v2.x
