Repository celestiaorg/celestia-app, pull requests merged in 2024-12, with the labels that each got.

#4068 refactor: remove sysctl dependency from start command
  cmd/celestia-appd/cmd/start.go
Labels: bug, external, backport:v3.x

#4078 fix: typographical errors in multiple files
  app/square_size.go
  docs/architecture/adr-011-optimistic-blob-size-independent-inclusion-proofs-and-pfb-fraud-proofs.md
  docs/architecture/adr-021-restricted-block-size.md
  specs/src/cat_pool.md
  x/blob/ante/blob_share_decorator.go
  x/blob/ante/max_total_blob_size_ante.go
  x/tokenfilter/README.md
Labels: external

#4061 docs: fix typo in `specs/src/cat_pool.md`
  specs/src/cat_pool.md
Labels: external

#4098 docs: fix transaction typos, grammar and documentation links
  specs/src/cat_pool.md
  specs/src/data_square_layout.md
  test/e2e/readme.md
Labels: external

#4086 feat(e2e/knuu): use latest release and prepare for node knuu tests
  go.mod
  go.sum
  test/e2e/benchmark/benchmark.go
  test/e2e/benchmark/throughput.go
  test/e2e/major_upgrade_v2.go
  test/e2e/major_upgrade_v3.go
  test/e2e/minor_version_compatibility.go
  test/e2e/simple.go
  test/e2e/testnet/node.go
  test/e2e/testnet/setup.go
  test/e2e/testnet/testnet.go
  test/e2e/testnet/txsimNode.go
  test/e2e/testnet/util.go
Labels: external

#4103 feat: override timeout commit via `--timeout-commit`
  Makefile
  README.md
  app/app.go
  app/app_test.go
  app/test/upgrade_test.go
  cmd/celestia-appd/cmd/app_exporter.go
  cmd/celestia-appd/cmd/app_server.go
  cmd/celestia-appd/cmd/root.go
  cmd/celestia-appd/cmd/start.go
  pkg/appconsts/chain_ids.go
  scripts/single-node.sh
  test/tokenfilter/setup.go
  test/util/malicious/app.go
  test/util/test_app.go
  test/util/testnode/config.go
  tools/chainbuilder/integration_test.go
  tools/chainbuilder/main.go
Labels: backport:v3.x

#4117 fix: multiple typos
  app/ante/tx_size_gas.go
  app/app.go
  app/app_test.go
  docker/Dockerfile
Labels: external

#4107 chore(test/interchain): upgrade cosmos-sdk and celestia-core versions
  test/interchain/go.mod
  test/interchain/go.sum
Labels: external

#4133 chore(deps): upgrade to cosmos-sdk v1.25.1
  go.mod
  go.sum
Labels: backport:v3.x

#4132 fix: typos
  specs/src/parameters_v1.md
  specs/src/parameters_v2.md
  x/blob/README.md
Labels: external

#4137 chore: fix some function names in comment
  test/util/test_app.go
  x/blobstream/abci_test.go
  x/blobstream/types/msgs.go
Labels: external

#4149 fix: typos
  docs/architecture/adr-004-qgb-relayer-security.md
Labels: external

#4148 chore: docs fix
  docs/architecture/adr-002-qgb-valset.md
Labels: external

#4145 fix: grammatical typos
  app/ante/ante.go
  app/export.go
  test/util/testfactory/namespace.go
  x/signal/types/keys.go
Labels: external

#4142 docs: fix URL
  specs/src/proto/types.proto
  specs/src/proto/wire.proto
Labels: external
