Repository celestiaorg/celestia-app, pull requests merged in 2024-10, with the labels that each got.

#3938 fix(ci): lint errors
  app/process_proposal.go
Labels: external

#3910 test: v3 e2e upgrade
  test/cmd/txsim/cli.go
  test/e2e/benchmark/benchmark.go
  test/e2e/main.go
  test/e2e/major_upgrade_v2.go
  test/e2e/major_upgrade_v3.go
  test/e2e/minor_version_compatibility.go
  test/e2e/simple.go
  test/e2e/testnet/key_generator.go
  test/e2e/testnet/node.go
  test/e2e/testnet/testnet.go
  test/e2e/testnet/txsimNode.go
  test/e2e/testnet/util.go
  test/txsim/upgrade.go
Labels: WS: V3 3️⃣, required

#3954 chore: optimize checkTx
  app/process_proposal.go
  app/test/prepare_proposal_test.go
  app/test/process_proposal_test.go
  app/validate_txs.go
  x/blob/ante/blob_share_decorator.go
  x/blob/ante/blob_share_decorator_test.go
Labels: optimization, WS: Maintenance 🔧, backport:v2.x

#3952 chore: pass knuu as an argument to the testnet.New
  test/e2e/benchmark/benchmark.go
  test/e2e/benchmark/throughput.go
  test/e2e/main.go
  test/e2e/major_upgrade_v2.go
  test/e2e/major_upgrade_v3.go
  test/e2e/minor_version_compatibility.go
  test/e2e/simple.go
  test/e2e/testnet/testnet.go
Labels: external

#3969 chore: appconsts godoc cosmetics
  pkg/appconsts/global_consts.go
Labels: chore

#3961 feat: increase default mempool `TTLNumBlocks` to 12
  app/default_overrides.go
  app/default_overrides_test.go
Labels: WS: V3 3️⃣

#3929 fix(ci): classify `-arabica` and `-mocha` releases as prereleases
  .goreleaser.yaml
Labels: external, backport:v2.x

#3882 feat!: versioned timeouts
  app/app.go
  app/default_overrides.go
  app/module/configurator_test.go
  app/test/upgrade_test.go
  go.mod
  go.sum
  local_devnet/docker-compose.yml
  pkg/appconsts/consensus_consts.go
  pkg/appconsts/global_consts.go
  pkg/appconsts/v1/app_consts.go
  pkg/appconsts/v2/app_consts.go
  pkg/appconsts/v3/app_consts.go
  pkg/appconsts/versioned_consts.go
  test/e2e/benchmark/benchmark.go
  test/e2e/benchmark/manifest.go
  test/e2e/major_upgrade_v3.go
  test/e2e/simple.go
  test/e2e/testnet/testnet.go
  test/e2e/testnet/txsimNode.go
  test/txsim/run_test.go
  test/util/genesis/genesis.go
  test/util/testnode/app_wrapper.go
  test/util/testnode/config.go
  test/util/testnode/network.go
  test/util/testnode/node_interaction_api.go
  x/blobstream/integration_test.go
  x/signal/integration_test.go
  x/signal/keeper.go
  x/signal/keeper_test.go
Labels: enhancement

#3994 chore: rename megabyte to mebibyte
  app/benchmarks/benchmark_msg_send_test.go
Labels: chore

#3996 chore(ci): remove release epic action
  .github/workflows/create_release_tracking_epic.yml
Labels: WS: V3 3️⃣, external, backport:v2.x

#4009 chore: bump txsim version
  test/e2e/testnet/defaults.go
Labels: testing, external

#4008 fix!: v3 upgrade delay
  app/test/square_size_test.go
  app/test/upgrade_test.go
  pkg/appconsts/chain_ids.go
  pkg/appconsts/versioned_consts.go
  pkg/appconsts/versioned_consts_test.go
  specs/src/parameters_v2.md
  specs/src/parameters_v3.md
  test/util/testnode/config.go
  x/signal/integration_test.go
  x/signal/keeper.go
  x/signal/keeper_test.go
Labels: bug, WS: V3 3️⃣, required

#4011 fix: enable tcp_bbr to load automatically after reboot
  Makefile
Labels: WS: Maintenance 🔧, WS: V2 ✌️, WS: V3 3️⃣, external, backport:v2.x
