Repository celestiaorg/celestia-app, pull requests merged in 2024-05, with the labels that each got.

#3426 fix: downgrade ibc main
  go.mod
  go.sum
Labels: dependencies

#3408 feat: adds functionality to read the blockchain headers into a csv file
  test/e2e/benchmark/throughput.go
  test/e2e/benchmark/utils.go
Labels: testing, WS: Big Blonks 🔭

#3425 fix: downgrade ibc and retract v1.8.0
  go.mod
  go.sum
Labels: dependencies

#3414 fix: MinorVersionCompatibility test
  test/e2e/check_upgrades.go
  test/e2e/main.go
  test/e2e/testnet/node.go
  test/e2e/testnet/node_helpers.go
  test/e2e/testnet/testnet.go
Labels: external

#3428 chore(txsim): enhances logging for debugging failed transactions
  test/txsim/account.go
Labels: chore, WS: Big Blonks 🔭

#3427 test: adds Nodes API to testnet
  test/e2e/testnet/testnet.go
Labels: testing, WS: Big Blonks 🔭

#3401 feat!: remove blobstream param subspace when upgrading to v2
  app/app.go
  app/test/upgrade_test.go
Labels: WS: V2✌️

#3438 chore(deps): upgrade to ibc-go v6.2.2
  go.mod
  go.sum
  test/interchain/go.mod
  test/interchain/go.sum
  test/testground/go.mod
  test/testground/go.sum
Labels: WS: V2✌️

#3443 chore(deps): bump go to v1.22.3
  Dockerfile
  Makefile
  README.md
  docker/Dockerfile_txsim
  go.mod
  go.work.example
  test/interchain/go.mod
  test/testground/Dockerfile
  test/testground/compositions/standard/plan.toml
  test/testground/go.mod
  test/testground/manifest.toml
Labels: dependencies, backport:v1.x

#3452 chore(deps): bump core version to v1.36.0-tm-v0.34.29
  go.mod
  go.sum
  test/interchain/go.mod
  test/interchain/go.sum
  test/testground/go.mod
  test/testground/go.sum
Labels: dependencies, backport:v1.x

#3459 feat: export BroadcastPayForBlob to support more async blob submission.
  pkg/user/signer.go
Labels: backport:v1.x, WS: BestTxs

#3461 chore: export NewShareInclusionProofFromEDS
  pkg/proof/proof.go
Labels: x/blobstream

#3454 test: extend minor version compat to test v2
  test/e2e/check_upgrades.go
  test/e2e/main.go
Labels: WS: V2✌️

#3467 docs: correct command of binary file
  x/blob/README.md
Labels: external

#3391 test(e2e benchmark): introduces test manifest and its related utilities
  test/e2e/benchmark/throughput.go
  test/e2e/check_upgrades.go
  test/e2e/simple.go
  test/e2e/testnet/defaults.go
  test/e2e/testnet/manifest.go
  test/e2e/testnet/node.go
  test/e2e/testnet/setup.go
  test/e2e/testnet/testnet.go
  test/e2e/testnet/txsimNode.go
Labels: testing, WS: Big Blonks 🔭

#3460 chore: export NewShareInclusionProofFromEDS
  pkg/proof/proof.go
Labels: x/blobstream

#3395 test(e2e benchmark): refactors E2EThroughput
  test/e2e/benchmark/benchmark.go
  test/e2e/benchmark/manifest.go
  test/e2e/benchmark/throughput.go
Labels: testing, WS: Big Blonks 🔭

#3494 test(e2e benchmark): adds network latency
  test/e2e/benchmark/benchmark.go
  test/e2e/benchmark/manifest.go
  test/e2e/benchmark/throughput.go
  test/e2e/testnet/node.go
Labels: testing, knuu, WS: Big Blonks 🔭

#3496 chore: extends single-node.sh script to support local tracing and traced data retrieval
  scripts/single-node.sh
Labels: chore, WS: Big Blonks 🔭

#3500 test: improve and test versioned ibc module
  app/module/mocks/versioned_ibc.go
  app/module/versioned_ibc_module.go
  app/module/versioned_ibc_module_test.go
Labels: WS: V2✌️

#3493 feat: improvements to big block tests
  go.mod
  go.sum
  test/e2e/benchmark/benchmark.go
  test/e2e/testnet/node.go
  test/e2e/testnet/node_helpers.go
  test/e2e/testnet/test_helpers.go
  test/e2e/testnet/testnet.go
  test/util/testnode/read.go
Labels: external, WS: Big Blonks 🔭

#3487 fix: e2e tests
  .github/workflows/nightly.yml
  .github/workflows/test-e2e.yml
  test/e2e/main.go
  test/e2e/major_upgrade_v2.go
  test/e2e/minor_version_compatibility.go
  test/e2e/testnet/testnet.go
Labels: knuu, WS: Maintenance 🔧
