Repository celestiaorg/celestia-app, pull requests merged in 2024-03, with the labels that each got.

#3017 feat: add gas estimation to the signer
  pkg/proof/proof_test.go
  pkg/user/signer.go
  pkg/user/signer_test.go
Labels: backport:v1.x

#3152 refactor!: rename to MaxEffectiveSquareSize
  app/prepare_proposal.go
  app/process_proposal.go
  app/square_size.go
  test/util/malicious/out_of_order_prepare.go
Labels: api breaking

#3179 fix: fixes e2e test failure by adjusting commit hash length in version recognition
  test/e2e/readme.md
  test/e2e/simple_test.go
Labels: fix

#3186 feat: add workdir to dockerfile
  Dockerfile
  docker/Dockerfile_txsim
Labels: external

#3196 feat: nonce handling with signer
  Makefile
  app/errors/insufficient_gas_price_test.go
  app/errors/nonce_mismatch.go
  app/errors/nonce_mismatch_test.go
  app/test/big_blob_test.go
  app/test/priority_test.go
  go.work.sum
  pkg/user/e2e_test.go
  pkg/user/signer.go
  pkg/user/signer_test.go
  test/util/blobfactory/payforblob_factory.go
  test/util/blobfactory/test_util.go
  test/util/direct_tx_gen.go
  x/blob/types/blob_tx_test.go
Labels: backport:v1.x
