Repository celestiaorg/celestia-app, pull requests merged in 2025-04, with the labels that each got.

#4474 feat: enable ability to start grpc server in standalone mode
  cmd/celestia-appd/cmd/start.go
  go.mod
  go.sum
Labels: external, backport:v3.x

#4459 feat(pkg/user): Implement gas price + usage estimation endpoints on `TxClient`, and option for using separate estimator service
  Makefile
  app/grpc/gasestimation/gas_estimator.go
  app/test/gas_estimation_test.go
  pkg/user/signer.go
  pkg/user/tx_client.go
  pkg/user/tx_client_test.go
  test/util/testnode/utils.go
Labels: WS: BestTxs, backport:v3.x

#4497 fix: add missing services
  cmd/celestia-appd/cmd/start.go
Labels: external

#4499 docs: fix link
  test/e2e/readme.md
Labels: external

#4500 docs: fix typo
  docs/architecture/adr-020-deterministic-square-construction.md
Labels: external

#4501 docs: document all Makefile targets
  Makefile
Labels: external

#4527 chore: update local devnet chain id to test
  local_devnet/celestia-app/config.toml
  local_devnet/celestia-app/core0/config/gentx/gentx-1c29bcd0d568df34f148b26205543566e4d1a177.json
  local_devnet/celestia-app/core0/config/gentx/gentx-e3c592c0c2ad4b05cef3791456b0d6dd4da72ed2.json
  local_devnet/celestia-app/core0/config/node_key.json
  local_devnet/celestia-app/core0/config/priv_validator_key.json
  local_devnet/celestia-app/genesis.json
  local_devnet/scripts/start_node_and_create_validator.sh
  pkg/appconsts/chain_ids.go
  pkg/appconsts/versioned_consts.go
  pkg/appconsts/versioned_consts_test.go
Labels: chore

#4538 chore: reenable priority mempool
  app/default_overrides.go
  app/default_overrides_test.go
  app/test/priority_test.go
  pkg/user/e2e_test.go
  pkg/user/tx_client_test.go
Labels: external

#4416 refactor: remove redundant import aliases
  .golangci.yml
  app/ante/fee.go
  app/app.go
  app/grpc/tx/server.go
  app/test/circuit_breaker_test.go
  pkg/appconsts/versioned_consts.go
  test/e2e/major_upgrade_v2.go
  test/e2e/major_upgrade_v3.go
  test/e2e/minor_version_compatibility.go
  test/pfm/simapp.go
  test/txsim/run_test.go
  test/util/genesis/modifier.go
  test/util/malicious/out_of_order_prepare.go
  x/blob/ante/ante_test.go
  x/blob/ante/blob_share_decorator_test.go
  x/blob/ante/max_total_blob_size_ante_test.go
  x/blob/keeper/keeper_test.go
  x/blob/types/payforblob.go
  x/mint/types/expected_keepers.go
  x/mint/types/minter_test.go
  x/signal/integration_test.go
  x/signal/keeper_test.go
Labels: external

#4531 docs: improve init command help output
  cmd/celestia-appd/cmd/init.go
  cmd/celestia-appd/cmd/root.go
Labels: external

#4575 chore!: remove blobstream related testing utils
  go.mod
  pkg/appconsts/global_consts.go
  test/multiplexer/multiplexer_test.go
  test/util/common.go
  test/util/test_app.go
  test/util/testfactory/common.go
Labels: testing

#4567 refactor: update benchmarks for app/v4
  Makefile
  app/benchmarks/README.md
  app/benchmarks/benchmark_ibc_update_client_test.go
  app/benchmarks/benchmark_msg_send_test.go
  app/benchmarks/benchmark_pfb_test.go
  app/benchmarks/gas_estimator_test.go
  pkg/appconsts/prepare_proposal_consts.go
  pkg/appconsts/prepare_proposal_consts_bench.go
Labels: external

#4570 chore: fix single script
  scripts/build-run-single-node.sh
  scripts/single-node-upgrades.sh
  scripts/single-node.sh
Labels: external

#4553 feat: add multiplexer
  .github/workflows/test.yml
  .gitignore
  Makefile
  cmd/celestia-appd/cmd/modify_root_command_multiplexer.go
  docker/Dockerfile
  docker/multiplexer.Dockerfile
  go.mod
  go.sum
  internal/embedding/celestia-app_Darwin_v3_arm64.tar.gz
  internal/embedding/celestia-app_Darwin_v3_x86_64.tar.gz
  internal/embedding/celestia-app_Linux_v3_arm64.tar.gz
  internal/embedding/celestia-app_Linux_v3_x86_64.tar.gz
  internal/embedding/celestia-app_darwin_v3_amd64.tar.gz
  internal/embedding/celestia-app_darwin_v3_arm64.tar.gz
  internal/embedding/celestia-app_linux_v3_amd64.tar.gz
  internal/embedding/celestia-app_linux_v3_arm64.tar.gz
  internal/embedding/data_darwin_amd64.go
  internal/embedding/data_darwin_arm64.go
  internal/embedding/data_linux_amd64.go
  internal/embedding/data_linux_arm64.go
  multiplexer/Makefile
  multiplexer/README.md
  multiplexer/abci/abci.go
  multiplexer/abci/errors.go
  multiplexer/abci/multiplexer.go
  multiplexer/abci/remote_v1.go
  multiplexer/abci/remote_v2.go
  multiplexer/abci/versions.go
  multiplexer/abci/versions_test.go
  multiplexer/appd/internal/testdata/celestia-app_Darwin_arm64.tar.gz
  multiplexer/appd/internal/testdata/celestia-app_Darwin_x86_64.tar.gz
  multiplexer/appd/internal/testdata/celestia-app_Linux_arm64.tar.gz
  multiplexer/appd/internal/testdata/celestia-app_Linux_x86_64.tar.gz
  multiplexer/appd/internal/testdata/data.go
  multiplexer/appd/internal/testdata/data_darwin_amd64.go
  multiplexer/appd/internal/testdata/data_darwin_arm64.go
  multiplexer/appd/internal/testdata/data_linux_amd64.go
  multiplexer/appd/internal/testdata/data_linux_arm64.go
  multiplexer/appd/option.go
  multiplexer/appd/option_test.go
  multiplexer/appd/run.go
  multiplexer/appd/run_test.go
  multiplexer/cmd/main.go
  multiplexer/cmd/passthrough.go
  multiplexer/cmd/passthrough_test.go
  multiplexer/cmd/start.go
  multiplexer/go.mod
  multiplexer/go.sum
  multiplexer/internal/utils.go
Labels: external, WS: V4

#4447 feat: implement gas price and gas limit customization for txsim
  test/cmd/txsim/cli.go
  test/txsim/account.go
  test/txsim/run.go
Labels: external, backport:v3.x

#4593 refactor: use one encoding.MakeConfig func
  app/ante/fee_test.go
  app/ante/panic_test.go
  app/ante/tx_size_gas_test.go
  app/app.go
  app/benchmarks/benchmark_ibc_update_client_test.go
  app/benchmarks/benchmark_msg_send_test.go
  app/benchmarks/benchmark_pfb_test.go
  app/benchmarks/gas_estimator_test.go
  app/default_overrides_test.go
  app/encoding/encoding.go
  app/errors/insufficient_gas_price_test.go
  app/errors/nonce_mismatch_test.go
  app/modules.go
  app/test/check_tx_test.go
  app/test/circuit_breaker_test.go
  app/test/fuzz_abci_test.go
  app/test/gas_estimation_test.go
  app/test/integration_test.go
  app/test/prepare_proposal_context_test.go
  app/test/prepare_proposal_test.go
  app/test/priority_test.go
  app/test/process_proposal_test.go
  app/test/square_size_test.go
  app/test/std_sdk_test.go
  pkg/user/tx_client_test.go
  test/cmd/txsim/cli.go
  test/cmd/txsim/cli_test.go
  test/txsim/run_test.go
  test/util/blobfactory/payforblob_factory_test.go
  test/util/blobfactory/test_util_test.go
  test/util/genesis/genesis.go
  test/util/testfactory/common_test.go
  test/util/testnode/comet_node_test.go
  test/util/testnode/node_interaction_api.go
  test/util/testnode/read.go
  test/util/testnode/signer.go
  test/util/testnode/utils.go
  x/blob/ante/ante_test.go
  x/blob/ante/blob_share_decorator_test.go
  x/blob/ante/max_total_blob_size_ante_test.go
  x/blob/test/decode_blob_tx_test.go
  x/blob/types/blob_tx_test.go
  x/blob/types/estimate_gas_test.go
  x/mint/simulation/decoder_test.go
  x/signal/keeper_test.go
Labels: external

#4579 feat: enable block api proxy when running in standalone mode
  cmd/celestia-appd/cmd/start.go
  go.mod
  go.sum
  test/util/testnode/rpc_client.go
Labels: external, WS: V4

#4596 build: bump embedded binary to v3.9.0-rc0
  Makefile
Labels: external

#4603 ci: build v3 docker images with multiple platforms
  .github/workflows/docker-build-publish.yml
Labels: external

#4602 feat: more robust multiplexer image for e2e upgrade test
  .github/workflows/docker-build-publish.yml
  Makefile
  docker/multiplexer.Dockerfile
Labels: external

#4609 test(testnode): update MaxBytes to 8 MiB
  test/util/testnode/config.go
Labels: external

#4608 fix: wire hyperlane module accounts in app
  app/app.go
Labels: external

#4611 refactor!: remove `GetCommitment`
  pkg/inclusion/get_commitment.go
  pkg/inclusion/get_commitment_test.go
Labels: external

#4615 docs: fix typos
  app/upgrades.go
  docker/multiplexer.Dockerfile
  go.mod
Labels: external

#4617 docs: replace TODO with links to blob inclusion and fraud proof documentation
  x/blob/README.md
Labels: external

#4597 build: set v2 upgrade height at build time
  Makefile
  cmd/celestia-appd/cmd/modify_root_command_multiplexer.go
  pkg/appconsts/upgrade_heights.go
Labels: external

#4621 refactor: replace context.TODO with context.Background in tx signing
  test/util/genesis/accounts.go
Labels: external

#4625 docs: fix typo tx_size_gas.go
  app/ante/tx_size_gas.go
Labels: external

#4616 docs: fix function name in comment
  app/param_filters.go
Labels: external

#4626 fix: add registration of tendermint and node services in standalone mode
  cmd/celestia-appd/cmd/start.go
Labels: external

#4627 refactor(benchmarks): align metric name to `block_size(mb)`
  app/benchmarks/benchmark_msg_send_test.go
Labels: external

#4634 build: pin to v0.1.0 of the multiplexer and remove local pin
  docker/Dockerfile
  docker/multiplexer.Dockerfile
  go.mod
  go.sum
Labels: external

#4645 docs: fix typo priority_test.go
  app/test/priority_test.go
Labels: external

#4635 test: add hyperlane integration test
  test/interop/ante.go
  test/interop/hyperlane_test.go
  test/interop/pfm_test.go
  test/interop/setup.go
  test/interop/simapp.go
  test/pfm/genesis.go
  test/pfm/setup.go
  test/tokenfilter/tokenfilter_test.go
Labels: external

#4653 test: add hyperlane disabled synthetic tokens test
  test/interop/hyperlane_test.go
Labels: external

#4652 refactor: use testsuites and mv tokenfilter testsuite to pkg test/interop
  test/interop/hyperlane_test.go
  test/interop/pfm_test.go
  test/interop/setup.go
  test/interop/tokenfilter_test.go
  test/tokenfilter/tokenfilter_test.go
Labels: external

#4655 chore: update the default address for remote ABCI over grpc
  go.mod
  go.sum
  multiplexer/abci/multiplexer.go
Labels: external

#4477 chore: remove coderabbit
  .coderabbit.yaml
Labels: backport:v3.x

#4661 docs: minor docstring fixups
  app/ante/fee.go
  app/ante/params.go
  app/app_test.go
  app/export.go
Labels: external

#4659 test: fix E2ESimple test
  test/e2e/simple.go
  test/e2e/testnet/defaults.go
  test/e2e/testnet/testnet.go
Labels: external

#4657 refactor: avoid re-downloading embedded binaries on every `make install`
  Makefile
Labels: external

#4675 refactor: remove embedding tests in multiplexer
  .github/workflows/test.yml
  multiplexer/abci/errors.go
  multiplexer/abci/multiplexer.go
  multiplexer/abci/remote_v1.go
  multiplexer/abci/remote_v2.go
  multiplexer/abci/versions_test.go
  multiplexer/appd/internal/testdata/celestia-app_Darwin_arm64.tar.gz
  multiplexer/appd/internal/testdata/celestia-app_Darwin_x86_64.tar.gz
  multiplexer/appd/internal/testdata/celestia-app_Linux_arm64.tar.gz
  multiplexer/appd/internal/testdata/celestia-app_Linux_x86_64.tar.gz
  multiplexer/appd/internal/testdata/data.go
  multiplexer/appd/internal/testdata/data_darwin_amd64.go
  multiplexer/appd/internal/testdata/data_darwin_arm64.go
  multiplexer/appd/internal/testdata/data_linux_amd64.go
  multiplexer/appd/internal/testdata/data_linux_arm64.go
  multiplexer/appd/run.go
  multiplexer/appd/run_test.go
  multiplexer/cmd/main.go
  multiplexer/cmd/start.go
Labels: external

#4672 fix: download v3 binaries on make build
  Makefile
  README.md
Labels: WS: V4

#4687 refactor(makefile): move embed binary logic to script
  Makefile
  scripts/download_v3_binary.sh
Labels: external

#4692 docs: update ADR-003 with reference to ADR-005 for confirms handling
  docs/architecture/adr-003-qgb-data-commitments.md
Labels: external

#4696 fix: download only current platform's embedded v3 binary in `make install`
  Makefile
Labels: external
