Repository celestiaorg/celestia-app, pull requests merged in 2025-09, with the labels that each got.

#5639 chore!: bump core v0.39.3
  Makefile
  app/app.go
  app/grpc/gasestimation/gas_estimator_e2e_test.go
  app/test/gas_estimation_test.go
  app/test/integration_test.go
  app/test/priority_test.go
  app/test/square_size_test.go
  cmd/celestia-appd/cmd/app_server.go
  cmd/celestia-appd/cmd/root.go
  go.mod
  go.sum
  pkg/appconsts/app_consts.go
  pkg/user/tx_client.go
  pkg/user/tx_client_test.go
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
  test/txsim/run_test.go
  test/util/malicious/app_test.go
  test/util/testnode/comet_node_test.go
  test/util/testnode/config.go
  test/util/testnode/network.go
  test/util/testnode/utils.go
Labels: WS: V6

#5756 chore: remove blrs region from talis
  tools/talis/digital_ocean.go
Labels: talis

#5798 fix: stop incrementing the sequence for each connection
  pkg/user/tx_client.go
  pkg/user/tx_client_test.go
Labels: WS: BestTxs

#5811 fix: compiler error
  pkg/user/tx_client.go
Labels: WS: Maintenance 🔧

#5707 feat: add open telemetry traces
  docs/maintainers/release-guide.md
  pkg/user/tx_client.go
  specs/src/recovery.md
  tools/check-eds-construction/README.md
Labels: WS: BestTxs, TxClient

#5776 feat: ability to submit PFBs in parallel
  Makefile
  pkg/user/account.go
  pkg/user/e2e_test.go
  pkg/user/mock_tx_server_test.go
  pkg/user/parallel_tx_submission.go
  pkg/user/parallel_tx_submission_test.go
  pkg/user/tx_client.go
  pkg/user/tx_client_test.go
  pkg/user/worker_account_test.go
  test/util/grpctest/mocks.go
Labels: WS: BestTxs
