Repository celestiaorg/celestia-app, pull requests merged in 2025-02, with the labels that each got.

#4283 docs: fix typo
  test/util/common.go
Labels: external

#4288 docs: fix typos
  x/blob/README.md
  x/blob/ante/ante_test.go
  x/blob/client/cli/util.go
Labels: external

#4287 chore: bump core to v1.47.0
  Makefile
  README.md
  docker/Dockerfile
  docker/txsim/Dockerfile
  go.mod
  go.sum
  go.work.example
  test/interchain/go.mod
  test/interchain/go.sum
Labels: backport:v3.x

#4290 refactor: fix typos
  app/app.go
  app/test/consistent_apphash_test.go
  x/paramfilter/test/gov_params_test.go
Labels: external

#4284 chore: update mempool defaults
  app/default_overrides.go
  app/default_overrides_test.go
Labels: backport:v3.x, defaults

#4294 docs: fix typos
  app/validate_txs.go
  pkg/proof/share_proof.go
Labels: external

#4297 docs: fix comment
  x/blobstream/genesis.go
Labels: external

#4296 refactor: fix typo in log
  x/blobstream/client/verify.go
Labels: external

#4309 docs: fix typo
  app/process_proposal.go
  x/mint/test/mint_test.go
Labels: external

#4306 docs: fix function names in comments
  app/errors/nonce_mismatch.go
  app/module/manager.go
  test/util/direct_tx_gen.go
Labels: external

#4302 refactor: fix typo
  x/blobstream/keeper/hooks_test.go
Labels: external

#4319 docs: fix typo
  x/mint/keeper/grpc_query.go
Labels: external

#4320 docs: fix grammar
  x/minfee/module.go
Labels: external

#4322 docs: fix typo
  x/mint/README.md
Labels: external

#4323 docs: fix typo
  x/mint/types/genesis.go
Labels: external

#4327 docs: fix typos
  proto/celestia/core/v1/da/data_availability_header.pb.go
  proto/celestia/core/v1/da/data_availability_header.proto
  specs/src/parameters_v3.md
Labels: external

#4208 refactor: use slices.Contains
  cmd/celestia-appd/cmd/download_genesis.go
  cmd/celestia-appd/cmd/start.go
Labels: external

#4334 docs: fix typo
  docs/architecture/adr-002-qgb-valset.md
Labels: external

#4338 docs: fix typo
  scripts/arabica-block-sync.sh
Labels: external

#4337 docs: fix typos
  docker/Dockerfile
  docs/architecture/adr-004-qgb-relayer-security.md
Labels: external

#4332 docs: fix typo
  local_devnet/celestia-app/app.toml
Labels: external

#4342 refactor: use maps.Clone to simplify the code
  test/pfm/simapp.go
Labels: external

#4344 revert: default mempool to prioritized (v1)
  app/default_overrides.go
  app/default_overrides_test.go
Labels: backport:v3.x

#4346 docs: fix typo
  docs/architecture/adr-003-qgb-data-commitments.md
Labels: external

#4353 docs: fix typos
  scripts/arabica.sh
  scripts/mocha.sh
Labels: external

#4358 fix: knuu e2e tests
  go.mod
  go.sum
  test/e2e/major_upgrade_v2.go
  test/e2e/major_upgrade_v3.go
  test/e2e/testnet/defaults.go
  test/e2e/testnet/testnet.go
Labels: external
