Repository celestiaorg/celestia-app, pull requests merged in 2025-08, with the labels that each got.

#5389 feat: query validators who have not signalled
  proto/celestia/signal/v1/query.proto
  x/signal/cli/query.go
  x/signal/interfaces.go
  x/signal/keeper.go
  x/signal/keeper_test.go
  x/signal/types/query.pb.go
  x/signal/types/query.pb.gw.go
Labels: external, forwardport:main

#5409 fix: improve event UnmarshalJSON
  go.mod
  go.sum
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
Labels: backport:v5.x

#5446 chore(deps): upgrade to v3.10.6
  .goreleaser.yaml
  Makefile
  docker/multiplexer.Dockerfile
  internal/embedding/data.go
Labels: backport:v5.x

#5482 refactor(multiplexer): upgrade directly after the commit
  multiplexer/abci/abci.go
Labels: multiplexer

#5485 ci: run go mod tidy on dependabot PRs
  .github/workflows/dependabot-tidy.yml
Labels: CI, priority:low

#5494 fix: refactor the e2e liveness check
  test/docker-e2e/e2e_block_sync_test.go
  test/docker-e2e/e2e_full_stack_pfb_test.go
  test/docker-e2e/e2e_simple_test.go
  test/docker-e2e/e2e_state_sync_test.go
  test/docker-e2e/e2e_test.go
  test/docker-e2e/e2e_upgrade_test.go
Labels: CI, flake, tastora

#5442 fix!: set ICA params during v6 upgrade handler
  app/app.go
  app/default_overrides.go
  app/default_overrides_test.go
  app/ica_host.go
  app/ica_host_test.go
  app/upgrades.go
  app/upgrades_test.go
  scripts/single-node-all-upgrades.sh
  scripts/single-node.sh
  test/util/test_app.go
Labels: required, WS: V6, required-mocha, required-arabica, required-rc

#5496 chore: add the v5 to v6 upgrade test case
  Makefile
  test/docker-e2e/e2e_upgrade_test.go
Labels: required, WS: V6, required-mocha, required-arabica, required-rc

#5526 feat!: implement CIP-41
  app/upgrades.go
  app/upgrades_test.go
  pkg/appconsts/app_consts.go
  scripts/min-commission-rate-proposal-v1.json
  scripts/min-commission-rate.sh
  scripts/single-node.sh
  test/util/test_app.go
  x/mint/README.md
  x/mint/client/testutil/grpc_test.go
  x/mint/client/testutil/suite_test.go
  x/mint/keeper/abci_test.go
  x/mint/types/constants.go
  x/mint/types/minter_test.go
Labels: required, required-mocha, required-arabica, required-rc

#5523 chore: bump to the unofficial commits for comet v0.39
  Makefile
  README.md
  app/test/gas_estimation_test.go
  docker/multiplexer.Dockerfile
  docker/standalone.Dockerfile
  docker/txsim/Dockerfile
  go.mod
  go.sum
  go.work.example
  pkg/user/e2e_test.go
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
  test/interchain/go.mod
  tools/chainbuilder/main.go
Labels: required, WS: V6, required-mocha, required-arabica, required-rc

#5611 chore: bump ibc to official tag
  go.mod
  go.sum
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
Labels: WS: V6, required-rc
