Repository celestiaorg/celestia-app, pull requests merged in 2025-01, with the labels that each got.

#4169 chore: fix typo
  docs/architecture/adr-011-optimistic-blob-size-independent-inclusion-proofs-and-pfb-fraud-proofs.md
Labels: external

#4150 chore: fix typos
  docs/architecture/adr-002-qgb-valset.md
  pkg/appconsts/global_consts.go
  pkg/appconsts/initial_consts.go
  pkg/da/data_availability_header_test.go
Labels: external

#4151 chore: fix typo
  test/pfm/simapp.go
Labels: external

#4162 chore: fix typos
  test/e2e/benchmark/throughput.go
  test/txsim/run_test.go
Labels: external

#4166 chore: fix typos
  pkg/proof/row_proof_test.go
  pkg/user/tx_client.go
Labels: external

#4163 chore: fix typos
  test/e2e/minor_version_compatibility.go
  test/txsim/stake.go
Labels: external

#4159 chore: fix quotation mark
  docs/architecture/adr-006-non-interactive-defaults.md
  local_devnet/celestia-app/config.toml
Labels: external

#4165 chore: fix typos
  README.md
  app/genesis.go
  docs/architecture/adr-001-abci++-adoption.md
Labels: external

#4167 chore: fix typo
  proto/celestia/qgb/v1/types.proto
  x/blobstream/types/types.pb.go
Labels: external

#4181 docs: fix typos
  test/util/malicious/out_of_order_prepare.go
  test/util/malicious/tree.go
Labels: external

#4182 docs: fix typo
  test/txsim/stake.go
Labels: external

#4180 docs: fix typo
  docs/architecture/adr-018-network-upgrades.md
Labels: external

#4187 docs: correct capitalization in release notes
  docs/release-notes/release-notes.md
Labels: external

#4198 docs: fix typo
  test/util/testnode/config.go
Labels: external

#4195 docs: fix typos in network upgrades and Docker documentation
  docs/architecture/adr-018-network-upgrades.md
  docs/maintainers/docker.md
  docs/release-notes/release-notes.md
Labels: external

#4183 docs: fix typos and grammar
  docs/architecture/adr-009-non-interactive-default-rules-for-reduced-padding.md
  docs/architecture/adr-011-optimistic-blob-size-independent-inclusion-proofs-and-pfb-fraud-proofs.md
Labels: external

#4188 docs: fix function name in comments
  pkg/da/data_availability_header.go
Labels: external

#4199 docs: fix typo
  test/util/malicious/test_app.go
Labels: external

#4197 chore(deps): upgrade to celestia-core v1.44.2
  go.mod
  go.sum
  test/interchain/go.mod
  test/interchain/go.sum
Labels: backport:v3.x

#4207 fix: correct typos in test function names and variables in nmt_wrapper_test.go
  pkg/wrapper/nmt_wrapper_test.go
Labels: external

#4206 fix: spelling errors
  docs/architecture/adr-001-abci++-adoption.md
  docs/architecture/adr-004-qgb-relayer-security.md
  docs/architecture/adr-009-non-interactive-default-rules-for-reduced-padding.md
Labels: external

#4214 docs: configure-v3
  Makefile
Labels: backport:v3.x

#4205 feat: increase max-recv-msg-size default to 20 MiB
  app/default_overrides.go
  app/default_overrides_test.go
Labels: backport:v3.x

#4220 chore(deps): sdk v1.26.1-sdk-v0.46.16
  go.mod
  go.sum
  test/interchain/go.mod
  test/interchain/go.sum
Labels: backport:v3.x

#4227 chore(deps): bump to core v1.45.0-tm-v0.34.35 and cosmos-sdk v1.27.0-sdk-v0.46.16
  go.mod
  go.sum
  test/interchain/go.mod
  test/interchain/go.sum
Labels: backport:v3.x

#4104 fix: tx client concurrency test
  pkg/user/e2e_test.go
  pkg/user/tx_client.go
Labels: backport:v3.x

#4237 chore: fix typo
  test/util/genesis/modifier.go
Labels: external

#4240 fix: broken links in markdown documentation
  README.md
  docs/release-notes/release-notes.md
  tools/blocktime/readme.md
  x/blob/README.md
Labels: external

#4248 chore: modify configure-v3 to update all default overrides
  Makefile
Labels: backport:v3.x

#4250 Update Makefile: Fix typo max_txs_bytes
  Makefile
Labels: external, backport:v3.x

#4252 fix: sed command on Linux
  Makefile
Labels: backport:v3.x

#4238 docs: gas used and gas price estimation ADR
  docs/architecture/adr-023-gas-used-and-gas-price-estimation.md
Labels: documentation

#4253 docs(typo): correct function config.go
  test/util/testnode/config.go
Labels: external

#4257 feat: implement the gas estimation API
  Makefile
  app/app.go
  app/grpc/gasestimation/gas_estimator.go
  app/grpc/gasestimation/gas_estimator.pb.go
  app/grpc/gasestimation/gas_estimator_test.go
  app/test/gas_estimation_test.go
  buf.lock
  buf.yaml
  docs/architecture/adr-023-gas-used-and-gas-price-estimation.md
  proto/celestia/core/v1/gas_estimation/gas_estimator.proto
Labels: WS: BestTxs

#4264 docs: improve error handling documentation and messages
  app/errors/errors.go
Labels: external

#4270 feat: add the gas estimation API to the signer
  pkg/user/signer.go
  pkg/user/tx_client_test.go
Labels: WS: BestTxs, backport:v3.x
