Repository celestiaorg/celestia-app, pull requests merged in 2025-05, with the labels that each got.

#4702 fix: update the default bond denom in default_overrides
  app/default_overrides.go
  app/default_overrides_test.go
Labels: external

#4720 fix: correct version command in Makefile
  Makefile
  docker/txsim/Dockerfile
Labels: external

#4719 refactor: update v3 line to use standalone registry
  .github/workflows/docker-build-publish.yml
  Makefile
  test/e2e/readme.md
  test/e2e/testnet/node.go
Labels: external

#4718 refactor: change image registries
  .github/workflows/docker-build-publish.yml
  Makefile
  docker/multiplexer.Dockerfile
  test/e2e/readme.md
  test/e2e/testnet/node.go
Labels: external

#4736 refactor(multiplexer): remove separate go.mod
  .github/workflows/test.yml
  Makefile
  cmd/celestia-appd/cmd/modify_root_command_multiplexer.go
  docs/maintainers/release-guide.md
  go.mod
  go.sum
  multiplexer/abci/multiplexer.go
  multiplexer/abci/remote_v1.go
  multiplexer/abci/versions.go
  multiplexer/cmd/main.go
  multiplexer/cmd/passthrough.go
  multiplexer/cmd/passthrough_test.go
  multiplexer/cmd/start.go
  multiplexer/go.mod
  multiplexer/go.sum
Labels: WS: V4

#4697 docs: fix typo
  multiplexer/README.md
Labels: external

#4754 fix: use 36658 for abci over grpc for v3.x
  cmd/celestia-appd/cmd/start.go
  local_devnet/celestia-app/config.toml
Labels: external

#4628 feat(user): Add support for multiple core endpoints to TxClient
  pkg/user/tx_client.go
  pkg/user/tx_client_test.go
  test/util/grpctest/mocks.go
Labels: enhancement, WS: BestTxs, external

#4761 fix: use standard default app home v3
  README.md
  app/init_test.go
Labels: external

#4760 fix: use standard appDirectory where applicable
  README.md
  cmd/celestia-appd/cmd/testnet.go
  docker/Dockerfile
  docker/multiplexer.Dockerfile
  docker/txsim/Dockerfile
Labels: external

#4764 test(scripts): add missing genesis
  local_devnet/celestia-app/genesis.json
  multiplexer/cmd/start.go
Labels: external

#4768 docs: remove stray ‘)’ in bank tx proto link
  specs/src/data_square_layout.md
Labels: external

#4767 fix: ensure core block api runs through multilplexer native app
  docker/multiplexer.Dockerfile
  multiplexer/abci/multiplexer.go
Labels: external

#4777 docs(x/mint): update README for CIP-29
  x/mint/README.md
  x/mint/types/minter_test.go
Labels: WS: V4

#4795 chore(specs/multisig): use versioned link to avoid ci breakages
  specs/src/multisig.md
Labels: external

#4801 refactor(multiplexer): simplify `getState`
  multiplexer/cmd/start.go
Labels: external

#4809 docs: fix dead link
  test/interop/simapp.go
Labels: external

#4703 test: add docker based E2E tests
  .github/workflows/test-e2e.yml
  test/docker-e2e/Makefile
  test/docker-e2e/e2e_simple_test.go
  test/docker-e2e/e2e_state_sync_test.go
  test/docker-e2e/e2e_test.go
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
Labels: external

#4827 fix: followup fixes to new E2E docker tests
  .github/workflows/test-e2e.yml
  Makefile
  go.mod
  test/docker-e2e/Makefile
  test/docker-e2e/e2e_state_sync_test.go
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
Labels: external

#4835 fix: use correct test in ci workflow
  .github/workflows/test-e2e.yml
Labels: external

#4853 fix: make passthrough show help
  multiplexer/cmd/passthrough.go
  multiplexer/cmd/passthrough_test.go
Labels: external

#4843 test: move E2E tests to run on each PR
  .github/workflows/test-e2e.yml
  .github/workflows/test.yml
  test/docker-e2e/e2e_test.go
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
Labels: external

#4852 chore: update tendermint/celestia-core version
  go.mod
  go.sum
  test/docker-e2e/go.mod
Labels: external

#4862 fix: build docker image for multiple platforms
  .github/workflows/docker-build-publish.yml
Labels: external

#4861 chore: remove unused parameters
  Makefile
  docker/Dockerfile
  docker/multiplexer.Dockerfile
Labels: external

#4864 ci: update go releaser to support multiplexer
  .goreleaser.yaml
  Makefile
  scripts/download_v3_binary.sh
Labels: external

#4863 test: adding multiplexer tests
  .github/workflows/test.yml
  Makefile
  multiplexer/appd/run.go
  multiplexer/appd/run_test.go
Labels: external
