Repository celestiaorg/celestia-app, pull requests merged in 2025-06, with the labels that each got.

#4944 fix: ensure remote abci conn ports are aligned
  go.mod
  go.sum
  multiplexer/abci/multiplexer.go
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
Labels: external

#4958 fix(app): disable `query consensus comet` CLI command
  app/app.go
Labels: external

#4972 docs(specs): Fix Decimal type spec link to current location
  specs/src/proto/types.proto
Labels: external

#4970 fix(cmd): pass down log options
  cmd/celestia-appd/cmd/root.go
  multiplexer/abci/multiplexer.go
Labels: external

#4998 feat(tools): allow disabling metrics reporting for blob submission latency tool
  tools/latency-monitor/main.go
Labels: external

#5000 chore(ci): update runner
  .github/workflows/goreleaser.yml
Labels: external

#5006 docs: fix function name
  multiplexer/abci/multiplexer.go
Labels: external

#5025 feat(test/cmd/txsim): Allow predefined set of namespaces for blob submission
  test/cmd/txsim/cli.go
  test/txsim/blob.go
Labels: external, txsim

#5034 chore: misc talis improvements
  Makefile
  tools/talis/deployment.go
  tools/talis/init.go
Labels: testing, talis

#5043 ci: update actions/cache to v4
  .github/copilot-setup-steps.yml
Labels: external

#4823 fix(test/util): legacy genesis should use `app_version`
  test/util/genesis/legacy_genesis.go
Labels: external

#5065 fix(appconsts)!: reduce upgrade height delay for testnets
  pkg/appconsts/v4/app_consts.go
  pkg/appconsts/v4/app_consts_test.go
  pkg/appconsts/versioned_consts.go
  pkg/appconsts/versioned_consts_test.go
Labels: backport:v4.x

#5071 docs: fix some minor issues in the comments
  docs/release-notes/release-notes.md
  tools/talis/README.md
  tools/talis/config.go
  tools/talis/genesis.go
Labels: external

#5059 fix(multiplexer): shut down on CTRL + C
  multiplexer/abci/multiplexer.go
Labels: bug

#5079 feat: add a network throughput measuring tool
  tools/throughput/main.go
  tools/throughput/readme.md
Labels: tools

#5093 chore: rate limit creation/destruction of DO droplets
  tools/talis/deployment.go
  tools/talis/digital_ocean.go
Labels: talis

#5068 chore: remove knuu e2e tests
  .github/workflows/test-e2e.yml
  Makefile
  go.mod
  go.sum
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
  test/e2e/benchmark/benchmark.go
  test/e2e/benchmark/main.go
  test/e2e/benchmark/manifest.go
  test/e2e/benchmark/throughput.go
  test/e2e/main.go
  test/e2e/major_upgrade_v4.go
  test/e2e/readme.md
  test/e2e/simple.go
  test/e2e/test_data/v3genesisAppState.json
  test/e2e/testnet/defaults.go
  test/e2e/testnet/key_generator.go
  test/e2e/testnet/node.go
  test/e2e/testnet/setup.go
  test/e2e/testnet/test_helpers.go
  test/e2e/testnet/testnet.go
  test/e2e/testnet/txsimNode.go
  test/e2e/testnet/util.go
  test/e2e/testnet/versions.go
  test/e2e/testnet/versions_test.go
Labels: backport:v4.x
