Repository celestiaorg/celestia-app, pull requests merged in 2025-07, with the labels that each got.

#5158 docs: fix typos
  tools/talis/README.md
Labels: external

#5171 feat: talis download list of tables
  tools/talis/download.go
Labels: priority:low, talis

#5172 feat: support the talis reset command
  tools/talis/README.md
  tools/talis/main.go
  tools/talis/reset.go
Labels: priority:low, talis

#5181 docs: fix typos in txsim Docker Image Usage Guide
  docker/txsim/README.md
Labels: external

#5196 docs: fix comments
  tools/blocketa/main.go
  tools/blockheight/main.go
Labels: external

#5195 fix(multiplexer): wait for v3 app to stop before starting v4
  multiplexer/abci/multiplexer.go
  multiplexer/appd/run.go
  multiplexer/appd/run_test.go
Labels: forwardport:main

#5210 docs: fix typo
  pkg/user/tx_client_test.go
Labels: external

#5215 chore(scripts): improve mainnet state sync script
  scripts/mainnet.sh
Labels: backport:v4.x

#5141 refactor: update E2E tests to use new builder pattern
  test/docker-e2e/dockerchain/config.go
  test/docker-e2e/dockerchain/testchain.go
  test/docker-e2e/e2e_simple_test.go
  test/docker-e2e/e2e_state_sync_test.go
  test/docker-e2e/e2e_test.go
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
  test/util/genesis/accounts.go
Labels: external

#5229 chore: bump core to fix EventAttribute unmarshalling
  go.mod
  go.sum
Labels: dependencies, backport:v4.x

#5219 test: adding test to perform state sync with mocha
  .github/workflows/test-nightly.yml
  test/docker-e2e/dockerchain/config.go
  test/docker-e2e/e2e_state_sync_test.go
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
  test/docker-e2e/networks/config.go
  test/docker-e2e/networks/networks.go
Labels: external

#5231 feat(x/signal): emit custom events
  x/signal/integration_test.go
  x/signal/keeper.go
  x/signal/keeper_test.go
  x/signal/types/msgs.go
Labels: forwardport:main, backport:v4.x

#5238 docs: fix typos
  pkg/appconsts/app_consts.go
  test/interop/simapp.go
  test/multiplexer/multiplexer_test.go
  tools/talis/init.go
Labels: external

#5254 typo: Remove development note from section header
  docs/architecture/adr-002-qgb-valset.md
Labels: external

#5255 test: update test to use existing tastora fns
  test/docker-e2e/dockerchain/config.go
  test/docker-e2e/e2e_upgrade_test.go
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
  test/util/genesis/genesis.go
Labels: external

#5251 test: Basic Full Stack E2E Test
  .github/workflows/test.yml
  test/docker-e2e/dockerchain/config.go
  test/docker-e2e/e2e_full_stack_pfb_test.go
  test/util/genesis/genesis.go
Labels: external

#5266 fix: update go mod to v2.3.1 of go-square
  go.mod
  go.sum
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
Labels: external, backport:v4.x

#5267 docs: fix typos
  docs/architecture/adr-022-multi-versioned-state-machine.md
  tools/latency-monitor/main.go
  tools/talis/digital_ocean.go
  tools/talis/genesis.go
Labels: external

#5253 docs: update to v5
  README.md
  docs/release-notes/release-notes.md
  specs/src/ante_handler.md
  specs/src/ante_handler_v5.md
  specs/src/parameters.md
  specs/src/parameters_v5.md
  specs/src/state_machine_modules.md
  specs/src/state_machine_modules_v5.md
Labels: external

#5275 fix: tx client overrides fee to 1utia if set
  pkg/user/tx_client.go
  pkg/user/tx_client_test.go
Labels: external, backport:v4.x

#5283 docs: add the informal audit report for the recovery mechanism
  README.md
  docs/audit/informal-systems-recovery.pdf
Labels: documentation, external

#5298 refactor: modernized code with built-in func
  test/cmd/txsim/cli.go
  test/interop/simapp.go
  tools/chainbuilder/benchmark_test.go
  tools/talis/download.go
  x/mint/types/minter_test.go
Labels: external

#5139 fix: tx client evictions bug
  go.mod
  go.sum
  pkg/user/tx_client.go
  pkg/user/tx_client_test.go
  tools/throughput/readme.md
Labels: backport:v4.x

#5305 docs: fix tokenfilter link
  specs/src/state_machine_modules_v1.md
  specs/src/state_machine_modules_v2.md
  specs/src/state_machine_modules_v3.md
Labels: external

#5304 fix: ensure gas estimator provides a price greater than the network and local min gas price
  Makefile
  app/app.go
  app/benchmarks/gas_estimator_test.go
  app/grpc/gasestimation/gas_estimator.go
  app/grpc/gasestimation/gas_estimator_e2e_test.go
  app/grpc/gasestimation/gas_estimator_test.go
  test/util/genesis/accounts.go
  test/util/genesis/genesis.go
  test/util/genesis/modifier.go
Labels: external, backport:v4.x

#5309 fix: iavl unlock of unlocked mutex
  go.mod
  go.sum
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
Labels: external, backport:v4.x

#5319 refactor: replace hardcoded chain IDs with appconsts references
  cmd/celestia-appd/cmd/download_genesis.go
  cmd/celestia-appd/cmd/download_genesis_test.go
  multiplexer/abci/abci_test.go
  test/docker-e2e/dockerchain/testchain.go
  test/docker-e2e/e2e_full_stack_pfb_test.go
  test/docker-e2e/networks/config.go
  test/util/testnode/utils.go
  tools/talis/README.md
  tools/talis/config.go
Labels: external

#5334 docs(specs): revise v5 params
  specs/src/parameters_v5.md
Labels: external

#5314 fix(app): register a v5 upgrade handler
  .goreleaser.yaml
  Makefile
  app/app.go
  app/upgrades.go
  docker/multiplexer.Dockerfile
  go.mod
  go.sum
  internal/embedding/data.go
  scripts/single-node-v5.sh
  test/docker-e2e/go.mod
  test/docker-e2e/go.sum
Labels: external

#5337 ci: upgrade to Node.js 24
  .github/workflows/markdown-linter.yml
Labels: external

#5323 fix(x/blob): event for update blob params
  x/blob/types/events.go
Labels: external

#5351 chore: update upgrade script to v5
  scripts/single-node-upgrades.sh
Labels: external

#5354 docs: fix comments
  x/blob/types/genesis.go
Labels: external

#5348 chore: support workers during s3 deployments and fix traces download directory
  tools/talis/deployment.go
  tools/talis/download.go
Labels: priority:low, external

#5359 fix: go releaser attaches binaries
  Makefile
Labels: external, forwardport:main

#5361 fix(goreleaser): download_binary script name
  .goreleaser.yaml
Labels: external, forwardport:main

#5368 docs: add release notes for v5
  docs/release-notes/release-notes.md
Labels: external

#5335 refactor(appconsts): use explicit number of mebibytes for max bytes
  pkg/appconsts/initial_consts.go
Labels: external

#5371 docs(x/mint): fix comment
  x/mint/types/minter.go
Labels: external

#5377 chore(deps): upgrade embedded binary to celestia-app v4.1.0
  .goreleaser.yaml
  Makefile
  docker/multiplexer.Dockerfile
  internal/embedding/data.go
  test/docker-e2e/dockerchain/config.go
  test/docker-e2e/e2e_test.go
Labels: external, WS: V5
