Repository celestiaorg/celestia-app, pull requests merged in 2025-03, with the labels that each got.

#4372 docs: fix typo
  docs/maintainers/release-guide.md
Labels: external

#4377 docs: fix grammar in logs
  test/e2e/benchmark/main.go
Labels: external

#4354 docs: Fix spelling errors in `app.toml`
  local_devnet/celestia-app/app.toml
Labels: external

#4384 docs: fix typo
  specs/src/data_square_layout.md
Labels: external

#4381 refactor(x/blob): use t.TempDir() instead of os.MkdirTemp
  x/blob/client/testutil/integration_test.go
Labels: external

#4340 fix(txsim): improved grpc server discovery, added default keypath value
  Makefile
  test/cmd/txsim/cli.go
  test/cmd/txsim/cli_test.go
  test/txsim/run.go
Labels: external

#4398 docs: fix typos
  app/errors/insufficient_gas_price.go
  pkg/user/tx_client.go
  scripts/mainnet.sh
Labels: external

#4393 docs: fix typo
  docs/architecture/adr-020-deterministic-square-construction.md
  docs/architecture/adr-022-multi-versioned-state-machine.md
Labels: external

#4399 refactor: remove duplicate `SetMinRetainBlocks` invocation
  cmd/celestia-appd/cmd/app_server.go
  test/util/malicious/test_app.go
Labels: external

#4397 feat(e2e): use dev k8s cluster for e2e tests
  .github/workflows/test-e2e.yml
Labels: external

#4415 refactor: remove x/exp dependency for slices package
  x/blob/types/payforblob.go
Labels: external

#4411 feat: update the gas estimation mechanism to use the mempool
  app/app.go
  app/benchmarks/gas_estimator_test.go
  app/grpc/gasestimation/gas_estimator.go
  app/grpc/gasestimation/gas_estimator_test.go
  app/test/gas_estimation_test.go
  docs/architecture/adr-023-gas-used-and-gas-price-estimation.md
Labels: WS: BestTxs, backport:v3.x

#4420 chore(deps): bump core to v1.51.0-tm-v0.34.35
  go.mod
  go.sum
  test/interchain/go.mod
  test/interchain/go.sum
Labels: dependencies, backport:v3.x

#4425 docs: improve proto comments
  app/grpc/tx/tx.pb.go
  proto/celestia/core/v1/tx/tx.proto
  proto/celestia/qgb/v1/query.proto
  x/blobstream/types/query.pb.go
Labels: external

#4438 docs: fix broken links in docs
  docs/architecture/adr-023-gas-used-and-gas-price-estimation.md
  x/minfee/README.md
  x/signal/README.md
Labels: external

#4448 ci: add SHAs and commented versions in workflow .yml files
  .github/workflows/codeql.yml
  .github/workflows/docker-build-publish.yml
  .github/workflows/github-pages.yml
  .github/workflows/goreleaser.yml
  .github/workflows/issue-label-automation.yml
  .github/workflows/lint-pull-request.yml
  .github/workflows/lint.yml
  .github/workflows/markdown-linter.yml
  .github/workflows/pr-review-requester.yml
  .github/workflows/project-automation.yml
  .github/workflows/protobuf.yml
  .github/workflows/stale.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test.yml
Labels: external

#4450 refactor: modernized code with built-in func
  app/ante/tx_size_gas.go
  pkg/inclusion/nmt_caching_test.go
  tools/blocktime/main.go
Labels: external

#4449 feat: adjust the estimated gas price for high and medium priority
  app/grpc/gasestimation/gas_estimator.go
  app/grpc/gasestimation/gas_estimator_test.go
  docs/architecture/adr-023-gas-used-and-gas-price-estimation.md
Labels: WS: BestTxs, backport:v3.x

#4414 feat!: reduce upgrade height delay for Arabica and Mocha
  docs/release-notes/pending-release.md
  pkg/appconsts/versioned_consts.go
  pkg/appconsts/versioned_consts_test.go
  x/signal/keeper_test.go
Labels: backport:v3.x

#4463 chore(deps): upgrade to go-square v2.2.0
  go.mod
  go.sum
Labels: backport:v3.x

#4466 fix: BlobShareDecorator check for nested authz messages
  x/blob/ante/blob_share_decorator.go
  x/blob/ante/blob_share_decorator_test.go
Labels: backport:v3.x

#4465 fix: MinGasPFB decorator check for nested authz messages
  x/blob/ante/ante.go
  x/blob/ante/ante_test.go
Labels: backport:v3.x

#4470 feat(ante)!: reject MsgExec if it contains a MsgExec or MsgPayForBlobs
  app/ante/ante.go
  app/ante/msg_exec.go
  app/ante/msg_exec_test.go
Labels: backport:v3.x

#4453 feat: wire module-by-hash debug command
  cmd/celestia-appd/cmd/root.go
  go.mod
  go.sum
Labels: external, backport:v3.x

#4479 docs: Fix binary docs for enabling and checking BBR.
  cmd/celestia-appd/cmd/start.go
Labels: documentation
